### ISSUE TITLE
Not explicit error message when command is in /sbin (Debian)

### ISSUE THREAD

**Issue by stone-w4tch3r** [Fizzadar/pyinfra#1023]
## Describe the bug
On debian, when using without sudo an operation, that under the hood uses command from /sbin, pyinfra will rethow debian's "command not found" message.

Issue is that debian don't add executables from /sbin to PATH, and without sudo they are "not found", while with sudo everything is ok (yeah, hate it too)

## To Reproduce
1. Run: `pyinfra inventory.py server.user user=ubuntu shell="/usr/bin/bash"`
2. Error: `sh: 1: usermod: not found`

+ Target system information
OS: Debian GNU/Linux 12 (bookworm) x86_64, Kernel: 6.1.0-13-amd64
(via @ssh in multipass vm)

## Expected behavior
Error like "Permission denied"

## Meta
+ Include output of `pyinfra --support`.
```
pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.37
      Release: 6.2.0-36-generic
      Machine: x86_64
    pyinfra: v2.8
    Executable: /home/user/Projects/linux_stuff/pyinfra_manager/venv/bin/pyinfra
    Python: 3.11.4 (CPython, GCC 12.3.0)
```
+ How was pyinfra installed (source/pip)?
**Pip**
+ Include pyinfra-debug.log (if one was created)
**None found**
+ Consider including output with `-vv` and `--debug`.
```
--> Beginning operation run...
--> Starting operation: Server/User (user=ubuntu, shell=/usr/bin/bash)
[primary.multipass] >>> env SUDO_ASKPASS=/tmp/pyinfra-sudo-askpass-cHx4fFUKupSc *** sh -c 'usermod -s /usr/bin/bash ubuntu'
    [primary.multipass] sh: 1: usermod: not found
    [primary.multipass] Error: executed 0/1 commands
```

**Comment by Fizzadar** [comment]
I don't think this is a bug, pyinfra is not responsible for managing `PATH` so I think failing this way is the correct behavior, just as it would fail running the command over SSH by hand. Happy to move to a discussion, but closing this issue for now.
