### ISSUE TITLE
files.block prepends a dollar sign when markers exist but content does not match

### ISSUE THREAD

**Issue by mgranville** [Fizzadar/pyinfra#1028]
## Describe the bug
files.block prepends a dollar sign when markers exist but content does not match. I suspect the bug is here https://github.com/pyinfra-dev/pyinfra/blob/7540c41fa0284b8dd80dcbea24d3616414484d60/pyinfra/operations/files.py#L1765

**Comment by stone-w4tch3r** [comment]
@Fizzadar this can be closed)

**Comment by Fizzadar** [comment]
Thank you @stone-w4tch3r for the fix 🙏!
