### ISSUE TITLE
Why using system commands such as `awk`, `sed` and so on instead of native python functions when working with files?

### ISSUE THREAD

**Issue by stone-w4tch3r** [Fizzadar/pyinfra#1029]
## Is your feature request related to a problem? Please describe
From user's perspective it is not very convenient to work with operations that hide such commands under the hood. You can't treat strings just as strings, escaping and preventing from command substitution is needed. 
It weakens pyinfra's abstraction from shell

## Describe the solution you'd like
Python already has functions for manipulating files and strings. This can decrease possibility of bugs, related to tool's differences on various systems, and simplify working with strings for users 

## P.S.
I faced this issue when working with files.Block, when trying to put string `eval "$(thefuck -a)"` into `.zshrc`.
Underlying `awk` expanded this to something like `eval "alias fuck='eval "$(TF_ALIAS=fuck PYTHONIOENCODING=utf-8 thefuck "$(fc -ln -1)")"'"`

When running again, got this error:
```
Files/Block (path=/home/ubuntu/.zshrc, content=['alias cat=ccat', 'alias less=cless', "alias git_cp='echo -n commit message:  && read -r message && echo $message | git add . && git commit -m $message && git push'", 'eval "$(thefuck -a)"'], marker=#### {mark} ALIASES BLOCK ####)
    [primary.multipass] nested awk: fatal: cannot open file `"$(TF_ALIAS=fuck' for reading (No such file or directory)
```

**Comment by Fizzadar** [comment]
The reason for this is simple - we don't require Python on the remote size. The entire design of pyinfra is based on the idea of "do what a human would making changes over SSH", if we were to move all the logic into Python code we loose that.

It's limiting in some ways for sure, but I believe the benefits outweigh that. Any bugs such as the block one just have to be handled, and so far in pyinfra's history these have been pretty rare, certainly rare enough to not warrant a change.
