### ISSUE TITLE
Package managers for other operating systems

### ISSUE THREAD

**Issue by cynddl** [Fizzadar/pyinfra#103]
I'm opening this issue to discuss support for package managers on other operating systems than Debian and Fedora. Currently, pyinfra seem to have only modules for apt and yum. I can likely contribute for:

1. the ``homebrew`` package manager for macOS,
2. the ``pacman`` package manager for Archlinux.

Let me know if that could be useful. I haven't found anything online, but maybe someone here has already written formulas for that?

**Comment by Fizzadar** [comment]
Hi @cynddl I'd love to see homebrew/pacman support added to pyinfra! I don't believe there are any formulas already out there.

Implementation wise the [apt module](https://github.com/Fizzadar/pyinfra/blob/develop/pyinfra/modules/apt.py#L218) and [apt facts](https://github.com/Fizzadar/pyinfra/blob/develop/pyinfra/facts/apt.py#L58) should serve as a good reference point :)

**Comment by Fizzadar** [comment]
Closing this as have just added #185 #186 & #187 to track these individually!
