### ISSUE TITLE
pyinfra does not exit with failure when operations are wrapped in python.call

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#1050]
## Describe the bug

pyinfra does not exit with failure (non-zero exit code) when operations wrapped in python.call are failed. When something goes wrong and there are Errors, the command line should report a non-zero exit code.

## To Reproduce
Steps to reproduce the behavior, please include where possible:

```python
from pyinfra.operations import python, server


def foo():
    # fails
    server.shell("/bin/false")

python.call(foo)
```

Run: `pyinfra @local deploy.py`

```
--> Results:
    Groups: @local
    [@local]   Changed: 1   No cahnge: 0   Errors: 1
```

The process exit code is 0!

## Expected behavior

non-zero exit code.

## Meta
+ Include output of `pyinfra --support`

```
    System: Linux
      Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
      Release: 5.15.0-91-generic
      Machine: x86_64
    pyinfra: v2.8
    Executable: /SOME/PATH/.venv/bin/pyinfra
    Python: 3.10.12 (CPython, GCC 11.4.0)

```

+ How was pyinfra installed (source/pip)? pip
+ Include pyinfra-debug.log (if one was created)
+ Consider including output with `-vv` and `--debug`.

**Comment by Fizzadar** [comment]
This should now be fixed in https://github.com/pyinfra-dev/pyinfra/commit/87e73c68c9890b965e359e4cf4d3f1bf4439873a, released just now in v2.9.1.
