### ISSUE TITLE
Docstrings not displayed for functions using the operator decorator

### ISSUE THREAD

**Issue by Denperidge** [Fizzadar/pyinfra#1055]
## Describe the bug
On VSCode, you cannot view the docstrings for operations (e.g. server.user() and the like). This seems to be because of the `@operation` wrapper

## To Reproduce
- In VSCode (or possibly other IDE's)
- Do an operation import (e.g. `from pyinfra.operations import server`)
- Hover over the usage of an import (e.g. `server.user(`)
- If all goes wrong, there's no docstrings placed

![A VSCode screenshot of server.user being hovered over. There are no docstrings nor keywords shown. This is the first descriptor of the 2](https://github.com/pyinfra-dev/pyinfra/assets/27348469/ccf10076-f6cb-4c65-8c84-aad476b4f423)
![A VSCode screenshot of server.user being hovered over, but with the second descriptor selected. There are no docstrings nor keywords shown](https://github.com/pyinfra-dev/pyinfra/assets/27348469/ac0b830f-5b72-4784-a778-48b74153b768)

Alternatively, you can add `from pyinfra.api import operation` and test this out on a local function. As seen below, the docstrings get jambled up as soon as the `@operation` decorator is used.
![A VSCode screenshot of a simple function called meow.  The docstring is displayed, and no parameters are shown to be available, as is the case](https://github.com/pyinfra-dev/pyinfra/assets/27348469/5c241314-fc77-4d9a-a40e-64147bfaed85)
![A VSCode screenshot of a simple function called meow, but with the @ operation decorator.  The docstring is no longer displayed, and there are now unclear parameters are shown to be available, even though this is not the case](https://github.com/pyinfra-dev/pyinfra/assets/27348469/eacbb15d-e992-4131-b3b3-a962b690d4ce)

## Expected behavior
The docstrings displaying! This is the output when copying the `server.user` function, but don't add the decorator!
[A VSCode screenshot of a function descriptor. server.user got copied without the `@operation` hovered over. Docstrings are displayed as expected, and the keywords are visible](https://github.com/pyinfra-dev/pyinfra/assets/27348469/1d8fac35-5ce1-4b05-9b5d-41b06e59bc8e)

## Possible solution?
In terms of Python3, I was only able to find this bug thread in the sphinx repository: https://github.com/sphinx-doc/sphinx/issues/3783 . It describes multiple potential solutions (e.g. functools.wrap, or custom wrapping thing)

## Meta
+ Include output of `pyinfra --support`.
```
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .   
    When adding an issue, be sure to include the following:

    System: Windows
      Platform: Windows-10-10.0.19045-SP0
      Release: 10
      Machine: AMD64
    pyinfra: v2.8
    Executable: C:\Python311\Scripts\pyinfra.exe       
    Python: 3.11.4 (CPython, MSC v.1934 64 bit (AMD64))
```
+ How was pyinfra installed (source/pip)? **Using pip!**
+ Include pyinfra-debug.log (if one was created) N/A
+ Consider including output with `-vv` and `--debug`. N/A

**Comment by Fizzadar** [comment]
Hi @Denperidge, would you mind trying this with the v3.b0 release? I’ve rewritten the type annotations for operations and have tested it working in VSCode.

**Comment by Denperidge** [comment]
Sorry for the late reply @Fizzadar , but here to confirm that it is fixed in v3.b0! Thank you very much!
