### ISSUE TITLE
Link on "Support" page out of date

### ISSUE THREAD

**Issue by phlummox** [Fizzadar/pyinfra#1056]
## Description

The "Support" page for PyInfra (https://docs.pyinfra.com/en/2.x/support.html) suggests asking queries by "chatting on [the `pyinfra` Discord](https://discord.gg/w3XxuKw)".

But the welcome message in the Discord forum states it has been deprecated in favour of a Matrix forum, at <https://matrix.to/#/%23pyinfra:matrix.org>.

p.s. Thanks for all your work on PyInfra!

**Comment by Fizzadar** [comment]
Thanks for spotting this! Fixed via https://github.com/pyinfra-dev/pyinfra/commit/ed46565f5aa8535d03d9368905f0734325e54251
