### ISSUE TITLE
`_shell_executable=None` is ignored in inventory

### ISSUE THREAD

**Issue by vojta001** [Fizzadar/pyinfra#1064]
## Describe the bug
Since #724 we can use `--shell-executable None` in CLI to make pyinfra not explicitly specify a shell (crucial for non-POSIX targets). I struggle to opt in for the same behavior using the inventory file only.

## To Reproduce

`inventory.py:`
```python
test = [
    ("example.tld", {"_shell_executable": None, "ssh_user": "root"})
]
```

```bash
pyinfra -vvv inventory.py exec date
```

The output is

```
--> Loading config...

--> Loading inventory...

--> Connecting to hosts...
    [example.tld] Connected
    [example.tld] Ready: shell

--> Proposed changes:
    Groups: test / inventory
    [example.tld]   Operations: 1   Change: 1   No change: 0


--> Beginning operation run...
--> Starting operation: Server/Shell (date)
[example.tld] >>> sh -c date
[example.tld] Sun Feb  4 11:17:36 CET 2024
    [example.tld] Success


--> Results:
    Groups: test / inventory
    [example.tld]   Changed: 1   No change: 0   Errors: 0
```

Compare it with
```bash
pyinfra --shell-executable None -vvv inventory.py exec date
```

and its output

```--> Loading config...

--> Loading inventory...

--> Connecting to hosts...
    [example.tld] Connected
    [example.tld] Ready: shell

--> Proposed changes:
    Groups: inventory / test
    [example.tld]   Operations: 1   Change: 1   No change: 0


--> Beginning operation run...
--> Starting operation: Server/Shell (date)
[example.tld] >>> date
[example.tld] Sun Feb  4 11:17:59 CET 2024
    [example.tld] Success


--> Results:
    Groups: inventory / test
    [example.tld]   Changed: 1   No change: 0   Errors: 0
```

It's the `[example.tld] >>> sh -c date` vs. `[example.tld] >>> date`.

## Meta
+ Include output of `pyinfra --support`.
```
--> Support information:
    System: Linux
      Platform: Linux-6.1.75-x86_64-with-glibc2.38
      Release: 6.1.75
      Machine: x86_64
    pyinfra: v2.8
    Executable: /nix/store/pwk54za44zp4q0x6p9sm0vr78s66gcy3-python3.11-pyinfra-2.8/bin/pyinfra
    Python: 3.11.6 (CPython, GCC 12.3.0)
```
+ How was pyinfra installed (source/pip)? distribution's package manager `nix`

**Comment by Fizzadar** [comment]
Hi @vojta001, thank you for reporting this. I've pushed a fix (unfortunately messed up the commit here) in https://github.com/pyinfra-dev/pyinfra/commit/8177f500d60a650313f20f2f4cce8f313d41e70c and just released that in v2.9.1. Would you be able to retry to confirm this is fixed?

**Comment by Fizzadar** [comment]
Fixed, cherry picked into v3 branch.

**Comment by vojta001** [comment]
@Fizzadar Thank you for fixing this and sorry for the long delay to test the patch. I can now confirm the issue is gone.

**Comment by Fizzadar** [comment]
@vojta001 no worries at all appreciate you checking in 🙏
