### ISSUE TITLE
Return whether and operation changed

### ISSUE THREAD

**Issue by tino** [Fizzadar/pyinfra#1065]
I'd like to be able to do this:
```
changed = files.put("files/postgres/compose.yml", "postgres/compose.yml")
if changed:
    server.shell("cd postgres && docker compose up -d")
```

So I can run steps conditionally on whether something changed. Or is there a better way to do this?

PS. Sorry I post this here, I went for the Questions button, ended up on an unused Discord that linked me to Matrix, which I don't have but told me I could use Thunderbird (which I do have) but that didn't work ¯\_(ツ)_/¯.

**Comment by vojta001** [comment]
This is already implemented, have a look at https://docs.pyinfra.com/en/2.x/using-operations.html#operation-changes-output

**Comment by tino** [comment]
Nvm, I found out that this is already possible!

```python
compose = files.put("files/postgres/compose.yml", "postgres/compose.yml")
if compose.changed:
    server.shell("cd postgres && docker compose up -d")
```
