### ISSUE TITLE
`--quiet` command line flag has no effect

### ISSUE THREAD

**Issue by moderation** [Fizzadar/pyinfra#1113]
## Describe the bug
In the `v3.x` branch, the `--quiet` command line flag no longer works

## To Reproduce
`pyinfra pi.local --quiet exec -- go version`

```
NAME="openSUSE Tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240524"

pyinfra --support

    System: Linux
      Platform: Linux-6.9.1-1-default-x86_64-with-glibc2.39
      Release: 6.9.1-1-default
      Machine: x86_64
    pyinfra: v3.0b1
    Executable: /home/moderation/.local/bin/pyinfra
    Python: 3.12.3 (CPython, GCC)
```

## Expected behavior
Expect reduced output as per `--quiet    Hide most pyinfra output.`. Output is exactly the same with or without the `--quiet` flag.

## Meta
`pyinfra` built from source from `HEAD` with `python3.12 -m pip install --break-system-packages --user --upgrade .`

**Comment by Fizzadar** [comment]
Thanks for spotting this, @moderation, I'm going to remove it as broken, should have been dropped in v3.0.

**Comment by Fizzadar** [comment]
Closed via https://github.com/pyinfra-dev/pyinfra/commit/682030db2026620439b2bfaf92118846901ba47e
