### ISSUE TITLE
Syntax for conditional tasks

### ISSUE THREAD

**Issue by martenlienen** [Fizzadar/pyinfra#1124]
At the moment, the useful utilities `any_changed` and `all_changed` in `pyinfra/operations/util/__init__.py` are broken because `OperationMeta.did_change` now returns a context manager instead of a boolean. This enables the syntax
```python
with op.did_change:
    pass
```
and the utilities would need to call `_did_change` instead. Personally, I would prefer keep `did_change` as what is now `_did_change` and fully rely on `host.when` to write conditional blocks like
```python
with host.when(op.did_change)):
    pass

# or
with host.when(any_changed(config_file_op, symlink_op)):
    pass
```
This makes it easier for users to write custom helper functions similar to `any_changed` without having to rely on internal underscore methods and, maybe more importantly, more clearly communicates that the `with` block represents a conditional in my eyes, because it has the word `when` in it.

What do you think?

I don't have time to propose a change myself at the moment but wanted to put this in writing before a 3.0 version is released.

**Comment by TobyGiacometti** [comment]
I am in favor of this proposal as well. The changes that made it into 3.0 effectively broke any previously (beta0) working code that used `OperationMeta.did_change`/`OperationMeta.did_not_change` (for example `_if=op.did_change`). Relying on `Host.when()` exclusively and reverting `OperationMeta.did_change`/`OperationMeta.did_not_change` to the previous implementation enables flexible change conditions, which are currently only possible when using `OperationMeta._did_change()` or `OperationMeta.changed` (deprecated).

**Comment by martenlienen** [comment]
It is a pity that 3.0 was released without fixing this. But since this is definitely broken, maybe it can be changed as a bug-fix release. The syntax for conditionals is not well documented anyway, I believe. @Fizzadar What do you think?

**Comment by Fizzadar** [comment]
Hi @martenlienen @TobyGiacometti apologies for missing this one before v3. Agree this is a bug and not as designed, though ideally both options would be supported. Unfortunately the context manager is the only way to do blocks of “if” statements.

I’ll have a think, but treating this  as a high priority bug for a 3.0.2 release.

**Comment by TobyGiacometti** [comment]
`Host.when()` is a nice addition, and I agree that it should remain. I just don't think that `OperationMeta.did_change` and `OperationMeta.did_not_change` should be wrappers for `Host.when()`. If one wants to use `with` blocks for conditional operations, it can be done easily without having to have said getters return a context manager:

- `Host.when(lambda: op.did_change)` if `OperationMeta.did_change` is a getter that returns a boolean.
- `Host.when(op.did_change)` if `OperationMeta.did_change` is a method that returns a boolean (how it was before 60f3d03)

**Comment by martenlienen** [comment]
From my perspective, returning `op.did_change` to the old state would be nice together with the new `host.when`. It would enable the syntax that I proposed in the opening post which gives a lot of freedom and reads quite well even when you are not too familiar with pyinfra, e.g.
```
# For a single operation
with host.when(op.did_change)):
    pass

# or with the utilities
with host.when(any_changed(config_file_op, symlink_op)):
    pass

# and allows any custom checks such as this weird one that only triggers if more than 3 operations changed.
with host.when(lambda: sum(op.did_change() for op in some_ops) > 3):
    pass
```

**Comment by Fizzadar** [comment]
Totally agree- this syntax is nice and simple and makes more sense than the other thing, fixed: https://github.com/pyinfra-dev/pyinfra/commit/31436958dad033dfc9678341f2bc0869fbde9bc8 & tested: https://github.com/pyinfra-dev/pyinfra/commit/d1921949dd84519a03ef3359eba75daa4b2cbfbf. 3.0.2 incoming.

**Comment by TobyGiacometti** [comment]
Thank you @Fizzadar!

**Comment by martenlienen** [comment]
Thanks a lot!
