### ISSUE TITLE
Installation docs for 3.x mix up pip and pipx

### ISSUE THREAD

**Issue by paidhi** [Fizzadar/pyinfra#1126]
## Describe the bug
The installation section for v3.x have a heading "Pipx" but the text says "It is recommended to install pyinfra using pip" and also have the command `pip install pyinfra`.
I think that was meant to say `pipx`. At least that's what the docs for v2.x say.

## To Reproduce
Compare https://docs.pyinfra.com/en/3.x/install.html with https://docs.pyinfra.com/en/2.x/install.html.

## Beta release
Because 3.x is currently a "pre-release" on PyPI the above command would still install v2.x.
To install the beta via pipx: `pipx install --pip-args='--pre' pyinfra`.

**Comment by Fizzadar** [comment]
Fixed in https://github.com/pyinfra-dev/pyinfra/commit/5c6b8629501cdee8dbe813006ebbef2a756d5104. We switched back to pip from pipx because it means type hints work properly in editors.
