### ISSUE TITLE
Docs for 3.x are missing Python API usage example

### ISSUE THREAD

**Issue by paidhi** [Fizzadar/pyinfra#1133]
Document "Using the API" for 3.x mentions "An example of how to use the API is embedded below." but does not have it.
To see the expected content one can compare https://docs.pyinfra.com/en/3.x/api/index.html with https://docs.pyinfra.com/en/2.x/api/index.html .

**Comment by Fizzadar** [comment]
Done a quick fix in https://github.com/pyinfra-dev/pyinfra/commit/5c6b8629501cdee8dbe813006ebbef2a756d5104. Added https://github.com/pyinfra-dev/pyinfra-examples/issues/4 to track adding a more up to date example.
