### ISSUE TITLE
Would be useful with a `ssh.keyscan` user argument

### ISSUE THREAD

**Issue by martingms** [Fizzadar/pyinfra#1139]
## Is your feature request related to a problem? Please describe
The `ssh.keyscan` operation checks and adds hosts to a `.ssh/known_hosts` file.

The implementation uses the `Home` fact to figure out which file to edit, which ends up being either the user you connected with, or root if sudo is set through one of the many ways to do so, with no option as far as I can tell to set it for another user.
I use the ssh key to rsync with a specific backup user, which is neither the user I connect as nor root.

## Describe the solution you'd like
I'd like it if the `ssh.keyscan` operation took a `user`-argument (or something similar), so I can run keyscan for an arbitrary user on the system.

**Comment by Fizzadar** [comment]
Hi @martingms! What about using the `_sudo_user` argument to do this?

**Comment by martingms** [comment]
Ah, I somehow missed that global arg! Thank you for the pointer :+1:
