### ISSUE TITLE
Pyinfra docs have examples with the wrong key name for ssh connector

### ISSUE THREAD

**Issue by format997** [Fizzadar/pyinfra#1142]
## Describe the bug
The examples at the top of the page for the @ssh connector documentation list the key name "ssh_username", but the documentation below that list "ssh_user" as the paramater to set to change the SSH user name. It would seem that "ssh_user" is the correct key name, per testing on my own setup. 

## To Reproduce
Visit documentation page for SSH connector, mismatch between examples and list of various key names that can be concfigured. 

## Expected behavior
Examples should list "ssh_name" instead of "ssh_username"

**Comment by Fizzadar** [comment]
Nice catch @format997, updated to the correct `ssh_user` in https://github.com/pyinfra-dev/pyinfra/commit/00cefb06f458c6068c6e8ee43de0cda0c0c1cb4e.
