### ISSUE TITLE
any_changed and all_changed are broken

### ISSUE THREAD

**Issue by TobyGiacometti** [Fizzadar/pyinfra#1152]
## Describe the bug

Since commit https://github.com/pyinfra-dev/pyinfra/commit/60f3d03da67e06574dda96aa2d7d92cc54546730, the helper functions `pyinfra.operations.util.any_changed` and `pyinfra.operations.util.all_changed` are broken.

## To Reproduce

```python
import pyinfra
import pyinfra.operations.python
import pyinfra.operations.util

op = pyinfra.operations.python.call(function=lambda: True)

with pyinfra.host.when(pyinfra.operations.util.any_changed(op)):
    ...
```

## Expected behavior

Code inside the `with` block should be executed.

## Meta

Check https://github.com/pyinfra-dev/pyinfra/issues/1124 for a possible fix.

**Comment by Fizzadar** [comment]
Fixed in https://github.com/pyinfra-dev/pyinfra/commit/31436958dad033dfc9678341f2bc0869fbde9bc8, added a test in https://github.com/pyinfra-dev/pyinfra/commit/d1921949dd84519a03ef3359eba75daa4b2cbfbf. 3.0.2 incoming.

**Comment by TobyGiacometti** [comment]
Thank you @Fizzadar!
