### ISSUE TITLE
Deploying to SSH aliases is no longer possible

### ISSUE THREAD

**Issue by filips123** [Fizzadar/pyinfra#1170]
## Describe the bug

In pyinfra 2.7, it was possible to run a deploy to a SSH alias defined in `~/.ssh/config` file, like this:

```sh
pyinfra server-alias deploy.py
```

In pyinfra 3.0.2, this is no longer possible, and fails with:

```
server-alias is neither an inventory file, a (list of) hosts or connectors nor refers to a python module
```

## To Reproduce

Add an alias to your `~/.ssh/config`:

```
Host server-alias
    HostName example.com
    User user
    Port 22
```

Try to deploy to that alias:

```sh
pyinfra server-alias deploy.py
```

## Expected behavior

pyinfra should detect that this is a host alias and use it to connect to the server.

## Meta

+ How was pyinfra installed (source/pip)? poetry

```
    System: Windows
      Platform: Windows-11-10.0.22631-SP0
      Release: 11
      Machine: AMD64
    pyinfra: v3.0.2
    Executable: E:\Projects\GimVicUrnik\venv\Scripts\pyinfra.exe
    Python: 3.12.4 (CPython, MSC v.1940 64 bit (AMD64))
```

**Comment by simonhammes** [comment]
Can you try `@ssh/server-alias`?

**Comment by filips123** [comment]
Yes, that works. Is it possible to add back support for aliases without `@ssh/` prefix, as it was supported in previous versions and is slightly shorter to type?

I guess that the problem is that pyinfra now [checks](https://github.com/pyinfra-dev/pyinfra/blob/aae76aa78cb2966d6a4ebf38b66da255dbe36e7c/pyinfra_cli/inventory.py#L84-L91) if the hostname resolves correctly, which SSH aliases don't. I didn't check how it was handled in previous versions and why the check is needed. Maybe it can be extended to support SSH aliases or just removed?

**Comment by simonhammes** [comment]
I'm very new to pyinfra, so I can't answer all of your questions :sweat_smile: 

You might be able to use something like [this](https://unix.stackexchange.com/a/297658) to check if the provided alias resolves (e.g. in case `socket.getaddrinfo()` raises).

**Comment by simonhammes** [comment]
> You might be able to use something like [this](https://unix.stackexchange.com/a/297658) to check if the provided alias resolves (e.g. in case `socket.getaddrinfo()` raises).

I'll give this a go.
