### ISSUE TITLE
server.crontab() not identifying cronjobs

### ISSUE THREAD

**Issue by kwilt** [Fizzadar/pyinfra#1189]
## Describe the bug
If this is not a bug I am horribly confused on how this is actually supposed to work. 🙃

If an unidentified cronjob exists in your crontab and you attempt to identify this cronjob with the `cron_name` argument, this does not add an identifier to the cronjob. You must then make another call to `server.crontab()` with the same `cron_name` if you want to make changes to the cronjob. This time however, instead of overwriting the existing cronjob that you just tried to identify, `server.crontab()` will create a new entry in your crontab - appending it to the end of the file - leaving you with the cronjob you initially tried to identify as well as the new cronjob with the identifier you tried to apply to the initial cronjob. 

## To Reproduce
Have a crontab with some cronjobs in it that aren't identified by PyInfra, then run `server.crontab()` against your crontab in an attempt to identify the cronjobs, and then modify them afterwards.

+ Operation code & usage
```
server.crontab(
    name="Identify Cron",
    command=f"/usr/bin/php{php_version} {old_estore_dir}/bin/magento cron:run 2>&1 \
| grep -v \"Ran jobs by schedule\" >> {old_estore_dir}/var/log/magento.cron.log",
    minute="*",
    hour="*",
    month="*",
    day_of_week="*",
    day_of_month="*",
    present=True,
    user=f"{username}",
    cron_name=f"{site}_cron",
    _sudo=True,
)

server.crontab(
    name="Modify Cron",
    command=f"/usr/bin/php{php_version} {estore_dir}/bin/magento cron:run 2>&1 \
| grep -v \"Ran jobs by schedule\" >> {estore_dir}/var/log/magento.cron.log",
    minute="*",
    hour="*",
    month="*",
    day_of_week="*",
    day_of_month="*",
    present=True,
    user=f"{username}",
    cron_name=f"{site}_cron",
    _sudo=True,
)
```

If I attempt to identify and modify either of the cronjobs, I get a brand new cronjob appended to the end of the file as shown, with the cron identifier. In this example I tried to edit the staging_cron

**Before**
```
* * * * * /usr/bin/php8.2 /opt/<name>/apps/prod/estore.e483eac1/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/prod/estore.e483eac1/var/log/magento.cron.log

* * * * * /usr/bin/php8.2 /opt/<name>/apps/staging/estore.1312e8dd/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.1312e8dd/var/log/magento.cron.log
```

**After**
```
* * * * * /usr/bin/php8.2 /opt/<name>/apps/prod/estore.e483eac1/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/prod/estore.e483eac1/var/log/magento.cron.log

* * * * * /usr/bin/php8.2 /opt/<name>/apps/staging/estore.1312e8dd/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.1312e8dd/var/log/magento.cron.log

# pyinfra-name=staging_cron
* * * * * /usr/bin/php8.2 /opt/<name>/apps/staging/estore.656bc6af/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.656bc6af/var/log/magento.cron.log
```

## Expected behavior
The cronjob should be identified with the first call to `server.crontab()`, prepending the `cron_name` identifier/comment on the line above the cronjob. Then, the second call to `server.crontab()` should overwrite this cronjob with the new contents if the same `cron_name` is used, not appending a new cronjob to the end of the file, and not leaving the initial cronjob behind.

## Meta
```
System: Linux
      Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
      Release: 5.15.153.1-microsoft-standard-WSL2
      Machine: x86_64
    pyinfra: v3.1
      click: v8.1.7
      configparser: v7.1.0
      distro: v1.9.0
      gevent: v24.2.1
      jinja2: v3.1.4
      packaging: v24.1
      paramiko: v3.4.1
      python-dateutil: v2.9.0.post0
      pywinrm: v0.5.0
      setuptools: v73.0.1
      typeguard: v4.3.0
      typing-extensions: v4.12.2
      wheel: v0.44.0
    Executable: /home/<name>/<project>/env/bin/pyinfra
    Python: 3.10.12 (CPython, GCC 11.4.0)
  ```
+ How was pyinfra installed? **Pip**

+ Debug info:
```
--> Starting operation: Identify Cron
    [pyinfra.api.operations] Starting operation {'Identify Cron'} on @local
    [pyinfra.api.facts] Getting fact: server.Crontab (user=<name>) (ensure_hosts: None)

[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c '! command -v crontab >/dev/null || crontab -l -u <name> || true'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
    [pyinfra.api.facts] [@local] Loaded fact server.Crontab (user=<name>)
    [pyinfra.api.host] [@local] noop: crontab /usr/bin/php8.2 /opt/<name>/apps/staging/estore.1312e8dd/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.1312e8dd/var/log/magento.cron.log exists
    [@local] No changes

--> Starting operation: Modify Cron
    [pyinfra.api.operations] Starting operation {'Modify Cron'} on @local
    [pyinfra.api.facts] Getting fact: server.Crontab (user=<name>) (ensure_hosts: None)

[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c '! command -v crontab >/dev/null || crontab -l -u <name> || true'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
    [pyinfra.api.facts] [@local] Loaded fact server.Crontab (user=<name>)

[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'crontab -l -u <name>> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'echo '"'"''"'"' >> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'echo '"'"'# pyinfra-name=staging_cron'"'"' >> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'echo '"'"'* * * * * /usr/bin/php8.2 /opt/<name>/apps/staging/estore.656bc6af/bin/magento cron:run 2>&1 | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/staging/estore.656bc6af/var/log/magento.cron.log'"'"' >> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
[pyinfra.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'crontab -u <name> /tmp/pyinfra-99800753387583ff6590a828b5571df23d46c9b6'
[pyinfra.connectors.util] --> Waiting for exit status...
[pyinfra.connectors.util] --> Command exit status: 0
    [@local] Success
```

**Comment by JakkuSakura** [comment]
This might be relevant to me soon.
If it's an unidentified cronjob, how is it supposed to be identified when you give it a name?

I suppose if you can identify it with other means, either by line number or command content(with a flag or something) or whatsoever, it's supposed to add a name to the existing item.

Sounds like a feature request rather than a bug

**Comment by kwilt** [comment]
Yeah I might be misunderstanding what this operation capable of. I was under the impression that you were able to identify existing, unidentified cronjobs, but that doesn't seem to be the case - in which case I suppose this would be a feature request. 

I've been verifying existing cronjobs using a small regex function I created. Basically it runs a regex pattern against `host.get_fact(Crontab)` for my specific command and returns the match if it exists. I can then pass that match in to my `server.crontab(command)` argument as a variable.

My thought process on how to identify an unidentified cronjob was to theoretically do something like the function I just described above, then if the `cron_name` argument was passed in and didn't already exist on that cronjob, it would prepend it to the cronjob, like it already does with a newly created one. Theoretically, it could delete the cronjob and replace it with the new, identified cronjob as long as it replaced in-line, not appending it to the end of the file which is the current behavior if you delete the unidentified cronjob (`present=False`) and replace it with the new identified one.

For the time being, I'm able to use [python-crontab](https://pypi.org/project/python-crontab/) to accomplish what I'm trying to do here along with the regex function slightly modified from I described earlier.

```python
def extract_active_cronjob(crontab, regex_pattern):
    regex = re.compile(regex_pattern)
    matches = []

    for cronjob in crontab:
        if isinstance(cronjob.command, str):  # Ensure command is a string
            match = regex.search(cronjob.command)
            if match:
                matches.append(match.group(0))
    return matches


# Initialize the user's crontab
user_crontab = CronTab(user=username)

# {site} is either "staging" or "prod"
pattern = rf'/opt/<name>/apps/{site}/estore\.[a-zA-Z0-9]+'

active_instance = extract_active_cronjob(user_crontab, pattern)

# If there is no active instance, create a new cronjob
if not active_instance:
    user_cronjob = user_crontab.new(
        command=f"/usr/bin/php{php_version} {estore_dir}/bin/magento cron:run 2>&1 | grep -v \"Ran jobs by schedule\" >> {estore_dir}/var/log/magento.cron.log"
    )
    user_cronjob.minute.every(1)
    user_crontab.write()
else:
    # Update the existing cronjob
    old_estore_dir = active_instance[0]
    for user_cronjob in user_crontab:
        if user_cronjob.command == f"/usr/bin/php{php_version} {old_estore_dir}/bin/magento cron:run 2>&1 | grep -v \"Ran jobs by schedule\" >> {old_estore_dir}/var/log/magento.cron.log":
            user_cronjob.set_command(
                f"/usr/bin/php{php_version} {estore_dir}/bin/magento cron:run 2>&1 | grep -v \"Ran jobs by schedule\" >> {estore_dir}/var/log/magento.cron.log"
            )

    user_crontab.write()

```

**Comment by JakkuSakura** [comment]
thanks for pointing out python-crontab. combined with other issues, I'm motivated to use python-crontab to replace current implementation, and solve issues once-for-all

**Comment by JakkuSakura** [comment]
> Yeah I might be misunderstanding what this operation capable of. I was under the impression that you were able to identify existing, unidentified cronjobs, but that doesn't seem to be the case - in which case I suppose this would be a feature request.

I read the implementation, the crontab fact is able to locate by unique commands, but the crontab operation can't handle it. so this might also be a bug

**Comment by kwilt** [comment]
> thanks for pointing out python-crontab. combined with other issues, I'm motivated to use python-crontab to replace current implementation, and solve issues once-for-all

Yeah, no problem. So far it seems to work great and requires very little code to accomplish the task at hand. I ended up wrapping that chunk of code after `extract_active_cronjob()` into its own function and then used PyInfra's `python.call()` to call the function. Works like a charm! 🙂

Also, I was able to add comments to existing, unidentified cronjobs in the way that I wanted to initially, even though it's not necessary now. The final code looks like this:

```python
def extract_active_cronjob(crontab, regex_pattern):
    regex = re.compile(regex_pattern)
    matches = []

    for cronjob in crontab:
        if isinstance(cronjob.command, str):  # Ensure command is a string
            match = regex.search(cronjob.command)
            if match:
                matches.append((match.group(0), cronjob))
    return matches


def modify_crontab():
    # Initialize the user's crontab
    user_crontab = CronTab(user=username)

    pattern = rf'/usr/bin/php[0-9.]+ /opt/<name>/apps/{site}/estore\.[a-zA-Z0-9]+/bin/magento cron:run 2>&1\
     | grep -v "Ran jobs by schedule" >> /opt/<name>/apps/{site}/estore\.[a-zA-Z0-9]+/var/log/magento.cron.log'

    active_instance = extract_active_cronjob(user_crontab, pattern)

    # If there is no active instance, create a new cronjob
    cronjob_modified = False

    if not active_instance:
        user_cronjob = user_crontab.new(
            comment=f"{site.upper()}",
            pre_comment=True,
            command=f"/usr/bin/php{php_version} {estore_dir}/bin/magento cron:run 2>&1"
                    f" | grep -v \"Ran jobs by schedule\" >> {estore_dir}/var/log/magento.cron.log"
        )
        user_cronjob.minute.every(1)
        user_crontab.write()
        cronjob_modified = True
    else:
        # Update the existing cronjob
        old_estore_dir, cronjob = active_instance[0]
        for user_cronjob in user_crontab:
            if user_cronjob == cronjob:
                user_cronjob.set_command(
                    f"/usr/bin/php{php_version} {estore_dir}/bin/magento cron:run 2>&1"
                    f" | grep -v \"Ran jobs by schedule\" >> {estore_dir}/var/log/magento.cron.log"
                )
                if user_cronjob.comment != f"{site.upper()}":
                    user_cronjob.set_comment(f"{site.upper()}", pre_comment=True)
                break

        user_crontab.write()
        cronjob_modified = True

    if not cronjob_modified:
        raise Exception("Failed to create or update the cronjob.")


python.call(
    name="Modify crontab",
    function=modify_crontab,
)

```

**Comment by JakkuSakura** [comment]
I'm not 100% sure what's the cause, but the sed-based line editing seems suspicious to me
sed can't add comments(name) to the existing command
I'd prefer editing everything on controller side and send over. 

The whole handling logic is not robust either. I will rewrite this part

**Comment by JakkuSakura** [comment]
Hi @kwilt. I didn't spot this issue in my PR. Can you check if my PR has fixed your issue?

**Comment by kwilt** [comment]
@JakkuSakura I've been pretty busy lately but I will (eventually) get around to testing the updated crontab operation. I appreciate the work!
