### ISSUE TITLE
Server fact Which is not... which

### ISSUE THREAD

**Issue by Firesphere** [Fizzadar/pyinfra#1249]
## Is your feature request related to a problem? Please describe

The PyInfra `Which` module attempts to see if a command exists by checking the output of `command -v`.
This causes some oddities, e.g. snap will respond with an error "unknown flag -v".

## Describe the solution you'd like

A more robust solution would be to have the `Which` module use the actual `which` command, which will output the location of the binary.
E.g. `which snap` returns either an error (doesn't exist), or the path to the executable.
Furthermore, I have some bash scripts in `/usr/local/bin/`, that do not have a -v flag at all, but do show a response when running `which snapcleaner` (/usr/local/bin/snapcleaner), indicating that this command indeed does exist.
Running `snapcleaner -v` returns nothing

As a replacement for the current `Which`, I would suggest to rename it to a `Version` module, that will output (to the actual terminal that's running PyInfra) the output of `command -v`.

In a perfect world, all commands have `-v`, sadly, it's often a mix of `--version`, `-V`, `-v` or `--Version`.
 To counteract this, it might be possible/an option to have the suggested Version module first do a `Which` to see if the command exists, and then try each option of flags, until a suitable response is given or no further options are available to check the version.

**Comment by maisim** [comment]
the -v is applied to the internal shell command "command" not to the command you are looking for. It should work in bash or sh, ...  also in busybox.

You can have a look to man bash, man sh, 

What shell are you using ? We can look for a fallback command if your shell does not have the "command" command :)

**Comment by maisim** [comment]
But, it should be nice to have an output because where is really the problem ? the command was not found or the shell command command miss ?

Can you please past an example of your output ?

**Comment by Firesphere** [comment]
It seems I'm mistaken, it is indeed as you say, I may have been mixing two things up.
