### ISSUE TITLE
Local file IO is still broken

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#130]
See: https://github.com/Fizzadar/pyinfra/commit/2ed18628391d3e4ff25d2b8ed0b061d27f08e584

**Comment by gdoumenc** [comment]
If you need a beta tester : present :) As we need this issue fixed. Tx

**Comment by Fizzadar** [comment]
@gdoumenc I've just pushed a (hopeful) fix for this (https://github.com/Fizzadar/pyinfra/commit/a2ede505e920d8ca43950290d8ef2602e99533c6) which happens because the jinja2 output in Python 3 is unicode data.

**Comment by Fizzadar** [comment]
Should be working, will cut `v0.5.3` soon!

**Comment by gdoumenc** [comment]
Working on all cases for me : Happy new year @Fizzadar :) !

**Comment by Fizzadar** [comment]
@gdoumenc thanks for confirming! Happy New Year to you :)!

**Comment by gdoumenc** [comment]
I found another issue on put.. If the target directory has not the rights for writing, even if sudo is defined, the command fails.
-- For your information, you can wonder why I use pyinfra with localhost ... In fact I think it is the perfect complementary tool for packer, I use a pyinfra script to deploy and I can deploy manually on a remote host or locally using packer... 
Regards

**Comment by Fizzadar** [comment]
@gdoumenc good catch, it's because we do the IO in Pythonland but that doesn't work with sudo! I'll investigate doing it using `cp` instead :)

**Comment by Fizzadar** [comment]
This should now be fixed as of https://github.com/Fizzadar/pyinfra/commit/803e8a9fe74905bdd0d19c294066c2f8ade57f97 :)
