### ISSUE TITLE
Template doesn't work

### ISSUE THREAD

**Issue by gdoumenc** [Fizzadar/pyinfra#132]
Hi,
With the new version `files.template` does'n work now on localhost... Empty file is rendered..
Regards

**Comment by Fizzadar** [comment]
@gdoumenc I just tested and it's working for me - could you paste a log of the command/output you're running? Thanks :)

**Comment by gdoumenc** [comment]
Sorry for this too quick description.. But this issue make us a lot af troubles... ;)

Here is the code : 

```
files.template(
    {"Move application code"},
    "files/uwsgi/application.py", "/usr/src/app/application.py",
    user="www-data", group="ubuntu", mode=664,
    sudo=True
)
```

And here are the logs (I don't see the source file somewhere...)  : 

```
ubuntu@ip-172-31-47-241:~$ pyinfra @local ./packer/deploy.py

### Welcome to pyinfra

--> Loading config...
--> Loading inventory...
--> Connecting to hosts...
    [@local] Connected
                    
--> Preparing operations...
    Pushing hash into operation order (host=@local, names={'Move application code'}): 62914d718cf5cadb9d50f55b99e27fa3b95c2348
DEBUG:pyinfra:Pushing hash into operation order (host=@local, names={'Move application code'}): 62914d718cf5cadb9d50f55b99e27fa3b95c2348
    Getting fact: file (ensure_hosts: (@local,))
DEBUG:pyinfra:Getting fact: file (ensure_hosts: (@local,))
    Building command (sudo: True): ls -ld --time-style=long-iso /usr/src/app/application.py || ls -ldT /usr/src/app/application.py
DEBUG:pyinfra:Building command (sudo: True): ls -ld --time-style=long-iso /usr/src/app/application.py || ls -ldT /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'ls -ld --time-style=long-iso /usr/src/app/application.py || ls -ldT /usr/src/app/application.py'
DEBUG:pyinfra:--> Running command on localhost: sudo -H sh -c 'ls -ld --time-style=long-iso /usr/src/app/application.py || ls -ldT /usr/src/app/application.py'
--> Waiting for exit status...
DEBUG:pyinfra:--> Waiting for exit status...
--> Command exit status: 0
DEBUG:pyinfra:--> Command exit status: 0
    Loaded fact file: ('/usr/src/app/application.py',)
DEBUG:pyinfra:Loaded fact file: ('/usr/src/app/application.py',)
    Failing hosts: 
DEBUG:pyinfra:Failing hosts: 
    Getting fact: sha1_file (ensure_hosts: (@local,))
DEBUG:pyinfra:Getting fact: sha1_file (ensure_hosts: (@local,))
    Building command (sudo: True): sha1sum /usr/src/app/application.py || sha1 /usr/src/app/application.py
DEBUG:pyinfra:Building command (sudo: True): sha1sum /usr/src/app/application.py || sha1 /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'sha1sum /usr/src/app/application.py || sha1 /usr/src/app/application.py'
DEBUG:pyinfra:--> Running command on localhost: sudo -H sh -c 'sha1sum /usr/src/app/application.py || sha1 /usr/src/app/application.py'
--> Waiting for exit status...
DEBUG:pyinfra:--> Waiting for exit status...
--> Command exit status: 0
DEBUG:pyinfra:--> Command exit status: 0
    Loaded fact sha1_file: ('/usr/src/app/application.py',)
DEBUG:pyinfra:Loaded fact sha1_file: ('/usr/src/app/application.py',)
    Failing hosts: 
DEBUG:pyinfra:Failing hosts: 
    [@local]  Ready: ./packer/deploy.py
INFO:pyinfra:[@local]  Ready: ./packer/deploy.py
                    
--> Proposed changes:
    Ungrouped:
INFO:pyinfra:Ungrouped:
    [@local]   Operations: 1   Commands: 3   
INFO:pyinfra:[@local]   Operations: 1   Commands: 3   

--> Beginning operation run...
--> Starting operation: Move application code 
INFO:pyinfra:--> Starting operation: Move application code 
    Starting operation Move application code on @local
DEBUG:pyinfra:Starting operation Move application code on @local
    Building command (sudo: True): cp /tmp/tmp41hjy50r /usr/src/app/application.py
DEBUG:pyinfra:Building command (sudo: True): cp /tmp/tmp41hjy50r /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'cp /tmp/tmp41hjy50r /usr/src/app/application.py'
DEBUG:pyinfra:--> Running command on localhost: sudo -H sh -c 'cp /tmp/tmp41hjy50r /usr/src/app/application.py'
--> Waiting for exit status...
DEBUG:pyinfra:--> Waiting for exit status...
--> Command exit status: 0
DEBUG:pyinfra:--> Command exit status: 0
    Building command (sudo: True): chown www-data:ubuntu /usr/src/app/application.py
DEBUG:pyinfra:Building command (sudo: True): chown www-data:ubuntu /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'chown www-data:ubuntu /usr/src/app/application.py'
DEBUG:pyinfra:--> Running command on localhost: sudo -H sh -c 'chown www-data:ubuntu /usr/src/app/application.py'
--> Waiting for exit status...
DEBUG:pyinfra:--> Waiting for exit status...
--> Command exit status: 0
DEBUG:pyinfra:--> Command exit status: 0
    Building command (sudo: True): chmod 664 /usr/src/app/application.py
DEBUG:pyinfra:Building command (sudo: True): chmod 664 /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'chmod 664 /usr/src/app/application.py'
DEBUG:pyinfra:--> Running command on localhost: sudo -H sh -c 'chmod 664 /usr/src/app/application.py'
--> Waiting for exit status...
DEBUG:pyinfra:--> Waiting for exit status...
--> Command exit status: 0
DEBUG:pyinfra:--> Command exit status: 0
    [@local] Success
INFO:pyinfra:[@local] Success
    Failing hosts: 
DEBUG:pyinfra:Failing hosts: 

--> Results:        
    Ungrouped:
INFO:pyinfra:Ungrouped:
    [@local]   Successful: 1   Errors: 0   Commands: 3/3   
INFO:pyinfra:[@local]   Successful: 1   Errors: 0   Commands: 3/3   

<-- Thank you, goodbye
```

**Comment by Fizzadar** [comment]
@gdoumenc no worries! I can see pyinfra doing the file copy and chown/etc in the logs:

```
Starting operation Move application code on @local
    Building command (sudo: True): cp /tmp/tmp41hjy50r /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'cp /tmp/tmp41hjy50r /usr/src/app/application.py'
...
    Building command (sudo: True): chown www-data:ubuntu /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'chown www-data:ubuntu /usr/src/app/application.py'
...
    Building command (sudo: True): chmod 664 /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'chmod 664 /usr/src/app/application.py'
...
    [@local] Success
```

What _should_ happen is the template is generated to the tempfile (`/tmp/tmp41hjy50r` in this case) and then copied and ownership/mode applied, which all looks OK.

I recreated the `files.template` call above in a fresh Ubuntu 16 VM with `pyinfra==0.6` and the template is copied and rendered correctly.

Could you run the `files.template` call only with `--dry --debug-state` and paste the output here? I can't figure out why this is happening!

**Comment by gdoumenc** [comment]
My point is that I don't see  the template generation... After it is ok but not the template generation..

`̀`̀`
ubuntu@ip-172-31-47-241:~$ pyinfra --dry --debug-state @local ./packer/deploy.py

### Welcome to pyinfra

--> Loading config...
--> Loading inventory...
--> Connecting to hosts...
    [@local] Connected
                    
--> Preparing operations...
    Pushing hash into operation order (host=@local, names={'Move application code'}): 62914d718cf5cadb9d50f55b99e27fa3b95c2348
DEBUG:pyinfra:Pushing hash into operation order (host=@local, names={'Move application code'}): 62914d718cf5cadb9d50f55b99e27fa3b95c2348
    Getting fact: file (ensure_hosts: (@local,))
DEBUG:pyinfra:Getting fact: file (ensure_hosts: (@local,))
    Building command (sudo: True): ls -ld --time-style=long-iso /usr/src/app/application.py || ls -ldT /usr/src/app/application.py
DEBUG:pyinfra:Building command (sudo: True): ls -ld --time-style=long-iso /usr/src/app/application.py || ls -ldT /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'ls -ld --time-style=long-iso /usr/src/app/application.py || ls -ldT /usr/src/app/application.py'
DEBUG:pyinfra:--> Running command on localhost: sudo -H sh -c 'ls -ld --time-style=long-iso /usr/src/app/application.py || ls -ldT /usr/src/app/application.py'
--> Waiting for exit status...
DEBUG:pyinfra:--> Waiting for exit status...
--> Command exit status: 0
DEBUG:pyinfra:--> Command exit status: 0
    Loaded fact file: ('/usr/src/app/application.py',)
DEBUG:pyinfra:Loaded fact file: ('/usr/src/app/application.py',)
    Failing hosts: 
DEBUG:pyinfra:Failing hosts: 
    Getting fact: sha1_file (ensure_hosts: (@local,))
DEBUG:pyinfra:Getting fact: sha1_file (ensure_hosts: (@local,))
    Building command (sudo: True): sha1sum /usr/src/app/application.py || sha1 /usr/src/app/application.py
DEBUG:pyinfra:Building command (sudo: True): sha1sum /usr/src/app/application.py || sha1 /usr/src/app/application.py
--> Running command on localhost: sudo -H sh -c 'sha1sum /usr/src/app/application.py || sha1 /usr/src/app/application.py'
DEBUG:pyinfra:--> Running command on localhost: sudo -H sh -c 'sha1sum /usr/src/app/application.py || sha1 /usr/src/app/application.py'
--> Waiting for exit status...
DEBUG:pyinfra:--> Waiting for exit status...
--> Command exit status: 0
DEBUG:pyinfra:--> Command exit status: 0
    Loaded fact sha1_file: ('/usr/src/app/application.py',)
DEBUG:pyinfra:Loaded fact sha1_file: ('/usr/src/app/application.py',)
    Failing hosts: 
DEBUG:pyinfra:Failing hosts: 
    [@local]  Ready: ./packer/deploy.py
INFO:pyinfra:[@local]  Ready: ./packer/deploy.py
                    
--> Proposed changes:
    Ungrouped:
INFO:pyinfra:Ungrouped:
    [@local]   Operations: 1   Commands: 3   
INFO:pyinfra:[@local]   Operations: 1   Commands: 3   

--> Gathered facts:
{
    "@local": {},
    "3a0e00964bfe04030b65330fe880686aa70cb7b3": {
        "@local": {
            "mode": 664,
            "user": "www-data",
            "group": "ubuntu",
            "size": "801",
            "mtime": "2018-02-16T19:29:00"
        }
    },
    "6645a0d09c735f9f631d99da46a0762eaa0df7fe": {
        "@local": "6455ebb4a3b53302300617d456210a2d5d5af565"
    }
}

--> Proposed operations:
{
    "@local": {
        "62914d718cf5cadb9d50f55b99e27fa3b95c2348": {
            "commands": [
                [
                    "File: ./packer/files/uwsgi/application.py",
                    "/usr/src/app/application.py"
                ],
                "chown www-data:ubuntu /usr/src/app/application.py",
                "chmod 664 /usr/src/app/application.py"
            ]
        }
    }
}

--> Operation meta:
{
    "62914d718cf5cadb9d50f55b99e27fa3b95c2348": {
        "names": [
            "Move application code"
        ],
        "args": [],
        "env": {},
        "hosts": null,
        "when": true,
        "sudo": true,
        "sudo_user": null,
        "su_user": null,
        "preserve_sudo_env": false,
        "ignore_errors": false,
        "timeout": null,
        "get_pty": false,
        "serial": false,
        "run_once": false,
        "parallel": null,
        "on_success": null,
        "on_error": null,
        "op": null
    }
}

--> Operation order:
[
    "62914d718cf5cadb9d50f55b99e27fa3b95c2348"
]

<-- Thank you, goodbye
`̀`̀`

**Comment by gdoumenc** [comment]
If you remove the follwing line it don't get the same trace... But no more working..
```
    #output_file.name = template_filename
```
```
--> Proposed operations:
{
    "@local": {
        "62914d718cf5cadb9d50f55b99e27fa3b95c2348": {
            "commands": [
                [
                    "In memory file: # WSGI Handler sample configuration file.\n#\n\nimport odoo\n\nodoo.multi_process = False  # In case of True odoo.evented should be set to True\n\n# Equivalent of --load command-line option\nodoo.conf.server_wide_modules = ['web']\nconf = odoo.tools.config\n\nconf['admin_passwd'] = 'dG56hmFR'\n\nconf['db_host'] = 'postgres.fpr-coworks.com'\nconf['db_port'] = False\nconf['db_user'] = 'kool'\nconf['db_password'] = '2wY7H9cUS8iEjza86Z62gmVUtj8qD75H'\n\nconf['dbfilter'] = 'odoo-briteheart'\n\nconf['data_dir'] = '/var/lib/odoo'\nconf['addons_path'] = '/var/lib/odoo/addons,/usr/src/odoo/addons,/usr/src/app/addons'\n\nconf['logfile'] = '/var/log/odoo/odoo.log'\nconf['log_handler'] = [':DEBUG']\nconf['log_level'] = 'debug'\n\napplication = odoo.service.wsgi_server.application\n\nodoo.service.server.load_server_wide_modules()\n",
                    "/usr/src/app/application.py"
                ],
                "chown www-data:ubuntu /usr/src/app/application.py",
                "chmod 664 /usr/src/app/application.py"
            ]
        }
    }
}

```

**Comment by Fizzadar** [comment]
@gdoumenc so the file is getting correctly generated into a `StringIO`; meaning the problem is happening somewhere at the [temporary write stage here](https://github.com/Fizzadar/pyinfra/blob/develop/pyinfra/api/connectors/local.py#L130-L139).

Would you mind trying creating a tempfile as above and writing to it in a Python process; just to check that works? I'm all out of ideas :/

**Comment by gdoumenc** [comment]
Found the issue : On python3.6 the StringIO position seems to be at end by default...
To fix the issue add the seek call
```
        with open(temp_filename, 'wb') as temp_f:
            filename_or_io.seek(0)
            data = filename_or_io.read()
```

**Comment by gdoumenc** [comment]
To my opinion, the seek should be called on IOString creation not when using it..

**Comment by Fizzadar** [comment]
@gdoumenc this should now be fixed @ https://github.com/Fizzadar/pyinfra/commit/48c46677c51d873b196d8101fca3a7385169a58e

I also agree that ideally the seek would be called on creation - however the `StringIO` object might get read (for debug output/etc) before the upload is initiated, so it's safer to call the seek just before use in `get_file_io`.

About to release this as `0.6.1` :)
