### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [Fizzadar/pyinfra#155]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by Fizzadar** [comment]
That sounds great, a logo for pyinfra would be awesome :)

**Comment by mansya** [comment]
I have designed the logo for this project. What do you think ? do you like it ? if yes let me know and if there are changes please let me know.
![pyinfra](https://user-images.githubusercontent.com/33461607/48304118-82d0e600-e546-11e8-95bb-035003a95f9f.png)

**Comment by Fizzadar** [comment]
@mansya I think it looks great! Thank you :)

I'd love to use just the icon if possible - do you have a PSD available?

**Comment by mansya** [comment]
hi sir, I have sent you [**pull requests**](https://github.com/Fizzadar/pyinfra/pull/156). and I have also uploaded all files to this [**drive**](https://drive.google.com/open?id=1hHI8fDvcrAvxY1_y-DtrBqStZV9hWcTT). please check.

**Comment by Fizzadar** [comment]
Thank you @mansya!
