### ISSUE TITLE
Pipelining

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#17]
Investigate bunching commands up together - would be esp. effective in fact gathering. Problem is facts are bound with sudo/sudo_user as well, so need to handle that (ie can't just join all the commands together and expect it to work as currently).

Also, this might be considered over-optimisation, and as such has low priority.

**Comment by Fizzadar** [comment]
With the latest changes in v2, in particular updating of facts during operation execution and the performance improvements, reduce the potential impact of pipelineing performance.

Still would be super helpful when doing a lot of file operations, but the implementation would be complex and I don't think pyinfra is considered bad for performance anyways :)

**Comment by link2xt** [comment]
This is actually slow when you have a 50ms RTT and need to gather 20 facts, this takes 1 second while it could take around 50ms with pipelining.

I workaround this issue by `rsync`-ing the repo with deploys to `/root/deploy` and running `pyinfra @local` from there, it is much faster this way.
