### ISSUE TITLE
Add @terraform connector

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#184]
Generate inventory from Terraform state file.

**Comment by blarghmatey** [comment]
It would be great to also support Pulumi. I'm currently evaluating an integration of PyInfra and Pulumi for my personal projects, and possibly for use at work.

**Comment by Fizzadar** [comment]
@blarghmatey Pulumi looks awesome! I've added https://github.com/Fizzadar/pyinfra/issues/460 to track that.

**Comment by Fizzadar** [comment]
This is now in alpha as of v2!
