### ISSUE TITLE
Support getting installed package info with `deb_package` fact

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#190]
How do you pass an argument on cli for getting a fact?

For instance:
`pyinfra --user root somehost -v fact deb_package`

Returns:
`TypeError: command() missing 1 required positional argument: 'name'`

So, where/how do I pass 'docker-ce' to that command line?

**Comment by Fizzadar** [comment]
@mkinney currently this is done in the same argument via colon; ie `pyinfra @local fact which:pyinfra` (multiple can be passed separated by commas).

**Comment by mkinney** [comment]
Hmm... not working as I would have expected:

```
$ pyinfra --user root 138.68.31.50 fact deb_packages | grep docker-ce
        "docker-ce": [
        "docker-ce-cli": [

$ pyinfra --user root 138.68.31.50 fact deb_package:docker-ce
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [138.68.31.50] Connected

--> Gathering facts...
    Loaded fact deb_package: ('docker-ce',)

--> Fact data for: deb_package
{
    "138.68.31.50": null
}
```

Am I missing something?

**Comment by Fizzadar** [comment]
@mkinney the `deb_package` fact is for `.deb` archives rather than info on a single installed package. That said I think it'd be great to extend it - would certainly be possible to accept either a filename or, without the `.deb`, a package name to query from `dpkg`.

**Comment by Fizzadar** [comment]
Command for this would need to be `dpkg -s docker-ce` - output matches `-I` output for a single archive. So will reimplement the fact to:

`dpkg -I <name> || dpkg -s <name>`

Which will then support archives + installed packages.

**Comment by mkinney** [comment]
Thanks for re-opening this issue.

I was trying to figure out a way to add a "when" type clause (only run this if...):

```
apt.key(
    {'Download the Docker apt key'},
    (
        'https://download.docker.com/linux/'
        '{{ host.fact.lsb_release.id|lower }}/gpg'
    ),
)
```

My typical Ansible work flow would be to figure out the fact, then put in the deploy script (playbook).

**Comment by Fizzadar** [comment]
👍 I think now the PR is merged this should be OK to close as the usage is properly documented!

**Comment by mkinney** [comment]
Thanks. Closing.
