### ISSUE TITLE
pylint and/or black or other python tooling for code quality?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#193]
Which do you prefer "pylint" or "black"?

```
$ pylint pyinfra/ | wc -l
    1926
```

```
$ black --check pyinfra/
<snip>
Oh no! 💥 💔 💥
73 files would be reformatted, 5 files would be left unchanged.
```
Not sure what caused it to die...

**Comment by mkinney** [comment]
Which ever you choose, I can help to get the code formatted.

**Comment by mkinney** [comment]
https://www.pylint.org/ and/or https://github.com/psf/black

**Comment by Fizzadar** [comment]
Currently pyinfra is [linted by `flake8`](https://github.com/Fizzadar/pyinfra/blob/master/.travis.yml#L16) as part of CI, which I'm pretty happy with - I see no major reason to change from this at this time as it keeps code consistent without dramatically changing it's style.

I'm not a fan of Black's double-quote enforcement (and refusal to enforce single quotes. Have never investigated pylint before which does look really intersting - I will have a look into pylint-ing pyinfra.

**Comment by mkinney** [comment]
Wow. I didn't know that flake8 had so many plugins... including black... lols.

see https://github.com/DmytroLitvinov/awesome-flake8-extensions

I'm thinking of implementing the spellcheck plugin.

**Comment by mkinney** [comment]
Going to close this issue. Can always re-open or create a new issue.
