### ISSUE TITLE
Support for dnf

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#195]
Fedora (thus Centos and RedHat) switched from yum to dnf. See https://en.wikipedia.org/wiki/DNF_(software) for more info.

How should pyinfra support dnf?

Did you want to copy (or move) all of the yum stuff to dnf?

Either way, the docs will need to reflect that yum and dnf are both supported.

**Comment by Fizzadar** [comment]
I think it'd be best to duplicate the yum module and start with that; this will allow for any DNF specific features to be handled nicely under the new module and provide a clean `dnf.packages`/etc API for users.
