### ISSUE TITLE
Add mech connector

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#197]
Add the ability to use mech as a connector. It is an alternative to the vagrant vmware_desktop provider. See https://github.com/mechboxes/mech

I've created a repo that will allow multiple VMs to be spun up using mech: https://github.com/mkinney/multiple-mech

What are your thoughts on adding mech to pyinfra as a connector?

**Comment by Fizzadar** [comment]
Now merged and will drop `v0.12` with this later today!

**Comment by Fizzadar** [comment]
FYI just released `v0.12`!
