### ISSUE TITLE
add ability to use winrm to execute commands on windows instances

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#201]
Add ability to interact with windows instances using winrm.

Perhaps create a new winrm connector.

See https://github.com/mkinney/pywinrm_example for using mech to spin up a windows instance that has winrm enabled as well as how to leverage pywinrm.

**Comment by Fizzadar** [comment]
This would be an amazing addition to pyinfra - I'm super keen on proper Windows support. I think this will need to be both a connector and a set of Windows-specific modules, as the commands will dramatically differ from *nix counterparts.

**Comment by mkinney** [comment]
Sorry it took so long to put together a prototype. I've been working on adding the docs/examples.

**Comment by mkinney** [comment]
@Fizzadar I don't really understand how to pass the shell variable around. I've hacked something together (see https://github.com/Fizzadar/pyinfra/pull/263/commits/d82df92f8af50fbb8dfcc7f7f4ce66057e87c295 ) that *seems* to work the way I want it to.

This means that I broke quite a few tests. (8 or so). I've commented them out because I don't really know how to fix the code/tests. I am able to continue working on the winrm stuff, but I'll need your help.

**Comment by mkinney** [comment]
Going to spend a lot of time here: https://docs.microsoft.com/en-us/powershell/scripting/overview?view=powershell-7

**Comment by mkinney** [comment]
Looks like no simple/easy put/get file that I could find. See https://github.com/diyan/pywinrm/issues/18 , https://github.com/StackStorm-Exchange/stackstorm-windows/issues/7 , and https://github.com/ansible/ansible-modules-core/blob/devel/windows/win_copy.ps1

**Comment by mkinney** [comment]
https://github.com/jborean93/pypsrp looks really interesting 

It might be a better winrm library.  It has a fetch and copy already. Looks like they have cert example/code/config.

**Comment by mkinney** [comment]
FYI, I figured out how to download python, silently install python, and verify python is installed. Check it out here: https://github.com/mkinney/pywinrm_example/blob/master/download_and_install_python.py

**Comment by mkinney** [comment]
Added a script to install pyinfra https://github.com/mkinney/pywinrm_example/blob/master/install_pyinfra.py

**Comment by mkinney** [comment]
Yay! Looks like `StefanScherer/windows_10` vagrant box has winrm working again.

**Comment by mkinney** [comment]
Look how complicated the script is to see if a windows instance needs to be rebooted:  https://adamtheautomator.com/pending-reboot-registry-windows/ or code can be found here https://github.com/adbertram/Random-PowerShell-Work/blob/master/Random%20Stuff/Test-PendingReboot.ps1 

I guess we need a way to run something like that .ps1. Perhaps something like `server.script_template`. We should also have a directory of ps1 scripts. Perhaps in facts and in modules. Not sure.
