### ISSUE TITLE
support installed packages in `rpm_package` fact

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#207]
When I run "rpm_packages", I see the value:

```
$ pyinfra 192.168.2.219 --user vagrant --password vagrant fact rpm_packages | grep -A2 epel
        "epel-release-8": [
            "8.el8"
        ],

```

When I specify the package, it returns "null":

```
$ pyinfra 192.168.2.219 --user vagrant --password vagrant fact rpm_package:epel-release-8
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [192.168.2.219] Connected

--> Gathering facts...
    Loaded fact rpm_package: ('epel-release-8',)

--> Fact data for: rpm_package
{
    "192.168.2.219": null
}
```

**Comment by Fizzadar** [comment]
Ah this is similar to the `deb_package` fact in that it currently only supports actual `.rpm` files; modifying this to support installed packages should be a similar fix; just need to find the right `rpm` command.

**Comment by Fizzadar** [comment]
This is now fixed by https://github.com/Fizzadar/pyinfra/commit/58f9a5cbaf710693ed83c48dc4084835613c529d.
