### ISSUE TITLE
fix installing already installed rpms in `yum.rpm` and `dnf.rpm`

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#208]
How do check if a package is installed?

For instance, on Centos8, if you have this snippet:

```
        dnf.rpm(
            {'Enable EPEL'},
            'https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{  host.fact.linux_distribution.major }}.noarch.rpm',
        )
```

It will work the first time just fine, but a 2nd time it errors:

```
--> Starting operation: Enable EPEL
    [192.168.2.219] package epel-release-8-8.el8.noarch (which is newer than epel-release-8-7.el8.noarch) is already installed
    [192.168.2.219] Error
```

I can add the `ignore_errors=True` option, but that feels... wrong.

**Comment by Fizzadar** [comment]
Hmm this should work - we check for the package being installed already (in `rpm_packages` fact) - but the versions are different here; so I think it's trying to install the old version over the newer `8-8` version, and rejecting it.

What's the output if you run with `-v`? It _should_ be simply running `rpm -U <filename>.rpm`, which is correct - but I believe `rpm` will reject it as there's a newer version already.

**Comment by mkinney** [comment]
```
--> Beginning operation run...
--> Starting operation: Install EPEL rpm to enable EPEL repo
[192.168.2.219] >>> sudo -H sh -c 'rpm -U /tmp/b7f95f3f0daf418959443bae7b416941df7e134d.rpm'
[192.168.2.219] package epel-release-8-8.el8.noarch (which is newer than epel-release-8-7.el8.noarch) is already installed
    [192.168.2.219] Error (ignored)
```

**Comment by Fizzadar** [comment]
Hmm yeah this is as expected really - the RPM it's trying to install is older than the one already installed on the system. Not sure what the best course of action here is; I see a few options:

1. If the package exists, no matter the version, don't do the install (and add a `force=False` keyword to force install of the older version)
2. Compare the installed version to the one to-be-installed, which might not always work as expected (poorly versioned packages/etc)
3. Keep as-is, which will fail if the system has a newer version but this seems silly

I'm leaning towards the first option, what do you think @mkinney?

**Comment by mkinney** [comment]
#1 would require code... that I'm not really sure is necessary at this time.

I think option #4 is to add `ignore_errors=True,`. (lol)

But, what would the python code to see if a 'epel-release*' package is installed?

**Comment by Fizzadar** [comment]
Currently you could look for `epel-release` in the `rpm_packages` fact (it should have `epel-release` as the key and a list containing the installed version).

**Comment by mkinney** [comment]
I was trying to figure out something like this:

```
from pyinfra import host
from pyinfra.modules import dnf

SUDO = True

packages = host.fact.rpm_packages
if packages.get('vim-enhanced', ''):
    print("installed")
else:
    print("not installed")
```

Is there a better way than that?

So, for the epel thing...

```
    packages = host.fact.rpm_packages
    epel_installed = False
    for p in packages.keys():
        if p.startswith('epel-release'):
            epel_installed = True

    if not epel_installed:
        dnf.rpm(
            {'Install EPEL rpm to enable EPEL repo'},
            'https://dl.fedoraproject.org/pub/epel/epel-release-latest-'
            '{{  host.fact.linux_distribution.major }}.noarch.rpm',
        )
```

Thoughts?

**Comment by Fizzadar** [comment]
I just commented on the PR :) I think this should be something the operation handles (ie option #1!). I've flagged this as a bug for me to fix!

**Comment by Fizzadar** [comment]
This should now be fixed by https://github.com/Fizzadar/pyinfra/commit/dd6ddcf7c34a8a47449e39a2c059102970fc96b7 (option 1).
