### ISSUE TITLE
add doc/info for developing pyinfra

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#216]
I think there should be a section/docs on how to develop pyinfra.

Things like:
- how to enable git commit hook (ex: https://flake8.pycqa.org/en/latest/user/using-hooks.html)
- how to gen doc locally
- how to run the tests (right now it is just pytest, but I'm thinking of some sort of integration-y tests)

**Comment by mkinney** [comment]
And:
- how to create a virtualenv then need to run:
`pip install -e .[dev]`

**Comment by Fizzadar** [comment]
This should be covered in the contributing file (https://github.com/Fizzadar/pyinfra/blob/master/CONTRIBUTING.md).
