### ISSUE TITLE
Merge the examples

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#224]
Not super keen on multiple example directories. Also the vagrantfile could just live in the top directory and the non standalone examples removed.

Move everything under `examples/` and simplify. Current example dir is just confusing.

**Comment by mkinney** [comment]
Makes sense.

Would you consider renaming example to examples?

There is a standalone reference to remove in docs/getting_started.rst

**Comment by mkinney** [comment]
I guess I need to have some caffiene... sorry. I see that you are moving it to examples. Great!

**Comment by mkinney** [comment]
I see you got that that changed, too.

![thumbs_up](https://user-images.githubusercontent.com/2219838/72224511-3b6e2d00-3530-11ea-8221-19cc7cd4ecf0.jpeg)
