### ISSUE TITLE
Is there a way to get std_out from server.script() and/or server.shell()?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#234]
Is there a way to get return code, stdout, and stderr from server.script() and/or server.shell()?

I think host.run_shell_command() only runs at the beginning of the deployment. Is that correct?

Please confirm the sequence of events: 
- collect files on command line (error if file is not found or there is a syntax error) and gather inventory
- gather facts using connectors; host.run_shell_command() runs here?
- run thru deploys; server.script() and server.shell() run in sequence from the other steps, right?

I'm trying to run some commands (like download an iso), then run some md5sum on the file, and stop the deploy if the check fails.

Here is a work-in-progress:

```
from pyinfra.modules import apt, files

SUDO = True

if host.fact.linux_name == 'Ubuntu':

    apt.packages(
        {'Install wget'},
        ['wget'],
        update=True,
    )

# Full URL:
# http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/alpine-netboot-3.11.2-x86_64.tar.gz
# sha256 is here
# http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/alpine-netboot-3.11.2-x86_64.tar.gz.sha256
tarfile = 'alpine-netboot-3.11.2-x86_64.tar.gz'
tarfile_full_path = '/tmp/{}'.format(tarfile)
sha256file = tarfile + '.sha256'
sha256file_full_path = '/tmp/{}'.format(sha256file)

# TODO: How to know if download was successful?
files.download(
    {'Download `{}`'.format(tarfile)},
    'http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/{}'.format(tarfile),
    tarfile_full_path,
)

files.download(
    {'Download `{}`'.format(sha256file)},
    'http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/{}'.format(sha256file),
    sha256file_full_path,
)

# TODO: how to sha256sum the file and fail if they do not match?
```

**Comment by mkinney** [comment]
Does 'sudo' follow? (assuming it does)

**Comment by Fizzadar** [comment]
The `host.run_shell_command` method should only be used within callback functions (ie using the [`python.call` operation](https://pyinfra.readthedocs.io/en/latest/modules/python.html#python-call)) - if called at the top level of a deploy file, it will execute at fact gather stage. Essentially what happens:

+ Load up the files from command line/error as needed
+ Execute each deploy file for each host - so this calls the operation functions `server.script()` and so on. These collect any facts they need at this time and output commands _to_ be executed, but don't execute them
+ Once all the commands are ready, they are executed in order

So the only way to execute code _during_ the deploy and retrieve the output/exit code is a callback, ie as per https://pyinfra.readthedocs.io/en/latest/examples/dynamic_execution_deploy.html.

Specific to this use-case - I've added https://github.com/Fizzadar/pyinfra/issues/238 to add hash checks to the `files.download` operation.

**Comment by Fizzadar** [comment]
Gonna close this now as there's #238 tracking the hash addition to `files.download`.
