### ISSUE TITLE
Add sha1sum/md5sum kwargs to `files.download`

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#238]

**Comment by mkinney** [comment]
Can you also make the function check if dest is a dir to then save to that dir. (do you don’t have to specify file name on both source and dest)

**Comment by Fizzadar** [comment]
Excellent idea, will do!

**Comment by Fizzadar** [comment]
The checksum arguments are now added in https://github.com/Fizzadar/pyinfra/commit/15eba1860ddd9c0052eb96decab60b8af15ad8eb. Note you have to provide the hash itself, not a URL to the hash.

**Comment by mkinney** [comment]
Code looks great.

But I'm having a hard time seeing how it would be used.

For now, you have to download the page, look for data to determine which file has sha/gpg info, download the sum info, look for the sha, then use that sha value as an input to this operation. I'm not sure how to do that as part of a single deploy. Could you help with the pattern?

See https://github.com/Fizzadar/pyinfra/blob/master/examples/vagrant/vagrant.py for a use case.

**Comment by Fizzadar** [comment]
So my thinking was the user should put the hash into the deploy code (ie, not download the checksum file in the deploy, but as part of creating the deploy). This ensures that the hash can never be changed outside of the deploy itself.

Alternatively, if providing an URL is desired, I could add a `sha1sum_url` argument that downloads the file (using `files.download` itself!) and then uses it for the checksum.

My thinking is that hard-coding the hash into the deploy is safer as it doesn't rely on the hosted version (which can always be changed). But happy to implement `_url` equivilent arguments too, what do you think?

**Comment by mkinney** [comment]
I guess I think of the sha as is the file exactly as expected. The GPG should definitely be hard coded (known before deployment).

It would be easier if there was a url for sha, but I’m ok if that does not get added. This use case exercises something that I don’t know how to implement using pyinfra. So, I’m more interested in how it could be implemented. Does that make sense?

**Comment by Fizzadar** [comment]
I'm not 100%; my understanding is:

+ Download/curl a file
+ grep out another URL form it
+ Download the grepped URL, and possibly a checksum file

Unfortunately due to the "two step" deploy I don't think this is possible. One option could be to do the grep/find filename in the group data; ie:

```py
# group_data/all.py

def get_vagrant_package_url_sha():
    # download vagrant downloads page
    # parse out URL + SHA1 for Linux package
    return url, sha1_hash
 
virtualbox_package_url, virtualbox_package_sha1 = get_vagrant_package_url_sha()
```

That way it's possible to just call `files.download` within the deploy as normal:

```py
files.download(
    {'Download Virtualbox'},
    host.data.virtualbox_package_url,
    sha1sum=host.data.virtualbox_package_sha1,
)
```

Unfortunately dynamic execution like this is really hard to achieve in pyinfra, and I can't think of any clean solution :/

**Comment by mkinney** [comment]
Ok. That's my understanding as well.

**Comment by mkinney** [comment]
I'm kind of cheating with the bash template:

```
(venv) mikekinney@sweet mkinney_pyinfra % cat examples/vagrant/templates/download_vagrant.bash.j2
#!/usr/bin/env bash
url=`grep -o 'https://.*_linux_amd64.zip' /tmp/downloads.html`
filename=`grep -o 'vagrant_.*linux_amd64.zip' /tmp/downloads.html`
cd /tmp
# only download if we need to
if [ ! -f $filename ];
then
  wget $url
fi
cd /usr/local/bin
unzip /tmp/${filename}
rm /tmp/${filename} /tmp/downloads.html
chmod 755 /usr/local/bin/vagrant
```

I suppose you could get output from `server.command()`. Maybe?

**Comment by Fizzadar** [comment]
That'll have the same issue :/ The command won't actually be executed until after all the operations have been prepared, so it's impossible to pass output of one operation into another.

The only clean solution I see here is fetch the file URL/etc from the virtualbox website in the group data or inventory, before the deploy itself.

**Comment by Fizzadar** [comment]
Gonna close this now as the above workaround is the only solution here.
