### ISSUE TITLE
run fact gathering in parallel?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#239]
It is not that big of a deal, but it is very obvious that the facts are gathered serially when you run `all-facts`. Can the fact gathering happen in parallel?

Does the fact gathering happen in parallel during deploys?

Might speed up deploys... maybe?

```
$ time pyinfra @docker/alpine all-facts
--> Loading config...
--> Loading inventory...
    The @docker connector is in Alpha!

--> Connecting to hosts...

--> Gathering facts...
    Loaded fact pacman_packages
    Loaded fact home
    Loaded fact hostname
    Loaded fact os
    Loaded fact os_version
    Loaded fact arch
    Loaded fact date
    Loaded fact mounts
    Loaded fact kernel_modules
    Loaded fact lsb_release
    Loaded fact sysctl
    Loaded fact groups
    Loaded fact users
^C
```

Took:
```
real	0m7.346s
user	0m1.407s
sys	0m0.725s
```

**Comment by mkinney** [comment]
Another minor thing is that the output has the screen escape sequences to look pretty, but when you run `all-facts` to a file, it looks pretty bad.

Is there an option to not show the escapes?

For example:

```
$ pyinfra @docker/alpine all-facts > /tmp/output
    The @docker connector is in Alpha!
```

```
$ cat -tve /tmp/output | head
--> Loading config...$
--> Loading inventory...$
$
--> Connecting to hosts...$
    \ {alpine}^M^[[K    | {docker run}^M^[[K    / {alpine}^M^[[K    - {docker run}^M^[[K    \ {alpine}^M^[[K    | {docker run}^M^[[K    / {alpine}^M^[[K    - {docker run}^M^[[K    \ {alpine}^M^[[K    | {docker run}^M^[[K    / {alpine}^M^[[K    - {docker run}^M^[[K    \ {alpine}^M^[[K    | {docker run}^M^[[K    / {alpine}^M^[[K    - {docker run}^M^[[K    \ {alpine}^M^[[K    | {docker run}^M^[[K    / {alpine}^M^[[K    - {docker run}^M^[[K    \ {alpine}^M^[[K    | {docker run}^M^[[K    / {alpine}^M^[[K    - {docker run}^M^[[K    \ {alpine}^M^[[K    | {docker run}^M^[[K    / {alpine}^M^[[K$
--> Gathering facts...$
    - fact: pacman_packages - {alpine}^M^[[K    \ fact: pacman_packages - {alpine}^M^[[K    | fact: pacman_packages - {alpine}^M^[[K    / fact: pacman_packages - {alpine}^M^[[K    - fact: pacman_packages - {alpine}^M^[[K    Loaded fact ^[[1mpacman_packages^[[0m$
    \ fact: home - {alpine}^M^[[K    | fact: home - {alpine}^M^[[K    / fact: home - {alpine}^M^[[K    - fact: home - {alpine}^M^[[K    Loaded fact ^[[1mhome^[[0m$
    \ fact: hostname - {alpine}^M^[[K    | fact: hostname - {alpine}^M^[[K    / fact: hostname - {alpine}^M^[[K    - fact: hostname - {alpine}^M^[[K    Loaded fact ^[[1mhostname^[[0m$
    \ fact: os - {alpine}^M^[[K    | fact: os - {alpine}^M^[[K    / fact: os - {alpine}^M^[[K    - fact: os - {alpine}^M^[[K    Loaded fact ^[[1mos^[[0m$
```

**Comment by Fizzadar** [comment]
The (very) long standing [pipelining issue](https://github.com/Fizzadar/pyinfra/issues/17) is effectively this. Unfortunately it's not quite so simple as facts either a) need arguments or b) rely on previous facts! So, the idea with pipelining is:

+ Load inventory/check OK, connect as normal
+ Execute each deploy file once, in "pipeline mode"; skip facts entirely and basically collect a list of facts that will be needed (and any arguments)
+ Execute/collect all the facts in parallel
  - or, in the case of one-liners, execute a single command that outputs each fact on a line
+ Re-execute the deploy file for each host, as normal, with all/most the facts pre-gathered
+ Execute the deploy as normal

**Comment by Fizzadar** [comment]
Escape wise Click _should_ figure that out itself; needs investigation (https://github.com/Fizzadar/pyinfra/issues/252).

**Comment by mkinney** [comment]
Ok. I didn't know it was a complex issue that was already being investigated.

It is like you need to build a dependency tree for the facts. I've not looked into the code. I was merely trying to save a few seconds watching a deploy. A few seconds is probably not worth saving if it will take lots of hours of research/coding/testing.

I'm ok with closing this issue as you have it tracked in other issues.

**Comment by Fizzadar** [comment]
I'm keen to do it but always held off because of the high rate of internal changes. Now that pyinfra is much more stable (and prepping v1) I'm going to revsist this when I get a chance!
