### ISSUE TITLE
easy way to print output in a deploy in color?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#241]
If I use `print('foo')` in a deploy, the output gets hard to find.

Is there a way to output your own custom messages in a different color like purple or bold?

**Comment by Fizzadar** [comment]
I'd recommend just using [`click`](https://click.palletsprojects.com/en/7.x/) for this (pyinfra uses it for the CLI), ie:

```py
print(click.style('message', 'yellow'))
```

**Comment by mkinney** [comment]
That's pretty cool!

Thanks!

<img width="753" alt="Screen Shot 2020-01-20 at 11 29 22 AM" src="https://user-images.githubusercontent.com/2219838/72752840-20c33600-3b78-11ea-8f90-0341de2aecfe.png">

**Comment by mkinney** [comment]
Ohh... check this out:

https://click.palletsprojects.com/en/7.x/bashcomplete/

Hmm... bash completion for pyinfra...

**Comment by mkinney** [comment]
I've added info in the doc and provided an example in `more-examples` branch.
