### ISSUE TITLE
Add top-level `debug-inventory` CLI command (and deprecate `--debug-data`)

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#242]
Would it make sense to have `all-inventory` or `--inventory` option added to show all items in inventory and their values/attributes?

**Comment by Fizzadar** [comment]
There's a `--debug-data` option which should cover this; but it requires specifying some commands, even if not needed. One option might be to add:

```sh
pyinfra inventory.py debug-inventory
```

**Comment by mkinney** [comment]
So, using the inventory.py in examples:

```
(venv) mikekinneymbp:examples mikekinney$ cat inventory.py
# pyinfra
# File: example/inventories/example.py
# Desc: example inventory, not actually used anywhere

# Define a group
web_servers = [
    'web-01.company.net',
    'web-02.company.net',
]


# Define another group
db_servers = [
    'db-01.company.net',
    # Define hosts with extra, per-host, data
    ('db-02.company.net', {'hello': 'world'}),
]
(venv) mikekinneymbp:examples mikekinney$ pyinfra inventory.py --debug-data fact os_version
--> Loading config...
--> Loading inventory...

--> Data for: web-01.company.net
{}

--> Data for: web-02.company.net
{}

--> Data for: db-01.company.net
{}

--> Data for: db-02.company.net
{
    "hello": "world"
}
```
Is web_servers still in scope in other deploy values supplied (or included) on the command line?

What would the `if` statements look like for:

```
# if I am a host in the db_servers:
    # install db
# if I am a web_server:
   # install apache

```

**Comment by Fizzadar** [comment]
So that'd basically look like:

```py
from pyinfra import host

if 'web_servers' in host.groups:
    # install db

if 'db_servers' in host.groups:
    # install db

# Alternatively:

from pyinfra import inventory

if host in inventory.get_group('web_servers'):...
```

The [groups & roles example](https://pyinfra.readthedocs.io/en/latest/examples/groups_roles.html) shows this pattern.

**Comment by Fizzadar** [comment]
Implemented in https://github.com/Fizzadar/pyinfra/commit/fd7abccdc6d49bb304204142587877ef0d2f8284 and documented in https://github.com/Fizzadar/pyinfra/commit/22ae60530e8238cb3920c2e7f0c4d64fc0ec4f6f.
