### ISSUE TITLE
ideas for running openvz operations locally?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#243]
I am having a hard time getting a local openvz environment.

It looks like https://download.openvz.org/debian/dists/ are pretty spartan. (nothing new-ish) I've tried a few combos of debian 7/8/9 but have had no luck.

I've tried using the `OpenVZ/Virtuozzo-7.0` vagrant box but it will not `yum update`.

Is there a good way to get a local openvz environment?

**Comment by Fizzadar** [comment]
Unfortunately I've had very little success with this - I managed to get CentOS 6(!) and OpenVZ 6 running on Virtualbox a while back, but haven't tried since. The VZ market is rapidly vanishing so I'm not sure there's much point putting too much effort into this!

**Comment by mkinney** [comment]
I totally agree. I've never used it, but assumed you (or someone that uses pyinfra) need it.

Deprecate all of the openvz operations?

**Comment by Fizzadar** [comment]
Yep I've used it extensively at [Afterburst](https://afterburst.com). I think they're OK to leave as-is; they're unit tested and still work, just doesn't need an example.
