### ISSUE TITLE
any plans to add firewall operations (ufw and firewalld)?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#246]
There are different firewall options. Ubuntu has ufw. I'm sure there are other software based firewalls.

I'm not sure what `firewall-cmd` does, but it looks like it uses iptables. From https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-using-firewalld-on-centos-7, "Firewalld is a firewall management solution available for many Linux distributions which acts as a frontend for the iptables packet filtering system provided by the Linux kernel."

https://help.ubuntu.com/community/UFW

Not sure the priority, but perhaps adding this to a future list of things to add. Maybe?

**Comment by Fizzadar** [comment]
It seems that everything is really `iptables` under the hood to me, which [has it's own module](https://pyinfra.readthedocs.io/en/latest/modules/iptables.html). Would be open to PRs for other CLIs but firewalls are so complex that it's hard to map all the options.

**Comment by mkinney** [comment]
Ha! I didn't realize that `ufw` uses iptables under the covers, too.

Ok. No worries.

**Comment by erentar** [comment]
I'd like to open this for reconsideration, firewalld is essential for networking on linux, and having to manage the very rich tapestry of options with bash and attempting to make them idempotent is rather difficult.
