### ISSUE TITLE
Add server.reboot operation

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#248]
It is not best practice, but I often would disable SELINUX and reboot, if it was either enforcing or permissive.

Changing the line in the file is relatively easy:
```
    files.line(
        {'Ensure SELINUX is disabled'},
        '/etc/sysconfig/selinux',
        r'SELINUX=.*',
        replace='SELINUX=disabled',
    )
```

but, if the value was changed, we should reboot before continuing.

See https://wiki.centos.org/HowTos/SELinux

We could sidestep the whole selinux configuration for now and perhaps add a `server.reboot_and_wait(delay=20, sleep=1, timeout=300)` operation. Maybe? That would solve most of the use cases I would run into. 

See https://docs.ansible.com/ansible/latest/modules/reboot_module.html and https://docs.ansible.com/ansible/latest/modules/wait_for_connection_module.html

Thoughts?

**Comment by Fizzadar** [comment]
I'm super keen on adding reboot support to pyinfra. I think it'd be incredibly useful to reboot a machine mid-deploy and continue the deploy once reconnected. This will take some thinking as pyinfra has never reconnected to machines mid-deploy, could also open up some interesting recovery options when things go wrong.

**Comment by Fizzadar** [comment]
Added in https://github.com/Fizzadar/pyinfra/commit/52a33472729c6c8f1b5f1a0900f68572e9c93b11, soon to be `v0.13.1` :)

**Comment by mkinney** [comment]
How frequently does the https://pyinfra.readthedocs.io/ get updated?

I don't see recent changes in https://pyinfra.readthedocs.io/en/latest/modules/puppet.html

**Comment by Fizzadar** [comment]
Argh - read the docs failed (again); rebuilt and should be updated :)

**Comment by mkinney** [comment]
Thanks!
