### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#251]
It would be nice to have bash completion for `pyinfra` command line.

Perhaps we can leverage this: https://click.palletsprojects.com/en/7.x/bashcomplete/

**Comment by Fizzadar** [comment]
So running `eval "$(_PYINFRA_COMPLETE=source pyinfra)"` already does this! Click is amazing. So I will add the script as `scripts/pyinfra-complete.sh`.

**Comment by Fizzadar** [comment]
Script added in https://github.com/Fizzadar/pyinfra/commit/b20b7741f1a67799d0d69453d5f8c86f1b83212e. Works fine but will now look to add more autocomplete helpers to the CLI as per the click docs.

**Comment by mkinney** [comment]
Ok.

Should probably add something to CONTRIBUTING.md and/or another place, but not quite sure where.

**Comment by yermulnik** [comment]
Apologies for resurrecting closed issue but wouldn't it make sense to install completions on `pip install pyinfra`?

**Comment by Fizzadar** [comment]
@yermulnik no worries! I did some investigation into this but unfortunately it seems bash completion folders vary by OS, OS version and environment! As such I don't think there's really any clean way to do this. However, I am going to improve/highlight the documentation on this, as it should be accessible to all.

**Comment by yermulnik** [comment]
@Fizzadar Thank you for taking a look into it. I meant more of having an option to have a completion file installed along with the package itself + howto in README on how to have completion activated by e.g. sourcing the file from within `.bashrc`.
