### ISSUE TITLE
can you specify another directory to search for files and/or templates?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#257]
If you have your files like this:

```
    examples
        deploy1.py
        /files
        /templates
    some_other_dir
        deploy2.py
```

In deploy2.py, if you do this:
`    local.include('../deploy1.py')`
the files and templates are not available/not found.

Is there a way around this?

Or should pyinfra figure out that the files/templates should be relative or something?

Thoughts?

Please let me know if this is unclear or does not make sense.

**Comment by Fizzadar** [comment]
So currently templates/files are all relative to the "deploy directory" which is the original file - in this case `some_other_dir` would be the deploy dir. Handling multiple directories is much more complex as there could be two files of the same name.

There's an `add_deploy_dir=True` flag on most of the `files.*` operations, which should make it possible to stop prepending the deploy dir (so would be relative to the working directory pyinfra is executed from).

So you could potentially use an absolute path, ie in `deploy1.py`:

```py
this_dir = path.abs(path.dirname(__file__))
files.template(
    {'Upload template from _this_ directory'},
    path.join(this_dir, 'templates', 'my-template.j2'),
}
```

More of a workaround than a good solution; certainly open to other options for this.

**Comment by mkinney** [comment]
Hmm... not sure. I see how that workaround would work.

But, I think the focus should be on the local.include() operation, as that's where I ran into the issue.

The use case for this would be the examples directory. I don't want to have to put the test files in the same directory as the deploys.

Going to think about it a bit more. I'm still refactoring some tests in a branch for examples directory.

**Comment by mkinney** [comment]
Closing issue as it works as intended. May file another issue/question later because this may come up again.
