### ISSUE TITLE
local.py, stderr=STDOUT

### ISSUE THREAD

**Issue by Folo23** [Fizzadar/pyinfra#258]
First, thank you very much for this cool library.

I've been trying it out deploying locally to Vagrant. Unfortunately, I have Ruby 2.7.0 installed, which isn't currently supported by Vagrant. This means I see helpful "notes" on `stderr` every time I run Vagrant like:

`NOTE: Gem::Specification.default_specifications_dir is deprecated; use Gem.default_specifications_dir instead. It will be removed on or after 2020-02-01.`

This causes `pyinfra @vagrant exec -- echo "hello world"` to choke. Changing line 123 of `local.py` from:
```python
process = Popen(command, shell=True, stdout=PIPE, stderr=STDOUT)
```
to:
```python
process = Popen(command, shell=True, stdout=PIPE)
```

makes the `@vagrant` connector work. Is there a reason the `stdout` and `stderr` outputs are combined in `shell(command)` in `local.py`? Changing the line doesn't seem to break any tests.

**Comment by Fizzadar** [comment]
Definitely a bug - and definitely code that should be removed and de-duplicated with the `@local` connector.

**Comment by mkinney** [comment]
@Folo23 Check out https://mechboxes.github.io/mech/ if you have a chance. You don't have to deal with ruby.

**Comment by Fizzadar** [comment]
@Folo23 this should now be fixed by https://github.com/Fizzadar/pyinfra/commit/548978c724a39512c215d9cd39b89c8158591aea which I'll release in `v0.13.1` in the coming hours/days!

**Comment by Folo23** [comment]
@Fizzadar Thanks for fixing it so quickly! I thought of submitting a 1-line pull request, but it looks like you did a more extensive refactoring.

@mkinney I hadn't heard of Mech. Will check it out for setting up virtual machines.
