### ISSUE TITLE
thoughts on things that would assist with support? (add `pyinfra --support`)

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#261]
Thoughts on adding a "--for-support" option that would show some helpful info:
- print local os info
- print pyinfra version
- print python version
- Visit 'https://github.com/Fizzadar/pyinfra/issues' and be sure to include the info above plus a small snippet that will demo the issue. (a small deploy) with the options '-vv --debug' added.

Or perhaps when you add '--debug' it will print support info like that above?

Also, may want to consider adding "template" to the issues. (I don't know how to do it but I liked how Molecule used to to it.) I just checked and they've taken it up a notch now that RedHat took ownership of it. See https://github.com/ansible/molecule/issues/new/choose 

Here's the bug one:

```
<!--- Verify first that your issue is not already reported on GitHub -->
<!--- Do not report bugs before reproducing them with the code of the master branch! -->
<!--- Please also check https://molecule.readthedocs.io/en/latest/faq.html --->
<!--- Please use https://groups.google.com/forum/#!forum/molecule-users for usage questions -->

# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
```

Molecule installation method (one of):

- source
- pip

Ansible installation method (one of):

- source
- pip
- OS package

Detail any linters or test runners used:

# Desired Behavior

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](https://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.
```

Thoughts?

**Comment by Fizzadar** [comment]
Have added two basic issue templates for this (https://github.com/Fizzadar/pyinfra/pull/269).

**Comment by mkinney** [comment]
That looks great.

Thanks

**Comment by Fizzadar** [comment]
Also agree a `pyinfra --support` would be useful to print out the info in one blob and link to the issues/etc!

**Comment by Fizzadar** [comment]
Added in https://github.com/Fizzadar/pyinfra/commit/b6fc1e2a6b647d97546905b804a8f556ece173a1 :)

**Comment by mkinney** [comment]
I like the support. So, we can probably change the questions if a bug:

1. Have them run `pyinfra --support`. Perhaps add more info here:

```
>>> import platform
>>> print(platform.uname())
uname_result(system='Darwin', node='sweet.local', release='19.2.0', version='Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64', machine='x86_64', processor='i386')

>>> import platform
>>> print(platform.uname())
uname_result(system='Windows', node='vagrant', release='10', version='10.0.17763', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 13, GenuineIntel')
```

2. Pip is ok (might want to suggest they 'python -m pip install --upgrade pip'. Maybe?)

3. Drop the 3rd question (if you update the '--support' option to show more about os info)

4. Drop python version as it is included in the `--support` above.

**Comment by mkinney** [comment]
Note that platform is being deprecated (I think). But, this did not work for me:

```
(venv) PS C:\Users\vagrant> python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print(os.uname())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'uname'
```

**Comment by mkinney** [comment]
Looks great! Here's what it looks like from windows:

```
(venv) PS C:\Users\vagrant> pyinfra.exe --support
--> Support information:

    If you're having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues.
    When adding an issue, be sure to include the following:

    System: Windows
    pyinfra: v0.13.3
    Executable: C:\Users\vagrant\venv\Scripts\pyinfra.exe
    Python: 3.7.6 (CPython, MSC v.1916 64 bit (AMD64))
```
