### ISSUE TITLE
garbage at end of deploy from windows host

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#270]
**Describe the bug**
Getting some weird characters at the end of a deploy from a windows host to a linux guest. (don't think the guest really matters)

**To Reproduce**
1. from windows, install pyinfra
2. do simple deploy
3. see output at the end

<img width="682" alt="Screen Shot 2020-01-28 at 1 54 05 PM" src="https://user-images.githubusercontent.com/2219838/73309030-54383d00-41d6-11ea-8aa5-2bc9c05d5821.png">

**Expected behavior**
There should be no escape sequences after the end of a deploy. (works from a mac host)

Here's the output from a mac host:
<img width="771" alt="Screen Shot 2020-01-28 at 2 00 15 PM" src="https://user-images.githubusercontent.com/2219838/73309137-8cd81680-41d6-11ea-884a-1faabedb55ec.png">

**Meta**
+ Include output of `pyinfra --version`.
(venv) PS C:\Users\vagrant> pyinfra --version
pyinfra: v0.13.3

+ How was pyinfra installed (source/pip)?
pip

+ Which OS are you using (incl. version)?
windows server 2019

+ Which Python version are you using?
(venv) PS C:\Users\vagrant> python --version
Python 3.7.6

(venv) PS C:\Users\vagrant> pyinfra --support
--> Support information:

More:
    If you're having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues.
    When adding an issue, be sure to include the following:

    System: Windows
    pyinfra: v0.13.3
    Executable: C:\Users\vagrant\venv\Scripts\pyinfra.exe
    Python: 3.7.6 (CPython, MSC v.1916 64 bit (AMD64))

**Comment by mkinney** [comment]
Might be related to this: https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/progress.py#L64

**Comment by Fizzadar** [comment]
Should now be disabled on Windows via https://github.com/Fizzadar/pyinfra/commit/726ced72e0eaad2a720e81e02a9f6539beea9af8.

**Comment by mkinney** [comment]
Thanks!

Let me know when there is a new release and I'll re-test.

**Comment by Fizzadar** [comment]
Now released in `v0.13.4`!

**Comment by mkinney** [comment]
Looks really good!

<img width="796" alt="Screen Shot 2020-01-30 at 9 29 39 AM" src="https://user-images.githubusercontent.com/2219838/73474312-23294b00-4343-11ea-8ccf-d08c78261f5d.png">
