### ISSUE TITLE
only print standard output

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#272]
**Is your feature request related to a problem? Please describe.**
There is too much output.

**Describe the solution you'd like**
I would like to see only the standard output from print statements.

For example: `pyinfra @mech/ubuntu18 exec -- echo hello` currently produces this output:
```
(venv) mikekinney@sweet mkinney_pyinfra % pyinfra @mech/ubuntu18 exec -- echo hello
--> Loading config...
--> Loading inventory...
    Getting Mech config...

--> Connecting to hosts...
    [@mech/ubuntu18] Connected

--> Proposed changes:
    Groups: @mech
    [@mech/ubuntu18]   Operations: 1   Commands: 1

--> Beginning operation run...
--> Starting operation: Server/Shell ('echo hello',)
[@mech/ubuntu18] >>> sh -c 'echo hello'
[@mech/ubuntu18] hello
    [@mech/ubuntu18] Success

--> Results:
    Groups: @mech
    [@mech/ubuntu18]   Successful: 1   Errors: 0   Commands: 1/1
```

But, I would like to see:
```
(venv) mikekinney@sweet mkinney_pyinfra % pyinfra @mech/ubuntu18 exec -- echo hello
[@mech/ubuntu18] hello
```

Perhaps add a `--quiet` option?

Or move those output lines to the '-v' value?

**Comment by Fizzadar** [comment]
I think this makes sense for the `exec` use-case. Currently pyinfra doesn't differentiate between input/output printing but I agree here that seems silly. Will change to `-v` flagging print both, and `exec` as a special case where only output, not input, is printed.

**Comment by Fizzadar** [comment]
Split up input/output in https://github.com/Fizzadar/pyinfra/commit/452ad7d8406b716101e6d1362da9ac1311c74cc3 and set exec to only do output in https://github.com/Fizzadar/pyinfra/commit/f15b01c52096c7d379e231314a74ac89667ec2ab.

**Comment by Fizzadar** [comment]
Now released in `v0.13.4`.

**Comment by mkinney** [comment]
I created a new dir/virtualenv for testing. I'm still seeing all of the output.

```
(venv) mikekinney@sweet tmp_pyinfra % pyinfra --user vagrant --password vagrant 192.168.3.134 exec -- echo hello
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [192.168.3.134] Connected

--> Proposed changes:
    Ungrouped:
    [192.168.3.134]   Operations: 1   Commands: 1

--> Beginning operation run...
--> Starting operation: Server/Shell ('echo hello',)
[192.168.3.134] hello
    [192.168.3.134] Success

--> Results:
    Ungrouped:
    [192.168.3.134]   Successful: 1   Errors: 0   Commands: 1/1
(venv) mikekinney@sweet tmp_pyinfra % pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Darwin
      Platform: Darwin-19.3.0-x86_64-i386-64bit
      Release: 19.3.0
      Machine: x86_64
    pyinfra: v0.13.4
    Executable: /Users/mikekinney/python/tmp_pyinfra/venv/bin/pyinfra
    Python: 3.7.6 (CPython, Clang 11.0.0 (clang-1100.0.33.16))
```

**Comment by Fizzadar** [comment]
My apologies I misunderstood! I was removing just the input line (`>>> echo hello`). I like a `--quiet` option that hides most logging (will keep error logs warning+critical going to stderr).

**Comment by mkinney** [comment]
No worries.

Thanks for your help

**Comment by Fizzadar** [comment]
https://github.com/Fizzadar/pyinfra/commit/8fdd68abfa47856a6c30e77b1922143d355ae279 should cover this; releasing `v0.13.5` now.
