### ISSUE TITLE
Document the release process?

### ISSUE THREAD

**Issue by mkinney** [Fizzadar/pyinfra#278]
**Is your feature request related to a problem? Please describe.**
I'm interested in knowing more about the release process for pyinfra. 

**Describe the solution you'd like**
Can the steps that are used to create a release be documented?

I'm experimenting with github actions. See https://github.com/mkinney/hello_python_cli/blob/master/.github/workflows/publish-to-test-pypi.yml

**Comment by mkinney** [comment]
I am using:
```
  git commit -m 'bump to v0.0.5'
  git tag v0.0.5
  git push origin v0.0.5
  git push
```

Is that similar to what is used?

How do you keep track of changes for https://github.com/Fizzadar/pyinfra/blob/master/CHANGELOG.md ?

How are docs published to read the docs?

Any other steps?

**Comment by Fizzadar** [comment]
Very similar!; the entire release is encapsulated in a shell script, [`scripts/release.sh`](https://github.com/Fizzadar/pyinfra/blob/master/scripts/release.sh).

Things like readthedocs are automated (ie readthedocs pics up the push and builds the docs itself).

**Comment by mkinney** [comment]
That's great! Thanks.
