### ISSUE TITLE
Use code formatter "black"

### ISSUE THREAD

**Issue by vilhelmprytz** [Fizzadar/pyinfra#283]
**Is your feature request related to a problem? Please describe.**
Using a code formatter makes sure that code style throughout the project is consistent and readable by different developers.

**Describe the solution you'd like**
Enforce the use of the [black](https://github.com/psf/black) code formatter.

I'd be more than happy to send in a pull request with all the code re-formatted using black.

**Comment by Fizzadar** [comment]
There was an old issue on this subject: https://github.com/Fizzadar/pyinfra/issues/193. Personally I'm not a fan of Black. I think flake8 does a good enough job while maintaining some level flexibility.

Are there specific areas of the codebase that could be improved readability wise? I would be keen to improve that (and if that means using something more strict like pylint or stronger flake8 rules/plugins I'm good with that).

**Comment by VilhelmPrytz** [comment]
Oops, I missed the old issue :smile: There are no specific areas of the codebase that I think would be improved really, it's just that enforcing the use of black (or any other code formatter) ensures all code follows a certain format.

**Comment by Fizzadar** [comment]
👍 I agree it's a good idea to enforce a code style. I think `black -S` could be used to format without enforcing the quotes, it looks like the best option for Python code formatting!

Flake8 can continue to enforce quotes + errors. There's a [`flake8-black`](https://pypi.org/project/flake8-black/) plugin as well which would integrate w/CI.

**Comment by VilhelmPrytz** [comment]
If you'd want it, I could send in a PR with `black -S` on all code? :smile:

And regarding the CI integration, you could just install black and run it using `black . -S --check`. Alternatively, I would recommend [tox](https://tox.readthedocs.io/en/latest/) as it works perfectly with both flake8, black and others (pytest, pylint etc).

**Comment by Fizzadar** [comment]
Hmm - I think it'd be best to switch as part of pyinfra v1 (no major changes; removal of all legacy code). I've a working branch for that so will run/commit black formatting on there bofore v1!

**Comment by nikaro** [comment]
I'm also not a fan of black since it often leads to have inconsistent style in the same file.

For example:
```python
list_of_colors = [
    "black",
    "blue",
    "red",
]
list_of_letters = [
    "a",
    "b",
    "c",
    [...],
    "z",
]
list_of_numbers = [
    0,
    1,
    2,
    [...],
    9,
]
```
Would become:
```python
list_of_colors = ["black", "blue", "red"]
list_of_letters = [
    "a",
    "b",
    "c",
    [...],
    "z",
]
list_of_numbers = [0, 1, 2, [...], 9]
```
Which i find inconsistent and sometimes ugly.

**Comment by vilhelmprytz** [comment]
> I'm also not a fan of black since it often leads to have inconsistent style in the same file.
> 
> For example:
> 
> ```python
> list_of_colors = [
>     "black",
>     "blue",
>     "red",
> ]
> list_of_letters = [
>     "a",
>     "b",
>     "c",
>     [...],
>     "z",
> ]
> list_of_numbers = [
>     0,
>     1,
>     2,
>     [...],
>     9,
> ]
> ```
> 
> Would become:
> 
> ```python
> list_of_colors = ["black", "blue", "red"]
> list_of_letters = [
>     "a",
>     "b",
>     "c",
>     [...],
>     "z",
> ]
> list_of_numbers = [0, 1, 2, [...], 9]
> ```
> 
> Which i find inconsistent and sometimes ugly.

Fair point. I generally think the pros of using black are more than the cons, not to mention the consistency between different projects. I believe you can configure it slightly as well.

**Comment by Fizzadar** [comment]
I've been playing around a lot with black these last few days and am unsatisfied with the results. Overall I'm pro code formatter usage, and will continue to look at options for pyinfra. That said, I have a number of issues with black:

1. As above, inconsistent output for similar lists
2. Trailing comma support appears to be entirely broken (running black inconsistently adds trailing commas, causing `flake8-commas` to, correctly, show warnings)
3. In tandem with above; https://github.com/psf/black/issues/1288
4. Black's refusal to entertain a `--single-quote` or similar flag is ridiculous, the addition of the `-S` flag to disable string normalisation is a half-arsed "fix". Given the `-S` flag they should implement a single quote config option, in my opinion
5. Upcoming changes to docstrings / more enforced rules

`yapf` may be a good option here, or just sticking with `flake8` (possibly with more plugins/strict config).
