### ISSUE TITLE
Why do we need pyinfra?

### ISSUE THREAD

**Issue by szwed** [Fizzadar/pyinfra#29]
1. There is already a number of similar tools, far more advanced than this one, isn't it easier to just write a Salt formula or Puppet recipe?
2. Docker + Mesos & Kubernetes solves the problem even better, why not to choose this way?

**Comment by uggedal** [comment]
1. Why did Luke Kanies start on Puppet when we had CFEngine? Also, have you read *Design Features* in the README?
2. No one is stopping you from choosing the obviously "better way" with Docker + Mesos/Kubernetes.
