### ISSUE TITLE
Use checksum arguments to validate existing files in `files.download`

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#295]
If the file already exists at the destination and any of the checksum arguments are provided, check the file matches and re-download if not.

**Comment by sysadmin75** [comment]
@Fizzadar  I was looking at this issue. I see there are a couple routes that can be taken.
One route would be to modify the host.fact.file that is already called in the download operation, and add a sha256sum (also md5sum and sha1sum) function to that fact.
Or the other route would be to add these sha and md5 functions to the download operation.
I just wanted to get your thoughts on what the best way you think would be.

**Comment by Fizzadar** [comment]
@sysadmin75 thanks for looking into this! So I put a placeholder in the operation a while back (https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/operations/files.py#L84). I was thinking of just using the existing `sha1` fact (example @ https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/operations/files.py#L579) to check and, if they don't match, set `download = True`.

Then the same for the other checksums - these will also need facts implemented - currently only `sha1_file` is a fact (https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/facts/files.py#L36).

Let me know if that does/doesn't make sense!

**Comment by sysadmin75** [comment]
>  I was thinking of just using the existing sha1 fact
Do you mean you would actually use the `host.fact.sha1_file` or do you mean you want to implement a host fact for any checksum type that is given (e.g. sha256sum, md5sum, etc)?

**Comment by Fizzadar** [comment]
Both! `host.fact.sha1_file` can be used to check against the `sha1sum` argument. For the `sha256sum` and `ms5sum` arguments will need to create new `host.fact.md5_file` and `host.fact.sha256_file` facts.

**Comment by sysadmin75** [comment]
@Fizzadar 
I noticed you use a regex to get the hash from the sha1sum command. Can you go into detail why you chose to handle it this way?

**Comment by Fizzadar** [comment]
@sysadmin75 simplest option to match the hash within the line - splitting or similar would also work but the regexes covered the different output formats (`sha1` vs `shasum`) nicely. But certainly not concerned about changing these things if there's a superior parsing method!
