### ISSUE TITLE
missing newline on apt.repo in loop

### ISSUE THREAD

**Issue by ak5** [Fizzadar/pyinfra#297]
**Describe the bug**
No new line in added `/etc/apt/sources.list.d/<filename>.list` file

**To Reproduce**
Steps to reproduce the behavior (include code & usage example):

target is a fresh Ubuntu 18.0.3 server

```python
from pyinfra.modules import apt

apt.key(
  {'add Nodesource apt gpg key'},
  key='https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
)

repos = [
  'deb https://deb.nodesource.com/node_14.x bionic main'
  'deb-src https://deb.nodesource.com/node_14.x bionic main'
]

for repo in repos:
  apt.repo({'add Nodesource repos'}, repo, filename='nodesource')

packages = [
  'nodejs',
  'build-essential'
]

apt.packages({'install nodejs'}, packages, update=True)
```

/etc/apt/sources.list.d/nodesource.list

```
deb https://deb.nodesource.com/node_14.x bionic maindeb-src https://deb.nodesource.com/node_14.x bionic main
```

**Expected behavior**

New line should exist

/etc/apt/sources.list.d/nodesource.list

```
deb https://deb.nodesource.com/node_14.x bionic main
deb-src https://deb.nodesource.com/node_14.x bionic main
```

**Meta**
+ Include output of `pyinfra --support`
```
    System: Linux
      Platform: Linux-5.6.14-arch1-1-x86_64-with-glibc2.2.5
      Release: 5.6.14-arch1-1
      Machine: x86_64
    pyinfra: v0.14.4
    Executable: /home/testuser/.local/bin/pyinfra
    Python: 3.8.3 (CPython, GCC 10.1.0)
```
+ How was pyinfra installed (source/pip)?
pip
+ Include pyinfra-debug.log (if one was created)
N/A
+ Consider including output with `-vv` and `--debug`.
N/A

**Comment by sysadmin75** [comment]
Hello, I was able to repro the issue using the deploy.py you have pasted above.  However, the repos list is wrong. The list should be. comma separated like so:
```
repos = [
   'deb https://deb.nodesource.com/node_14.x bionic main',
   'deb-src https://deb.nodesource.com/node_14.x bionic main'
]
```
Once I make this change, the repo file is written correctly.
```
#cat /etc/apt/sources.list.d/nodesource.list 
deb https://deb.nodesource.com/node_14.x bionic main
deb-src https://deb.nodesource.com/node_14.x bionic main
```

**Comment by ak5** [comment]
xD thanks wow
