### ISSUE TITLE
Broken link to contributing guide in docs

### ISSUE THREAD

**Issue by stchris** [Fizzadar/pyinfra#298]
**Describe the bug**
The page at https://pyinfra.readthedocs.io/en/latest/contributing.html points to https://github.com/Fizzadar/pyinfra/blob/master/CONTRIBUTING, but the link is broken.

**To Reproduce**
Navigate to https://pyinfra.readthedocs.io/en/latest/contributing.html, click on "Contributing guide".

**Expected behavior**
The link should go to https://github.com/Fizzadar/pyinfra/blob/master/CONTRIBUTING.md

**Meta**
+ Include output of `pyinfra --support`.
+ How was pyinfra installed (source/pip)?
+ Include pyinfra-debug.log (if one was created)
+ Consider including output with `-vv` and `--debug`.

**Comment by Fizzadar** [comment]
Thanks @stchris, https://github.com/Fizzadar/pyinfra/commit/e0982134ee6dafaaef71d46452b7f0ba19516da6 should fix this!
