### ISSUE TITLE
Import hosts in Ansible inventory

### ISSUE THREAD

**Issue by ricardbejarano** [Fizzadar/pyinfra#301]
**Is your feature request related to a problem? Please describe.**
I use Ansible _alongside_ pyinfra, and it'd be great if they supported each others' inventory formats.
Being pyinfra the "underdog" one, it'd be great if it added support for parsing Ansible inventories.

**Describe the solution you'd like**
Since Ansible has YAML-formatted inventories, it's actually pretty easy to extract a group's hosts into a Python list (pyinfra's "format").

In fact, given that pyinfra is so scriptable, I've written a little snippet to extract an Ansible group's hosts into a list in pyinfra:

```python
def flatten_list(root_list):
  items = []
  for item in root_list:
    if isinstance(item, list):
      for item in flatten_list(item):
        items.append(item)
    else:
      items.append(item)
  return items

def extract_ansible_inventory_hosts(ansible_inventory):
  hosts = []
  for group in ansible_inventory:
    if "hosts" in ansible_inventory[group]:
      for host in ansible_inventory[group]["hosts"]:
        hosts.append(host)
    if "children" in ansible_inventory[group]:
      for host in extract_ansible_inventory_hosts(ansible_inventory[group]["children"]):
        hosts.append(host)
  return hosts

def extract_ansible_inventory_group(ansible_inventory, group):
  if group in ansible_inventory:
    hosts = []
    if "hosts" in ansible_inventory[group]:
      hosts = list(ansible_inventory[group]["hosts"].keys())
    if "children" in ansible_inventory[group]:
      hosts += extract_ansible_inventory_hosts(ansible_inventory[group]["children"])
    return hosts
  return [
    extract_ansible_inventory_group(ansible_inventory[child]["children"], group)
    for child in ansible_inventory
    if "children" in ansible_inventory[child]
  ]

def extract_ansible_inventory(ansible_inventory_file_path, group):
  import yaml
  with open(ansible_inventory_file_path) as ansible_inventory_file:
    ansible_inventory = yaml.safe_load(ansible_inventory_file)
  return list(set(flatten_list(extract_ansible_inventory_group(ansible_inventory, group))))

linux = extract_ansible_inventory("ansible_inventory.yaml", "linux")
```

The above works with nested groups, too.

This can be prepended in pyinfra's inventory, but it'd be great if it came built-in as some sort of helper.
It could also be extended to support other configuration management systems' inventories.

And, if we start extending inventorying, we could add helpers to import inventory from other sources (VMware, Consul, ...).

**Comment by Fizzadar** [comment]
@ricardbejarano so pyinfra technically can already read ansible ini-style inventory using [the `@ansible` connector](https://pyinfra.readthedocs.io/en/latest/connectors.html#ansible). This is implemented here: https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/api/connectors/ansible.py.

The YAML loading code would be a great addition here! Happy to merge a PR or I can add it myself when I get a chance :)

**Comment by ricardbejarano** [comment]
Didn't know about the `@ansible` connector, but yeah INI doesn't really cut it when dealing with large entangled inventories (probably should use something else when it gets that large).

I can work on a PR for that but I'll have to read some code first, I discovered and started using pyinfra yesterday.

**Comment by ricardbejarano** [comment]
Created #303 for this.

Close this if merged.
