### ISSUE TITLE
Investigate: Automatic sudo password

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#318]
**Is your feature request related to a problem? Please describe.**
Sudo w/password requires explicitly including `use_sudo_password=[True|str]` in the operation.

**Describe the solution you'd like**
Deprecate `use_sudo_password` global argument and ask for password as needed, accounting for commands the SSH user does not need sudo for (`sudo -l`).

This is an investigation piece - it may be impossible or too complex to implement this feature as described.

**Comment by gnat** [comment]
Would be extremely useful to have a way to apply `use_sudo_password` on all operations on a per-script basis or per-run basis.

Applying an entire script's changes as sudo would be an extremely common use case, I would imagine...

**Comment by Fizzadar** [comment]
Finally live in v1.5!

**Comment by gnat** [comment]
Tested and works. Killer change @Fizzadar !

**Comment by williamblair333** [comment]
My user account is in target machine's visudo file and does not require a password to do sudo operations.  Will this allow sudo operations without prompting for a password?  If so, would you post an example?

**Comment by rsheftel** [comment]
Perhaps I am missing where in the documentation this is, but I have a simple case that I have some commands that require sudo and I cannot figure out how to make pyinfra either take in the sudo password or prompt me for it. I am using v2.7 and when the script gets to a command that requires sudo password it just hangs.
