### ISSUE TITLE
pkg_add not found, should use pkg install instead

### ISSUE THREAD

**Issue by SebRut** [Fizzadar/pyinfra#320]
**Describe the bug**
`pkg` module tries to use nonexistent `pkg_add` to install packages.

**To Reproduce**
1. Define FreeNAS jail in inventory
2. Try to install package using `pkg` module

**Expected behavior**
The package gets installed

**Meta**
+ `pyinfra --support` output
```
    System: Linux
      Platform: Linux-5.6.16-1-MANJARO-x86_64-with-glibc2.2.5
      Release: 5.6.16-1-MANJARO
      Machine: x86_64
    pyinfra: v0.14.5
    Executable: /home/sebastian/.local/bin/pyinfra
    Python: 3.8.3 (CPython, GCC 10.1.0)
```

+ Consider including output with `-vv` and `--debug`.
```
...
[sismics.lan] >>> sh -c pkg_info
[sismics.lan] sh: pkg_info: not found
    Loaded fact pkg_packages
...
```

**Comment by Fizzadar** [comment]
This should be fixed by https://github.com/Fizzadar/pyinfra/commit/0e8a4299b039c4776ed4341f99800b0475201dab + https://github.com/Fizzadar/pyinfra/commit/7bd6a8df1a52bfb3a14452c7e4f9e77256d36621, releasing `0.15.dev1` shortly and full `0.15` will follow in a few days!
