### ISSUE TITLE
Drop python2 support (& 3.5)

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#329]
v1 will be the last version to support py2. This is to support legacy systems still using pyinfra. I expect v2 to be at least a year off from today.

**Comment by sysadmin75** [comment]
Do you have a roadmap listed somewhere?

**Comment by Fizzadar** [comment]
Forgot to update - roadmap is now setup @ https://github.com/Fizzadar/pyinfra/projects/1#card-44117269!

**Comment by yggdr** [comment]
Do you already have plans on which python 3 version you'll support once you drop python3? Will it stay with 3.5+, or will you go higher, like 3.6+ which seems to be supported on older LTS versions of major Linux distributions like CentOS and Ubuntu.

Have you given any thought about replacing gevent with native async?

**Comment by Fizzadar** [comment]
Hi @yggdr! I'm thinking Python 3.6+ as 3.5 has been EOL for a while now.

Regarding native async - that entirely depends on paramiko (https://github.com/paramiko/paramiko/issues/389) - currently this works because gevent monkey patches the stdlib, allowing the non-async paramiko code to run asynchronously. Good thing is this works extremely well so there's no particular pressure to move to native async.

**Comment by Fizzadar** [comment]
And it's finally live!
