### ISSUE TITLE
Release V1

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#333]
Issue tracking V1 release. Milestone: https://github.com/Fizzadar/pyinfra/milestone/6

Changes:

+ Change default value of `create_remote_dir` to `True`
+ Change default value of `interpolate_values` to `False`
+ Remove all legacy compat code (will print warning in 0.x versions)

**Comment by Fizzadar** [comment]
🎉 🎉 🎉

**Comment by wookayin** [comment]
Congratulations and thanks for your hard work!
