### ISSUE TITLE
apt.repro not working when using an extra filename argument

### ISSUE THREAD

**Issue by questor** [Fizzadar/pyinfra#336]
**Describe the bug**
I try to add a repro, but it doesn't work if I specify that it should be put into an extra file. There is no file created. When I do not use an extra file (remove the filename-argument) it works.

**To Reproduce**
```py
apt.repo(
    {'install perforce repo'},
    'deb http://package.perforce.com/apt/ubuntu bionic release',
    present=True,
    filename="perforce",
)
```

**Expected behavior**
I would expect a file "perforce.list" in "/etc/apt/sources.list.d/"

**Meta**
+ Include output of `pyinfra --support`.
```
    System: Linux
      Platform: Linux-5.3.0-59-generic-x86_64-with-Ubuntu-18.04-bionic
      Release: 5.3.0-59-generic
      Machine: x86_64
    pyinfra: v0.15
    Executable: /home/dev/.local/bin/pyinfra
    Python: 2.7.17 (CPython, GCC 7.5.0)
```

+ How was pyinfra installed (source/pip)?
from github

+ Include pyinfra-debug.log (if one was created)
```
--> Starting operation: install perforce repo 
[@local] >>> sudo -H -n -i sh -c '# If the file now exists
                if [ -f "/etc/apt/sources.list.d/perforce.list" ]; then
                    # Grep for the line, sed if matches
                    (grep "^.*deb http://package.perforce.com/apt/ubuntu bionic release.*$" "/etc/apt/sources.list.d/perforce.list" && sed -i="" "s/^.*deb http:\/\/package.perforce.com\/apt\/ubuntu bionic release.*$//" /etc/apt/sources.list.d/perforce.list) 2> /dev/null ||                     # Else echo
                    echo "deb http://package.perforce.com/apt/ubuntu bionic release" >> /etc/apt/sources.list.d/perforce.list

                # No file, just echo
                else
                    echo "deb http://package.perforce.com/apt/ubuntu bionic release" >> /etc/apt/sources.list.d/perforce.list
                fi'
[@local] mesg: ttyname failed: Inappropriate ioctl for device
    [@local] Success
```

Additional note: the ttyname failed comes from a bug in the .profile file of the root user, see https://superuser.com/questions/1241548/xubuntu-16-04-ttyname-failed-inappropriate-ioctl-for-device    but not sure if that is really an issue or just trashing the console.

**Comment by Fizzadar** [comment]
This definitely looks wrong, if the file doesn't exist it should just create + echo to it. Will investigate!

**Comment by Fizzadar** [comment]
@questor I can't replicate this using Docker or within an Ubuntu 18 VM. If you apply the fix from the SO question does it work? The command being executed is correct/should work.

```
$ pyinfra @docker/ubuntu:18.04 apt-test.py
--> Loading config...
--> Loading inventory...
    The @docker connector is in beta!

--> Connecting to hosts...
    [@docker/ubuntu:18.04] Connected

--> Preparing operations...
    Loading: apt-test.py
    [@docker/ubuntu:18.04] Ready: apt-test.py

--> Proposed changes:
    Groups: @docker
    [@docker/ubuntu:18.04]   Operations: 1   Commands: 1

--> Beginning operation run...
--> Starting operation: install perforce repo
    [@docker/ubuntu:18.04] Success

--> Results:
    Groups: @docker
    [@docker/ubuntu:18.04]   Successful: 1   Errors: 0   Commands: 1/1
    [@docker/ubuntu:18.04] docker build complete, image ID: 17d0a8499543

$ docker run -it 17d0a8499543 sh
root@331af80ed4e9:/# cat /etc/apt/sources.list.d/perforce.list
deb http://package.perforce.com/apt/ubuntu bionic release
```

**Comment by questor** [comment]
I've patched my config and didn't get the "ttyname failed" message, but still does not work. I've used the "@local" deployment, might this make a change? What I noticed is that I received a "success" message even in the not working case. I've added some logging code and found this (note the printed "blub" and no "blub2"):
--> Starting operation: install perforce repo 
[@local] >>> sudo -H -n -i sh -c 'echo "blub"
                # If the file now exists
                echo "blub2"
                if [ -f "/etc/apt/sources.list.d/perforce.list" ]; then
                    echo "file exists, check if good" >> /etc/apt/sources.list.d/path1.txt
                    # Grep for the line, sed if matches
                    (grep "^.*deb http://package.perforce.com/apt/ubuntu bionic release.*$" "/etc/apt/sources.list.d/perforce.list" && sed -i="" "s/^.*deb http:\/\/package.perforce.com\/apt\/ubuntu bionic release.*$//" /etc/apt/sources.list.d/perforce.list) 2> /dev/null ||                     # Else echo
                    echo "deb http://package.perforce.com/apt/ubuntu bionic release" >> /etc/apt/sources.list.d/perforce.list
                # No file, just echo
                else
                    echo "file exists, check if good" >> /etc/apt/sources.list.d/path2.txt
                    echo "deb http://package.perforce.com/apt/ubuntu bionic release" >> /etc/apt/sources.list.d/perforce.list
                fi'
[@local] blub
    [@local] Success

When I remove all comments (btw it seems there is an error here because of the comment hiding the "\" https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/operations/files.py#L248) I get a syntax error because of the "then" and I'm not sure why?! Is it some sort of new-line problem (I've checked files.py and it's NOT using windows-new-lines).

btw my sh is pointing to bash, should be fine I guess?

**Comment by Fizzadar** [comment]
Hmm - I also tried using `@local` and it worked the same as my comment above. After you ran the above does `/etc/apt/sources.list.d/path2.txt` exist/contain anything?

As far as next steps go I can only think of changing the command in the operation to echo instead of writing to the file, this would help identify the path being executed. Currently we don't know if the first if statement is evaluating true or false.

**Comment by Fizzadar** [comment]
I've created a quick branch to test - https://github.com/Fizzadar/pyinfra/compare/master...temp-apt-repo-test - if you wouldn't mind installing that, rerunning the test and pasting the output here that would really help!

**Comment by Fizzadar** [comment]
@questor I've just pushed https://github.com/Fizzadar/pyinfra/commit/b325d715cbe1e1ea12fc5e3ac54589eb749a03e7 to master which correctly adds the semicolons - does this work for you?

**Comment by questor** [comment]
yep, can confirm that it works now with this change on my machine. small sidenote: I had to put another space BEFORE the semicolon in one of my tests I made, your version works on my machine but as I don't understand why I need semicolons it might be a good idea to make a space before the added semicolons just to be sure(tm).

Thanks for fixing it and being responsive, I know it's hard work to maintain opensource projects, you can close this ticket now!

**Comment by Fizzadar** [comment]
The semi-colon explicitly separates the commands - not 100% on why the newline didn't have this effect (it should) but this could well be a difference in shells. See: https://stackoverflow.com/questions/7507038/semicolons-superfluous-at-the-end-of-a-line-in-shell-scripts

So this should be OK now! I'm planning to release this in `0.16` today/tomorrow :)
