### ISSUE TITLE
pyinfra does not handle SSH certificates

### ISSUE THREAD

**Issue by terrorbyte** [Fizzadar/pyinfra#338]
**Describe the bug**
Currently pyinfra doesn't handle [OpenSSH Certificates](https://man.openbsd.org/ssh-keygen#CERTIFICATES). Paramiko does have support for them via [load_certificate](http://docs.paramiko.org/en/stable/api/keys.html#paramiko.pkey.PKey.load_certificate). I have been working on a patch or two for this as it is pretty easy to handle but does require some assumptions and loading of the public key. Do you think this would be better handled via an additional command line flag or by having it be the default behaviour to look for -cert.pub certificates of the given keys? I should note that OpenSSH defaults to searching for those when loading private keys.

I was a bit torn on whether to do this as a bug report or as a feature request.

**To Reproduce**
Generate OpenSSH certificate keys, set up a pki, and attempt to run pyinfra with the -cert.pub signed public keys and observe how they are not loaded. 

**Expected behavior**
Load the certificates and use them when calling paramiko.

**Comment by Fizzadar** [comment]
@terrorbyte this seems reasonable - do you know where OpenSSH looks for these? And is it part of the SSH config?

Should be relatively simple to implement assuming they have expected/known locations and/or explicit SSH config directives.

**Comment by terrorbyte** [comment]
Yes I do, so the lookup logic for OpenSSH is to search for the public key in the same directory path as the loaded private key and it searches for `-cert.pub` and `.pub` [1]. There is the `CertificateFile` directive, but by default if that's not specified in the SSH config it should default to what I stated before. The exact excerpt is [2]:

>If no certificates have been explicitly specified by the CertificateFile directive, ssh will also try to load certificate information from the filename obtained by appending -cert.pub to identity filenames. 

I appreciate you being so responsive to these. Happy to test or give guidance if need be (or patches).

[1] - https://github.com/openssh/openssh-portable/blob/049297de975b92adcc2db77e3fb7046c0e3c695d/ssh-keygen.c#L2453
[2] - https://man.openbsd.org/ssh#i

**Comment by Fizzadar** [comment]
I have now implemented this in https://github.com/Fizzadar/pyinfra/commit/deba79dd1af70a9e88a02c0eadf61f86c79f9c79 + https://github.com/Fizzadar/pyinfra/commit/7f811970abe16ab4242e216c311c19ded646ea29.

**Comment by Fizzadar** [comment]
Now released in `0.16`!
