### ISSUE TITLE
pkg.packages: don't set PKG_PATH on OpenBSD if /etc/installurl exists

### ISSUE THREAD

**Issue by leahneukirchen** [Fizzadar/pyinfra#341]
**Describe the bug**

pkg.packages will compute a default `$PKG_PATH` which has several downsides:
- it uses the default OpenBSD site, which may be slow
- it uses the stable package repo even if the system runs a snapshot
- it behaves differently than just using `pkg_add` on the default install

**To Reproduce**

Simply use `pkg.packages` on a OpenBSD system.

**Expected behavior**

If `/etc/installurl` exists, `pkg.packages` should not initialize `PKG_PATH` but use the default behavior.

**Comment by Fizzadar** [comment]
This is much better, was not aware of `/etc/installurl`! I've updated the operation to check for this in https://github.com/Fizzadar/pyinfra/commit/44af64958224e4e5a941354b33f7ed233a490972, and plan to release `v0.16`  in the coming days.

**Comment by Fizzadar** [comment]
Now released in `0.16`!
