### ISSUE TITLE
Adding a line does not work as expected

### ISSUE THREAD

**Issue by nardusg** [Fizzadar/pyinfra#346]
**Describe the bug**
Adding a line does not work as expected. If I add "AllowUsers nardusg narrem' to end of file it disapear and reapear every time I run the deploy.

**To Reproduce**
files.line(
    {'sshd: Add AllowUsers to sshd_config'},
    '/etc/ssh/sshd_config',
    'AllowUsers nardusg narrem',
    present=True,
)

**Expected behavior**
To add "AllowUsers nardusg narrem" to end of file and keep it there

**Meta**
+ Include output of `pyinfra --support`.
Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.7.6-201.fc32.x86_64-x86_64-with-glibc2.2.5
      Release: 5.7.6-201.fc32.x86_64
      Machine: x86_64
    pyinfra: v0.16
    Executable: /home/nardusg/.local/bin/pyinfra
    Python: 3.8.3 (CPython, GCC 10.1.1 20200507 (Red Hat 10.1.1-1))

+ How was pyinfra installed (source/pip)?
pip3.8

+ Include pyinfra-debug.log (if one was created)
attached
+ Consider including output with `-vv` and `--debug`.
attached

**Comment by nardusg** [comment]
[debug_dubble_secondrun.txt](https://github.com/Fizzadar/pyinfra/files/4869293/debug_dubble_secondrun.txt)
[debug_dubbel.txt](https://github.com/Fizzadar/pyinfra/files/4869294/debug_dubbel.txt)

**Comment by nardusg** [comment]
![Screenshot-2020-07-03-125438-733x770](https://user-images.githubusercontent.com/29011858/86462738-6772aa00-bd2c-11ea-99ec-ddd16430023c.png)

**Comment by Fizzadar** [comment]
I believe this is the same issue as #345; I've just released `0.16.1` which should fix this!

**Comment by nardusg** [comment]
Jip, looks good, getting the right behaviour now :+1:
