### ISSUE TITLE
Add support crontab 'nIcknames'

### ISSUE THREAD

**Issue by SebRut** [Fizzadar/pyinfra#348]
**Is your feature request related to a problem? Please describe.**
I'd like to easily schedule a script at system start independent of the available software. Crontabs `@reboot` special time spec enables me to do this.

**Describe the solution you'd like**
Expand `server.crontab` to support the special nicknames (see "extensions" on this [page](https://linux.die.net/man/5/crontab)).

**Comment by Fizzadar** [comment]
I like this idea 👍.

**Comment by Fizzadar** [comment]
I have now implemented this as a `special_time` argument on the `server.crontab` operation in https://github.com/Fizzadar/pyinfra/commit/0de65ff474be9e52a008f06ce53a10a81397c4a3, released in `0.16.2`!
