### ISSUE TITLE
server.user support public key filenames

### ISSUE THREAD

**Issue by nardusg** [Fizzadar/pyinfra#349]
Hi

Is is possible to do:
    public_keys=['ssh_keys/id_rsa_nar_serv.pub'],

instead of:
    public_keys=['ssh-rsa AAAAB..3NzQ== root@lunarnix'],

Thanks

Nardus

**Comment by Fizzadar** [comment]
👍 this is a nice idea.

**Comment by Fizzadar** [comment]
I have now implemented support for this in https://github.com/Fizzadar/pyinfra/commit/72a0b381a2ae69c33442f3d2c5d1410a10de2281 and released in `0.16.2`.
