### ISSUE TITLE
variable questions ?

### ISSUE THREAD

**Issue by nardusg** [Fizzadar/pyinfra#350]
Hi

Me again.

Question 1:
If I want to use variables, what is the best way to do it? See example below, example below works, is there a better way:

file_version= 'v0.21.5'

files.download(
    {'Download the correct file'},
    'https://github.com//releases/download/%s/somefile' %(file_version),
    '/usr/local/bin/file',
)

Question 2:
Where should all the variables go so that I can use them in my tasks and deploys files ?

Thanks

**Comment by Fizzadar** [comment]
Hi @nardusg! So the recommended way to achieve this would be to store the variables under a group data file, ie similar directoy tree ie:

```py
# deploy.py
from pyinfra import host

files.download('https://github.com//releases/download/%s/somefile' %(host.data.file_version)
```

```py
# group_data/all.py

file_version = 'v0.21.5'
```

Does that help? I'm keen to improve the documentation for this!

Reference: https://docs.pyinfra.com/en/latest/deploys.html#data

**Comment by nardusg** [comment]
Hi

Yes, thanks for the answer. I guess we stuck with this, in ansible I would have replaced the %s with {{ host.data.file_version }} like below:

files.download('https://github.com//releases/download/{{ host.data.file_version }}/somefile'

Just in my view a bit cleaner. But will will work with %s

Thanks

**Comment by Fizzadar** [comment]
If you're using python3 f-strings can be similar!:

```py
files.download(f'https://github.com//releases/download/{host.data.file_version}/somefile')
```

**Comment by nardusg** [comment]
Ok, that works, thanks, will give it a go
