### ISSUE TITLE
gevent dependency should be higher

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#354]
**Describe the bug**

Having older versions of gevent < 1.5 (say, 1.2.2 which is the Ubuntu 18.04 default), the CLI does not work. The current dependency is `gevent > 1`, so the following might happen if one have older versions of gevent:

```
❯❯❯ pyinfra                                                                                    
Traceback (most recent call last):                                                             
  File "/usr/local/bin/pyinfra", line 7, in <module>                                           
    from pyinfra_cli.__main__ import execute_pyinfra                                           
  File "/usr/local/lib/python3.6/dist-packages/pyinfra_cli/__main__.py", line 36, in <module>  
    gevent.signal_handler(signal.SIGINT, gevent.kill)  # kill any greenlets on ctrl+c          
AttributeError: module 'gevent' has no attribute 'signal_handler'                              
```

This is due to #293 but the dependency package version needs to be updated. gevent ==1.2.2 does not have such method.

**Meta**
+ Include output of `pyinfra --support`.
  - pyinfra version: 0.16.1

+ How was pyinfra installed (source/pip)?
  - pip3 install pyinfra

+ gevent:
```
>>> gevent                                                                      
<module 'gevent' from '/usr/lib/python3/dist-packages/gevent/__init__.py'>      
>>> gevent.__version__                                                          
'1.2.2'                                                                         
```

**Comment by Fizzadar** [comment]
Nice catch @wookayin this is very much on me for not considering older gevent versions!

I think I'm going to add a try/except so support for both remains, as otherwise the gevent API has remained stable.

**Comment by Fizzadar** [comment]
Implemented in https://github.com/Fizzadar/pyinfra/commit/85b94f0d9caef0b1d22763371b1279ae2f433944, will release `0.16.2` later today!

**Comment by wookayin** [comment]
Fantastic, looks great to me. Thanks for your fast help!
