### ISSUE TITLE
Directory fact fails on parsing busybox LS 

### ISSUE THREAD

**Issue by Tezar** [Fizzadar/pyinfra#356]
**Describe the bug**
When running directory fact on system with busybox (e.g. Alpine), it will always assume that directory doesn't exists.

**To Reproduce**
Install linux with busy box, collect directory fact on known dir.

**Expected behavior**
Directory should be detected.

**Meta**
Fact will run `ls -ld --time-style=long-iso {0} 2> /dev/null || ls -ldT {0}`, first part will fail since busybox supports only `--full-time`
It will end up running ` ls -ldT {0}` which fails in interesting way. The `-T` flag stands for `--tabsize=COLS`, so the directory param is instead consumed as integer for this flag, and therefore `ls` defaults to current dir. PyInfra still fails to parse its output, since it lacks timezone param
`drwx------    3 root     root          1024 Jul  9 12:27 .`
closest pyinfra expected format
`drwx------    3 root     root          1024 Jul  9 12:27:00 0000 .`

**Comment by Fizzadar** [comment]
I have implemented an immediate fix for this in https://github.com/Fizzadar/pyinfra/commit/dc14bfe3e1f7b0cb8109ffb989c2cefcf45ee49d, released in `0.16.2`.

Also opened #358 for post-v1 investigations!
