### ISSUE TITLE
Documentation for deploys

### ISSUE THREAD

**Issue by Tezar** [Fizzadar/pyinfra#357]
https://docs.pyinfra.com/en/latest/api/deploys.html states that `state` and `host `params follow after the description, when tha actual case is to use them as first params, could be quite confusing.

Also I seem unable to find info about the magic description param, I get it, how it works, but there is no reference in docs that pyinfra will strip it before passing it to my custom operators.

**Comment by Fizzadar** [comment]
@Tezar I completely agree! pyinfra `v1` will deprecate this behavior in favor of a global `name` argument as per https://github.com/Fizzadar/pyinfra/issues/340.

I am hoping to get v1 out in the next few days which should solve this! If you'd like to use this now it can be installed w/`pip install pyinfra --pre --upgrade --upgrade-strategy only-if-needed`.

**Comment by Fizzadar** [comment]
I have now updated the docs to use the new v1 style of writing deploys and plan to release v1 later today.
