### ISSUE TITLE
line() got an unexpected keyword argument 'path'

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#360]
**Describe the bug**

`files.line` does not work as expeced. It throws an error `TypeError: line() got an unexpected keyword argument 'path'`.

I was following the documentation https://docs.pyinfra.com/en/latest/modules/files.html#files-line but it doesn't work.

Isn't it the just basic API :)? I hope there is any test case that covers each of the all APIs.

**To Reproduce**

Deploy:

```python
from pyinfra.operations import files, server

files.line(
    name='test',
    path='/tmp/test',
    line='hello',
)
```

Result:

```
❯❯❯ pyinfra -vv @local t/job.py
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [@local] Connected

--> Preparing operations...
    Loading: t/job.py
--> An unexpected exception occurred:

  File ".../lib/python3.8/site-packages/pyinfra/api/operation.py", line 343, in decorated_func
    commands = unroll_generators(func(
TypeError: line() got an unexpected keyword argument 'path'

--> The full traceback has been written to pyinfra-debug.log
```

**Meta**

pyinfra: v0.16.2 (pip)

**Comment by Fizzadar** [comment]
@wookayin this is due to the `name` kwarg - this requires pyinfra v1 which I'm going to release today. My apologies I jumped the gun on the documentation it seems, will fix that today!

**Comment by wookayin** [comment]
Thanks for letting know of this. I wasn't aware that v1.0 (master/nightly) will be introducing many big changes. I will try the master version as you're going to release v1.0 soon.
