### ISSUE TITLE
Investigate: API and function signature should match for better completion support

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#361]
Programmatic APIs and their python signature do not match because of the use of `@operation` decorators.

For example: `server.shell` has the following prototype/signature [(code)](https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/operations/server.py#L98)

```
shell(state, host, commands, chdir=None)
```

![image](https://user-images.githubusercontent.com/1009873/87112274-631d2400-c239-11ea-94cd-cf557ee8a336.png)

But [the documentation](https://docs.pyinfra.com/en/latest/modules/server.html#server-shell) says 

```
server.shell(commands, chdir=None)
```

which are different. Users are supposed to call like the latter but the python API has a different signature; this confuses users **a lOT**. Please consider matching the signature.

I think we can still implement the logic by dependency injection through decorator; for example, `state=` can become a keyword-only argument with some sentinel objects as default argument.

**Comment by Fizzadar** [comment]
So the issue here is actually both forms are totally acceptable in CLI mode (as of v1/master), with state/host being required for API mode (see [packaging deploys](https://docs.pyinfra.com/en/latest/api/deploys.html).

```py
from pyinfra import host, state
from pyinfra.operations import server


# This is available when executing in API *and* CLI mode
server.shell(state, host, 'echo hiwithstate')

# This is only available in CLI mode, and uses pseudo/magic modules
server.shell('echo hiwithoutstate')
```

I'm keen to keep the CLI shortcut of not including these as it's useful, but it makes it much harder to remove them from intellisense/similar, as this entirely depends on the context. As you say I think the only option here is to make them keyword arguments - the problem is, in API mode, these are required arguments and so this would cause the same issue for people writing API code.

**Comment by wookayin** [comment]
If state and host were keyword arguments, we could satisfy both needs. I think this would be much better (therefore I strongly recommend) because the orderings of positional args do match.

Example:

```
server.shell(commands, chdir=None, *, state=AUTO, host=AUTO)
```

But this is some changes that would break the API signature of all existing methods, so you may want to have these changes before a major release.

**Comment by Fizzadar** [comment]
I have successfully implemented this in a backwards compatible manner in https://github.com/Fizzadar/pyinfra/commit/6f74697e67d43a93c99aa6b8a70da5e9c4390752! Meaning it can be released immediately in v1 and deprecates the old style for proper removal in v2. Operations updated in https://github.com/Fizzadar/pyinfra/commit/a86e5a19fe48e89228f20bd5eec7f408c83d00bb.

**Comment by wookayin** [comment]
I'm very happy we narrowly made it for the major release v1. Thank you very much for considering my suggestions and implementing this *super* fast. This is awesome!
