### ISSUE TITLE
Investigate: Better completion support for `pyinfra.host`

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#362]
`pyinfra.host` are not recognized by LSPs or python completion. It is a pseudo-module defined in `pseudo_modules.py` but language servers (e.g. coc.nvim / vs-code, etc.) cannot recognize the symbol because it is dynamically set-attributed.

A drawback of this is:

```python
>>> from pyinfra import host
>>> host.fact.linux_name
AttributeError: 'NoneType' object has no attribute 'fact'
```

They are only operative when running under pyinfra CLI. This doesn't give users a good completion experience. A better way would be to have a fake/pseudo module in more a static fashion, so that they can pull up a relevant python symbol and hence completions (e.g. [pyinfra.facts.server.LinuxName](https://github.com/Fizzadar/pyinfra/blob/v0.16.2/pyinfra/facts/server.py#L508)).

Fact Docs: https://docs.pyinfra.com/en/latest/facts.html

I have an example only for `host.fact` but all attributes under `host` should be subject to this improvement.

**Comment by Fizzadar** [comment]
This should now be supported after https://github.com/Fizzadar/pyinfra/commit/5d57fe79c80d03913c32b780fe968cd605aff04d! Have also improved the error message when accessing "unset" pseudo modules.

**Comment by Fizzadar** [comment]
Sidenote: does not cover `host.fact`, which I will tackle under another issue.
