### ISSUE TITLE
files.{file,directory} should support Pathlib

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#366]
`pathlib.Path` is a standard library for dealing with path. Currently files operations do not accept Pathlib. It would be great to have the support of Pathlib, as converting `pathlib.Path` via `str(...)` makes the deploy code less concise.

e.g.

```python
files.file(Path("/usr/local/cuda").joinpath("include/cudnn.h"), assume_present=True)
```

**Comment by Fizzadar** [comment]
Excellent idea to support this!

**Comment by Fizzadar** [comment]
Implemented @ https://github.com/Fizzadar/pyinfra/commit/16c80d0a9dc11a6f82c4c9d13551c104ef908d07, will release in `v1` and `v0.16.3` later today.
