### ISSUE TITLE
file.sync does not handle symbolic links.

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#368]
**Describe the bug**

`files.sync(src, dest)` does not work when dest is a symbolc link.

error message:

```
[@local] pyinfra error (operation=...): /tmp/a/symbolic/link/directory exists and is not a directory
```

when `/tmp/a/symbolic/link/directory` points to **a directory**.

**Expected behavior**

It should be able to copy files into `dest` even if `dest` is a symbolic link (to a directory) as rsync does. If it points to a file, should throw an error.

**Meta**
+ Include output of `pyinfra --support`.
  1.0.0.dev2 (master)

**Comment by Fizzadar** [comment]
👍 Seems reasonable to implement - will have it check for symlink and if encountered validate the target is a directory (but continue to upload to the symlink).

**Comment by Fizzadar** [comment]
This should be fixed by https://github.com/Fizzadar/pyinfra/commit/330ee7a1fe22a29da7d8f1c41fd29ac6c8935b7f! Will release in `1.0.3` today/tomorrow!
