### ISSUE TITLE
Homepage uses pre v1 example

### ISSUE THREAD

**Issue by Tezar** [Fizzadar/pyinfra#372]
**Describe the bug**
https://pyinfra.com/ in the quickstart section still uses old arguments passing instead of explicit naming introduced in v1.

**Meta**
Maybe change "'Install iftop" to "Assert iftop installed" to better cross the message of describing the wanted stated in contrast to just remotely blindly running some bash?

**Comment by Fizzadar** [comment]
Thanks for spotting this @Tezar, fixed!
