### ISSUE TITLE
Expose inventory to the deploy

### ISSUE THREAD

**Issue by Tezar** [Fizzadar/pyinfra#373]
**Is your feature request related to a problem? Please describe.**
When setting up master/slave (or broker/workers) architecture, I like to whitelist connections. Currently I have to duplicate definitions in the host.

**Describe the solution you'd like**
Enable access to siblings in the same group, maybe via `host.siblings` to allow something like this
```
generator_pipeline = ["broker", "worker1", "worker2"]

brokers = [
   ("broker", {"allow":"generator_pipeline"},
]
```

or some kind of other reflection to allow accessing inventory

**Comment by Fizzadar** [comment]
@Tezar it should be possible to achieve this using group data files and importing inventory, for example:

```py
# inventory.py
brokers = ["broker"]
workers = ["worker1", "worker2"]
```

```py
# group_data/brokers.py
from pyinfra import inventory
allow = [host.name for host in inventory.get_group('workers')]
```

This is only possible within data files because the inventory has to be fully parsed before it can be used, ie it can't self-reference within the same file. Does this help?

**Comment by Tezar** [comment]
Thanks @Fizzadar , this (or something like this) will work for my use case. 

Actually knowing that I can access inventory in this manner even from deploy solves this, since I can call
`inventory.get_group(host.data.allow)` directly within the deploy file.
