### ISSUE TITLE
Docs: clarify deploy layout mandatory/optional paths

### ISSUE THREAD

**Issue by Tezar** [Fizzadar/pyinfra#374]
**Describe the bug**
[Documentation](https://docs.pyinfra.com/en/latest/deploys.html#layoutl) states basic layout for deployment. Some paths can be however chosen freely (e.g. `inventories`) while others are to be strictly followed (`group_data`, `config.py`)

To add confusion, while there is directory `inventories`, rest of the examples code uses it without specifying path (i.e. `pyinfra inventory.py debug-inventory`) which suggests that pyinfra will always search for the inventory file within the folder, which is not the case. It will lead to fine error message `Could not resolve hostname (inventory.py)`

**Expected behavior**
+ use full path to inventory at least in the "Writing Deploys" section
+ specify which paths are hardcoded and which are optional/best-practice (without testing I am not sure how templates/files dirs behave)

**Comment by Fizzadar** [comment]
Great point @Tezar, this is v.confusing! I've updated the docs to make this more explicit (https://docs.pyinfra.com/en/latest/deploys.html#layout) - I think that explains it properly?
