### ISSUE TITLE
Allow SimpleNamespace types in data files

### ISSUE THREAD

**Issue by harold-b** [Fizzadar/pyinfra#376]
It seems that currently [SimpleNamespace ](https://docs.python.org/3/library/types.html#types.SimpleNamespace) is not parsed as host data. Would it be possible to allow this type? As it simplifies the syntax over dictionaries when defining nested anonymous structures.

**Comment by Fizzadar** [comment]
Added in https://github.com/Fizzadar/pyinfra/commit/c4cdfed62edf63ff810f4b3a583b834b666cede8 and released today in `1.0.3`!

**Comment by harold-b** [comment]
Excellent, thank you!
