### ISSUE TITLE
Add ability for Docker connector to execute on remote machine

### ISSUE THREAD

**Issue by charles-l** [Fizzadar/pyinfra#383]
**Is your feature request related to a problem? Please describe.**

The docker connector is awesome, but only seems to work for the local machine. If I want to start a docker container on a remote machine, I have to use the remote machine connector and execute a "docker run" command through the shell which doesn't leverage the functionality of the existing `@docker` connector.

**Describe the solution you'd like**

Ideally, I'd be able to specify a remote host and a container name to run on that host, something like `@docker/remote.host/container:1.1` (there's probably a better syntax than this).

**Comment by charles-l** [comment]
BTW, if this seems like a feature you'd be willing to include in the project, I'd be interested in implementing it, either by expanding the current docker connector or by adding a new remote-docker connector.

**Comment by Fizzadar** [comment]
This is a really interesting idea! I originally thought it'd just make sense to install `pyinfra` alongside `docker` on the remote machine - but that's less than ideal.

I think a new connector, combining the docker + SSH connectors (`@docker-ssh/remote.host:image:tag` could work?).

**Comment by charles-l** [comment]
OK -- cool, I'll take a stab at implementing this then.

**Comment by Fizzadar** [comment]
Thanks @charles-l! Feel free to ping me or message here if you need a hand w/anything :)

**Comment by charles-l** [comment]
@Fizzadar ok -- finished up a basic draft PR -- had some questions for next steps for you when you get the chance to look it over.
