### ISSUE TITLE
yum/dnf packages are split on the last dash, breaking packages with dashes *in the name*

### ISSUE THREAD

**Issue by alexandrunastase** [Fizzadar/pyinfra#385]
**Describe the bug**
When trying to remove the packages 'vim-enhanced' or 'vim-common' using dnf the removal does not happen.

**To Reproduce**
```
dnf.packages(
    packages=["git","vim-common", "vim-enhanced"],
    present=False,
    sudo=True,
)
```

There is also a failing test in the PR https://github.com/Fizzadar/pyinfra/pull/380 .

**Expected behavior**
Packages 'vim-enhanced' and 'vim-common' are removed

Expected output: 
```
sudo -H -n sh -c 'dnf remove -y git vim-common vim-enhanced' 
```
Actual output:
```
sudo -H -n sh -c 'dnf remove -y git'
```
**Meta**
Discussion and a test : https://github.com/Fizzadar/pyinfra/pull/380

**Comment by FooBarQuaxx** [comment]
Yes, this is because `version_join='-'` [here](https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/operations/dnf.py#L188).
The package name is split on '-' and the second half is treated as the package's version which lead to this bug.

**Comment by Fizzadar** [comment]
Well this is frustrating! Both package names _and_ version use dashes :/

One option is to simply remove support for explicit versions here, but that seems rubbish/not backwards compatible.

That said, I think I'd like to enable support for the following for all package managers (based on https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/operations/util/packaging.py#L52):

```py
apt.packages(
    packages=[('htop', 'version'), ('vim', 'version')],
)
```

Ie passing a tuple `(package_name, package_version)` to specify specific version. This would then support yum/etc where this currently fails.

As for the version joining for yum/dnf packages themselves - perhaps checking the right hand side for one or more numerical characters.

**Comment by FooBarQuaxx** [comment]
@Fizzadar rpm (and so dnf/yum) supports non numeric values for version (eg. my-package-**trunk**, trunk being the version component). Saying that, I think support for specific version is an essential feature for package management and very preferably not solely using the suggested tuple approach but also the current documented inline one.

**Comment by Fizzadar** [comment]
Agreed support for specific versions is absolutely essential - I think inline also. But does pose a problem for yum/dnf, need to have a think about options here!

**Comment by Fizzadar** [comment]
@alexandrunastase this has been fixed by @FooBarQuaxx (thank you!) in https://github.com/Fizzadar/pyinfra/commit/586608a8afe864a496813f733b92335f1f51174b. Tested locally and can remove `vim-common` as expected.

I will release `1.0.4` later today!

**Comment by alexandrunastase** [comment]
@Fizzadar @FooBarQuaxx I tested on my machine and for me it did not work. I also ran the test that I created in this PR https://github.com/Fizzadar/pyinfra/pull/380/files, after I rebased, and it failed (the one with `vim-enhanced` and `vim-common`). 

Verbose output : 

Beginning operation run...
--> Starting operation: Dnf/Packages ("packages=['git', 'vim-enhanced', 'vim-common']", 'present=False')
[@local] >>> sudo -H -n sh -c 'dnf remove -y git'
[@local] Dependencies resolved.

--
Note: All 3 packages were installed before the run
Check the version for pyinfra and it's v1.0.4

**Comment by Fizzadar** [comment]
@alexandrunastase strange - what's the output of  `pyinfra INVENTORY fact rpm_packages`? It _should_ be picking up `vim-common` and `vim-enhanced` as packages.

**Comment by alexandrunastase** [comment]
@Fizzadar Both are listed there, but I would think the problem is not with the fact gathering, but rather with the operation logic, since the test is failing.

Output:
[rpm_packages_output_23_07.txt](https://github.com/Fizzadar/pyinfra/files/4968411/rpm_packages_output_23_07.txt)

**Comment by Fizzadar** [comment]
Thank you for providing that @alexandrunastase, I've not forgotten about this!

**Comment by alexandrunastase** [comment]
@Fizzadar thanks. I really appreciate it. Though I started using Arch for about week, I'll spin up a VM to test on Fedora if there is a fix.

**Comment by Fizzadar** [comment]
I have finally fixed this in https://github.com/Fizzadar/pyinfra/commit/cd3418f18f5ba7fe4666a74ec19384e7caaa935b & updated the test; unfortunately the naming of RPM packages is just too ambiguous!
