### ISSUE TITLE
Home directory is not created with `server.user`

### ISSUE THREAD

**Issue by hoh** [Fizzadar/pyinfra#39]
Using the following states does not result in the home directory being created. The use is created and `/home/deploy` is written in `/etc/passwd`, but the directory is not created.

```python
    server.user(
        'deploy',
        group='deploy',
        ensure_home=True,
    )
```

Using `pyinfra-0.1.dev26` (pip installed) on Ubuntu 16.04 x86_64 in a Linux container.

**Comment by Fizzadar** [comment]
@hoh this _was_ expected behaviour - `ensure_home` only triggered when `home` was explicitly set. I've now changed it to default home to `/home/{name}` in https://github.com/Fizzadar/pyinfra/commit/419df4f9145fc483f4f93d8786dddca94afa8194, so this should now work.

**Comment by hoh** [comment]
Great, 👍
