### ISSUE TITLE
files.line operation should allow use of env vars like $HOME

### ISSUE THREAD

**Issue by cpbrown** [Fizzadar/pyinfra#390]
FindInFile.command in facts/files.py should get the cannonical name of the file so it will match when compared

**Comment by Fizzadar** [comment]
@cpbrown this should be possible by setting `interpolate_variables=True` in the operation (https://docs.pyinfra.com/en/latest/modules/files.html#files-line).

In  `0.x` this was the default, but `1.x` has changed this to require explicit enabling.

**Comment by cpbrown** [comment]
I set interpolate_variables=True and it works!  Thanks.
