### ISSUE TITLE
Interdependent ops about group/user creation

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#394]
A deploy script containing

```
apt.packages(                                                            
    name='Install Docker via apt.',                                      
    packages=['docker-ce', 'docker-ce-cli', 'containerd.io'],            
    update=_add_apt.changed,
)                                                                        

server.group(                                                            
    name='Create docker user group',                                     
    group='docker',                                                      
)                                                                        
```

will fail when docker gets installed, because

- At the moment when facts are gathered, there is no docker installed and therefore no docker group
- After docker installation is done, it tries to do add group, but fails with an error "the group already exists"

Related: https://docs.pyinfra.com/en/latest/deploy_process.html#interdependent-operations

However, creating group shouldn't just fail if exists. the operation is really not idempotent. What is your suggestion on this scenario? Checking operations' precondition in runtime is pretty cumbersome and not very intuitive.

I think this is just only one example, but I believe there are a LOT more similar cases about inderdependent operations because of the fundamental assumption of the execution model.

**Meta**

- pyinfra 1.0.4

**Comment by Fizzadar** [comment]
I believe this is the same as #387, will continue discussion in there!
