### ISSUE TITLE
API change `name` arg

### ISSUE THREAD

**Issue by pylang** [Fizzadar/pyinfra#395]
**Is your feature request related to a problem? Please describe.**

This is a minor observation, but the `name` parameter in operations seems confusing.

Example:

```python
apt.package(
    name="Ensure package is installed"
    ...
)
```

Expecting a name, instead we seem to pass in a phrase or title.  I'm not familiar with conventions, but I wasn't sure what "name" to pass in until I saw examples.

**Describe the solution you'd like**

Since API changes are being considered with v1.1, I suggest changing the name of the parameter `name` to fit its purpose, e.g. `title`, or `comment`, etc.  This may help newcomers infer what should be passed in.

**Comment by Fizzadar** [comment]
To me the argument is simply to "name the operation". I think title/description/comment would all be just as valid too (I considered description but chose name as it's quicker to type). A name can be one or more words and is essentially a form of identifier for a given object (operation call in this case).

Also important to note is its entirely optional to provide the name argument and only serves as a prettified/humanised name for an operation call. Perhaps it could be removed from the examples? The behaviour without still outputs all the relevant information.

As for changing the argument that would be a breaking change (v2) and given the above I don't see any reason to change it, am open to opinions on this for the future (potential to implement a new name for 1.1 with backwards compatibility if there's lots of weight behind it).
