### ISSUE TITLE
0% coverage?

### ISSUE THREAD

**Issue by MartinThoma** [Fizzadar/pyinfra#402]
The first thing I saw when visiting the Github page was "0% coverage". Is this true or is there an issue with the coverage reporting / the badge?

**Comment by Fizzadar** [comment]
Definitely an issue with codecov! Hadn't spotted this it looks awful, will investigate today!

**Comment by Fizzadar** [comment]
Fixed by https://github.com/Fizzadar/pyinfra/commit/441231e55b2f254a951f013e017b084598f81fa2, back to 92% :)

**Comment by MartinThoma** [comment]
Awesome! Thank you :-)
