### ISSUE TITLE
Use of --serial will cause operations to be run twice

### ISSUE THREAD

**Issue by morrison12** [Fizzadar/pyinfra#406]
**Describe the bug**
Use of the --serial option with the CLI will cause all operations to be run twice

**To Reproduce**
pyinfra --serial _inventory_ deploy.py 
**Expected behavior**
Operations run only once.

**Meta**
See "# Default: section of pyinfra/pyinfra.api.operations.py ...

    System: Darwin
      Platform: macOS-10.14.6-x86_64-i386-64bit
      Release: 18.7.0
      Machine: x86_64
    pyinfra: v1.0.4
    Python: 3.8.5 (CPython, Clang 11.0.0 (clang-1100.0.33.17))

**Comment by Fizzadar** [comment]
I've fixed this is in https://github.com/Fizzadar/pyinfra/commit/c66008265dfb67eaff158fcaa0872ac264db3b82! I expect to release this in the next week or so in the upcoming v1.1.

**Comment by Fizzadar** [comment]
I've just released `v1.1.dev0` which fixes this.
