### ISSUE TITLE
Fix docker_ce example

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#408]
Source (thank you @pylang):

https://github.com/Fizzadar/pyinfra/issues/363#issuecomment-660902603

```FYI: one of the examples doesn't work.

examples/docker_ce,py fails quietly - the command runs but nothing is executed. It seems host.fact.linux becomes None and skips the conditional block containing the commands.

Bypassing that, another problem: an error is thrown at the second apt.packages command, requiring a password, but none was asked. I tried the following but nothing works:

> pyinfra @local /path/to/docker_ce.py 
> pyinfra @local /path/to/docker_ce.py use_sudo_password=true
> pyinfra @local /path/to/docker_ce.py --use_sudo_password

A third issue: later host.fact.command("apt-key list") complains that no such fact exists.

UPDATE: the second issue regarding passwords was somewhat resolved adding use_sudo_password=True into the appropriate operation function (in code, not the terminal). See also more insight on env vars in config.py.

apt.key, isn't adding new gpgs when apt-key list is called.

Can confirm other facts are returning None, e.g. linux_id and code_name

The other issues remain.```

**Comment by pylang** [comment]
I've been working with this a lot.  I managed to cobble a work-around (until the next update) if I comment some code out.  Here are the sore spots to help narrow the debugging.  

1. Comment the following, which returns `None`:
```python
    if host.fact.linux_name in {'Ubuntu'}:
```
Temporarily replaced with `if True:

1. Comment the following and hard code the metadata:
```python
    linux_id = host.fact.linux_distribution['release_meta'].get('ID')
    code_name = host.fact.linux_distribution['release_meta'].get('DISTRIB_CODENAME')
```
1. Comment the last line 
```python
    python.call(...) 
```
I vaguely recall the callback throwing an error related to the `command` arg.

**Comment by Fizzadar** [comment]
Fixed by https://github.com/Fizzadar/pyinfra/commit/c0cc3f314b4cfc5c9ed12501065f8ff5afaa3871!

**Comment by pylang** [comment]
I have a modified version of this, but it's close.  Although the task works on my local machine, I get an error when I push to CI.  

At `linux_id = lsb_info["id"].lower()`, it says `lsb_info` is `None`.

At the very least I expected a [dict](https://github.com/Fizzadar/pyinfra/blob/1a32553de0b6bdc949c020c5a953a7638db41b37/pyinfra/facts/server.py#L205).  It might be getting [`None` from the base method](https://github.com/Fizzadar/pyinfra/blob/1a32553de0b6bdc949c020c5a953a7638db41b37/pyinfra/api/facts.py#L90).  Does this need `default = dict`?

As to why it's running ok on my machine and not on CI, i'm not sure.
