### ISSUE TITLE
Allow custom options for apt.packages

### ISSUE THREAD

**Issue by wookayin** [Fizzadar/pyinfra#411]
As reported in https://github.com/sharkdp/bat/issues/938#issuecomment-646745610, apt-install of `bat` and `ripgrep` does not work unless `-o Dpkg::Options::="--force-overwrite"` option is provided:

```
sudo apt install -o Dpkg::Options::="--force-overwrite" bat ripgrep
```

However, [the current apt API](https://docs.pyinfra.com/en/latest/modules/apt.html#apt-packages) does not have a way to provide custom option or flag. It would be great to allow such options.

**Comment by Fizzadar** [comment]
I've implemented this in https://github.com/Fizzadar/pyinfra/commit/ed22d8bf14ecc1847c63285d58c73e0669c44a4f as `extra_install_args`/`extra_uninstall_args` (matching yum/dnf ops); released in 1.1.dev1 in prep for the upcoming 1.1!
