### ISSUE TITLE
Python API documentation

### ISSUE THREAD

**Issue by bronte2k7** [Fizzadar/pyinfra#427]
[problem]
I want to integrate pyinfra into my program. Without using the command line interface.

[decision]
add Python API to run pyinfra without CLI

p.s. sorry for my english

**Comment by bronte2k7** [comment]
It looks like packaging deploys partially answers my question. But the question remains how to use packaging deploys remotely?

**Comment by Fizzadar** [comment]
Hi @bronte2k7! There is an available and stable Python API - see [the `api_deploy.py` example](https://github.com/Fizzadar/pyinfra/blob/master/examples/api_deploy.py).

The documentation doesn't reference this anywhere which is poor, I'm leaving this issue open to track documenting this!

**Comment by bronte2k7** [comment]
Thanks a lot

**Comment by bronte2k7** [comment]
Hi
Please add a description of the API to create inventory. Your example api_deploy.py for vargant and I don't understand how to make inventory for ssh

**Comment by bronte2k7** [comment]
Hi

I do not understand. How can I access the host data?

**Comment by Fizzadar** [comment]
So to access host data you would need to use `host.get_fact`, kinda like:

```py
host = inventory.get_host('my-server.net')
linux_distro = host.fact.linux_distribution
```

Does that help? I'm planning a more tutorial-style API documentation and will be sure to include this kind of information!

**Comment by bronte2k7** [comment]
> So to access host data you would need to use `host.get_fact`, kinda like:
> 
> ```python
> host = inventory.get_host('my-server.net')
> linux_distro = host.fact.linux_distribution
> ```
> 
> Does that help? I'm planning a more tutorial-style API documentation and will be sure to include this kind of information!

Works))) Great, thanks.

**Comment by bronte2k7** [comment]
Hi. I'm with a new question

I need to get the data of the host that is currently being processed. Is it possible to get the current host?

**Comment by Fizzadar** [comment]
API now has _some_ documentation. Will create a new issue to track improving it.
