### ISSUE TITLE
Add support for specifying port when using ssh.keyscan

### ISSUE THREAD

**Issue by kvold** [Fizzadar/pyinfra#428]
I'm trying to add a server to known_hosts which uses a different port than 22 using ssh.keyscan. It fails when I specify hostname="servername:port", which I see pyinfra translates to "ssh-keyscan servername:port" on the server.

A "port=" option in pyinfra ssh.keyscan which would translate to  "ssh-keyscan -p port " would be useful (for me at least :).

**Comment by Fizzadar** [comment]
Excellent idea @kvold! Will replicate for all of the `ssh.*` operations too :)

**Comment by Fizzadar** [comment]
Switching back to original here - will add the port arg to `ssh.keyscan` for `v1.1.2` and do the other ones later as requires other changes + deprecations for arg consistency!

**Comment by Fizzadar** [comment]
Port argument added in https://github.com/Fizzadar/pyinfra/commit/fd5cba1880ad306162c71fb7269d45b416428d56 which I'm about to release in `v1.1.2`.
