### ISSUE TITLE
new states BaseStateCallback

### ISSUE THREAD

**Issue by bronte2k7** [Fizzadar/pyinfra#436]
[problem]
i want to log all states. But missing state: host connection error

[decision]
add new state: host_connect_error

**Comment by bronte2k7** [comment]
[problem]
some manipulations need to be done before connecting to the host

[decision]
add new state: preparation

**Comment by Fizzadar** [comment]
I have implemented both of these in https://github.com/Fizzadar/pyinfra/commit/b102d3f031149b307380f419c3b3c96e91eb8343, pending the `v1.2` release in the coming days!
