### ISSUE TITLE
Fact to detect GUIs

### ISSUE THREAD

**Issue by pylang** [Fizzadar/pyinfra#441]
**Is your feature request related to a problem? Please describe.**

Sometimes I deploy GUI-based packages, e.g. `meld`, `gufw` to GUI-based machines.   However, on occasion I will test on non-GUI servers, where installing these GUI packages isn't needed. 
 I would like to skip them. 

There seem to be ways to [detect whether a GUI is installed (on Linux)](https://askubuntu.com/questions/918097/how-can-i-detect-whether-ubuntu-server-has-a-gui-installed).  With this, a user can skip installing certain operations.

**Describe the solution you'd like**

A fact to automate GUI detection.

```python
if host.fact.has_gui():
    apt.packages(
        name="Install gui-based packages.",
        packages=[
            "gufw",
            "meld",
            ...
        ]
    )
```

**Comment by bronte2k7** [comment]
Hi.
Use this fact.

```python
class HasGui(FactBase):
    default = list
    command = 'ls /usr/share/xsessions/*.desktop || true'

    def process(self, output):
        return output

```

P.S. I checked for ubuntu

**Comment by Fizzadar** [comment]
This looks like a good addition I'll add it in for 1.2!

**Comment by pylang** [comment]
Seems to be working so far on Debian with desktop environments.  I've also tested it on Ubuntu server (no GUI), which also works.  One exception is, if you happen to have left over `*.desktop` files, you get a false positive and it doesn't work.   This exception can be simulated on Ubuntu server, install gui-based program, remove it, and run the fact. The fact will return True.  

I can work with it since I'm now aware to keep `/usr/share/xsessions/` clean, but other people may not know to look there, resulting in a future bug.

**Comment by Fizzadar** [comment]
This is frustrating - I can't think of  any way to handle that situation. I'm going to add a warning when using the fact to highlight this possible problem (unblocking v1.2 release). Can revisit if a better solution comes to light!

**Comment by pylang** [comment]
The [link](https://askubuntu.com/a/918103) mentioned about shows some Linux-fu that suggests verifying the programs are actually installed, and not just leftover.  It's a bit beyond me right now.

**Comment by Fizzadar** [comment]
There's also [this answer](https://unix.stackexchange.com/a/522282) which likely picks up GUI "flags" in more systems. Will see if I can get the combination of the two working such that the underlying binary presence is checked.

**Comment by bronte2k7** [comment]
Check installed packages. But it is safer

**Comment by Fizzadar** [comment]
Chosen the more explicit route looking for exact binaries - more painful to maintain but should be rock solid; https://github.com/Fizzadar/pyinfra/commit/057c90a9985ce16e9e0e7e42de2f37dffb761969! 1.2 coming up v.shortly!
