### ISSUE TITLE
FactBase types of incoming and outgoing data

### ISSUE THREAD

**Issue by bronte2k7** [Fizzadar/pyinfra#445]
[problem]
get the raw output of the command. To process data inside a function

[decision]
add the ability to get raw data in str type

**Comment by bronte2k7** [comment]
[problem]
sometimes it is necessary for a fact to return a string and not a list

[decision]
add the ability to return not only a list or dictionary but also a string

**Comment by Fizzadar** [comment]
Hi @bronte2k7 - this should already be possible, the `process` method is passed the `stdout` lines but can return anything it wants; ie:

```py
class StringFact(FactBase):
    command = 'some-command'
    default = six.text_type  # until py2 is dropped
    
    def process(self, output):
        return '\n'.join(output)
```

**Comment by bronte2k7** [comment]
Hi @Fizzadar
I believed that the function works differently, and this caused me confusion. Thanks

**Comment by Fizzadar** [comment]
I've now updated the facts API doc to make this more clear + include an example! https://github.com/Fizzadar/pyinfra/commit/e73711ad20a89b956622b8579a2b002463b1de16
