### ISSUE TITLE
CLI docs/help: make discovery easier

### ISSUE THREAD

**Issue by mjmare** [Fizzadar/pyinfra#448]
Hi

For a beginner it is hard to find out which operations are avalable. It would be nice if the CLI help (--help) would show all available operations. 

Also some commands are operations (debug-inventory), some are options (--debug-facts). Also some options shown when using --help are deprecated (--debug-data).

**Comment by Fizzadar** [comment]
👍 agreed this needs tidying - I think all non-deprecated options should be shown, and deprecated ones hidden.

**Comment by pylang** [comment]
I imagine this would be a matter of exposing the Operations Index to the cli. 

On a related note, after you [make a custom operation](https://docs.pyinfra.com/en/latest/api/operations.html), how do you access it in a deploy file?  Unlike `FactBase`, which adds subclasses to a Facts Index,  operations seem to be capture via the `@operation` decorator.   However, I can't access it from `pyinfra.operations`.

The Operations Index seems more buried than the Facts Index.  Harder to know how to reach custom objects.

**Comment by Fizzadar** [comment]
Apologies I never saw this message! I think this has been answered elsewhere @pylang!?

Regarding the original issue - this is cleaned up and pending released in `1.4`!

**Comment by mjmare** [comment]
No prob. Thanks for fixing it.

**Comment by pylang** [comment]
Yes, my question has been [resolved](https://stackoverflow.com/questions/64165507/how-to-include-custom-modules-in-pyinfra).  Thanks.  I guess this can be closed now.

**Comment by Fizzadar** [comment]
This has now been released in `v1.4`!
