### ISSUE TITLE
Example is incorrect

### ISSUE THREAD

**Issue by mjmare** [Fizzadar/pyinfra#449]
Example on https://docs.pyinfra.com/en/1.x/modules/python.html is not correct:

**hello** should be hello

host.run_shell_command args are not correct. I could not figure out the correct ones (maybe improve docs?).

TIA

PS It was not obvious to me how to run a command on a server and inspect its output.  As you probably have guessed, I'm just checking out PyInfra (I'm probably trying to act contrary to PyInfra's intended use). The example above seems to provide the answer (which seems pretty complex for such a simple task). 

PS2 I found the corresponding code on GH: https://github.com/Fizzadar/pyinfra/blob/master/examples/python.py
This code still fails with:
```
Unexpected error in Python callback: TypeError("run_shell_command() got multiple values for argument 'command'",)
```

PS3 From the example https://docs.pyinfra.com/en/1.x/examples/dynamic_execution_deploy.html I gather that I should just pass the command string (not host and state) and not a kwarg.

**Comment by Fizzadar** [comment]
Thank you for adding this issue @mjmare, the example is incorrect and I'll get that fixed! You just neeed to pass the command + kwarg here, no `state` or `host` objects required.

Regarding the running command + getting output, I'll try to make this more obvious - there's two options here, using facts (`host.fact.command('my-command')` will immediately give the output and then running inside a function as you've described, where the output is collected during the execution phase. The [deploy process doc](https://docs.pyinfra.com/en/1.x/deploy_process.html) explains the process and difference between the phases. I need to tweak the getting started guide to highlight this better.

**Comment by mjmare** [comment]
Thx, I was already investigating Facts to do this.  Stil a bit puzzled on how to create a Fact. Examples like host.fact.linux_name are accessed like properties. However when I created my own Fact: 
```
from pyinfra.api import FactBase

class SwapIsOn(FactBase):
    '''
    Returns True is Swap is on
    '''

    def command(self):
        return 'swapon --show'

    def process(self, output):
        return len(output)>0
```
and using it like:
```
print(f'Fact={host.fact.swap_is_on}')
```
yields:
```
Fact=<function get_host_fact.<locals>.wrapper at 0x10d162ee0>
```
Turns out I need to do:
```
print(f'Fact={host.fact.swap_is_on()}')
```

Don't know why this is. Should the custom fact be registered in some way?

**Comment by Fizzadar** [comment]
So this is  because the `command` is a method - if you set `command = 'swapon --show'` as a class level  attribute, it'll return without execution.

The majority of  facts don't need a dynamic command, so basically have a hard-coded command attribute, but some facts (file, etc) do need a dynamic command, and so have a `command` method  instead.

I realise this is a bit confusing! I must improve the documentation on https://docs.pyinfra.com/en/1.x/api/facts.html to highlight this. Post that, I'm thinking about overhauling the fact system entirely in v2 when it comes :)

**Comment by Fizzadar** [comment]
I've now fixed the example issue in https://github.com/Fizzadar/pyinfra/commit/270ba458a9ab36b8c82eb32b36d6d2d0127ebd3e and updated/expanded the facts doc @ https://github.com/Fizzadar/pyinfra/commit/e73711ad20a89b956622b8579a2b002463b1de16.
