### ISSUE TITLE
Test existing keys in apt.key

### ISSUE THREAD

**Issue by pylang** [Fizzadar/pyinfra#454]
**Is your feature request related to a problem? Please describe.**

In the [docker example](https://github.com/Fizzadar/pyinfra/blob/1a32553de0b6bdc949c020c5a953a7638db41b37/examples/docker_ce.py#L50) I noticed some tests to avoid rewriting keys that already exist.  Perhaps these tests can be folded into the `apt.key()` operation.

**Describe the solution you'd like**

Add a keyword to ensure the key exists, e.g.

```python
apt.key(
    name="Add the Docker apt gpg key if we need to",
    src="https://download.docker.com/linux/ubuntu/gpg",
    exists=True,
)
```

If the key exists, don't  bother adding the key.  Otherwise, add the key.

You can then write cleaner code without the testing logic.

**Comment by Fizzadar** [comment]
The checking/implementation of this was actually completed in https://github.com/Fizzadar/pyinfra/commit/776b35c81ef936df661ffc09543a05d674ded093#diff-73efd0d9dd8a7cadf7e9e96baa7ef1cfe911a3d1b1cf14b009667cd64f232748! I need to fix the example to remove the now pointless check.

**Comment by Fizzadar** [comment]
Manual check removed in https://github.com/Fizzadar/pyinfra/commit/3f3cda771c3f2c1fc483946d7d408bee42e998d1 :)
