### ISSUE TITLE
Can't use sudo=True from operation called from other operation

### ISSUE THREAD

**Issue by amagee** [Fizzadar/pyinfra#456]
I want to make a deploy where some of the commands use sudo and some don't.

My `config.py`:

```
USE_SUDO_PASSWORD = True
```

If I call a command with `sudo=True` from top level (ie. my `deploy.py` looks like this):

```
from pyinfra.operations import apt
apt.update(sudo=True)
```

it works as expected.

However if my deploy looks like this:

```
from operations.myapt import do_apt_update
do_apt_update()
```

(and `operations/myapt.py` looks like this:)

```
from pyinfra.api import operation
from pyinfra.operations import apt

@operation
def do_apt_update(state=None, host=None):
    yield apt.update(sudo=True)
```

then the command is not executed with sudo (even though in both cases pyinfra does ask for my sudo password).

I've noticed that in `pyinfra/api/operation.py`, the `sudo` argument is stripped from the kwargs:

```
        # Get the meta kwargs (globals that apply to all hosts)
        op_meta_kwargs = pop_global_op_kwargs(state, kwargs)
```

and then the stripped kwargs are passed through to the command:

```
        # If this op is being called inside another, just return here
        # (any unwanted/op-related kwargs removed above).
        if state.in_op:
            return func(*args, **kwargs) or []
```

however I don't understand any more to debug further.

Am I right in expecting that this should work, or am I misunderstanding something?

**Comment by Fizzadar** [comment]
Hi @amagee! So the global arguments are all removed by the `@operation` decorator - the correct way to use sudo here would be when calling the operation itself; ie:

```py
from operations.myapt import do_apt_update
do_apt_update(sudo=True)
```

This is done such that nested operations respect the users arguments for sudo/etc.

Alternatively, setting `SUDO = True` in the config will work. Currently setting `USE_SUDO_PASSWORD` does not also set `sudo` (I am going to add a warning for this).

Going to also update the packaging deploys documentation to document how nested operations work and cannot be passed global arguments.

**Comment by amagee** [comment]
Oh ok, so it's not possible to have a command that's called without sudo call a command with sudo?

Is supporting this on the roadmap at all? I can work around it but it would definitely be a nice to have - for me it's a pretty typical pattern for an operation to want to `sudo apt-get install` some stuff and then do some user-space stuff that uses the packages.

If it's not supported, having an error thrown if you try to use `sudo=True` from a non-sudo operation would save a lot of time.

**Comment by Fizzadar** [comment]
So an operation is meant to be a single unit of work - such that `sudo` should be applied for every command within the operation. For your use-case I would recommend using the [`@deploy` decorator](https://docs.pyinfra.com/en/1.x/api/deploys.html) which does allow calling multiple operations each with different global arguments.

Excellent point about rasing an error when this happens (around https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/api/operation.py#L184-L187), it's totally hidden from the user; I'm going to implement that!

**Comment by Fizzadar** [comment]
I have now implemented the check and exception for this in https://github.com/Fizzadar/pyinfra/commit/adaa80f37c6b0bd116698377beb9cfe4f6603dbf.
