### ISSUE TITLE
Offer unified operations

### ISSUE THREAD

**Issue by iredmail** [Fizzadar/pyinfra#458]
If your deploy needs to support different linux distributions at the same time, e.g. CentOS and Ubuntu, you have to write 2 tasks like:

```
yum.packages(...)
apt.packages(...)
```

pyinfra should offer one operation named, for example, `package`, it detects distro and use correct operation like `yum.packages` and `apt.packages` to handle it. then you just need one task for different linux/bsd distributions:

```
package(...)
```

Same as the `package` module in Ansible: https://docs.ansible.com/ansible/2.9/modules/package_module.html

Also, please offer a `service` operation too to handle service start/stop/restart/enable/disable. Same as the `service` module in ansible: https://docs.ansible.com/ansible/2.9/modules/service_module.html

**Comment by Fizzadar** [comment]
@iredmail 👋 - there's the [`server.service`](https://docs.pyinfra.com/en/1.x/operations/server.html#server-service) operation which handles the service aspect here!

Definitely like idea of the same for packages, `server.packages` perhaps!

**Comment by iredmail** [comment]
Cool. 👍

Better mention this in document page of each “xxx.packages” module.
