### ISSUE TITLE
operation chdir parameter not accepting dynamic value

### ISSUE THREAD

**Issue by christian-thieme** [Fizzadar/pyinfra#466]
**Describe the bug**

Using a dynamic value in the chdir parameter is not working.

**To Reproduce**

create an inventory with multiple hosts

servers = [
    'a.domain.com,
    'b.domain.com,
    'c.domain.com',
]

from pyinfra import host
from pyinfra.operations import server

server.shell(
    chdir=f"/var/www/{host.name}",
    commands=f"echo Hello {host.name}!"
)

the command is created correctly, the chdir parameter seems to by fixed after the first execution

**Expected behavior**

The chdir parameter should accept a dynamic value

**Meta**

Was working with v1.1.2, broken since v1.2.

**Comment by Fizzadar** [comment]
@christian-thieme this is a side-effect of making `chdir` a global argument. I think this perfectly highlights the need for the global arguments to work on a per host, rather than per-operation, level 👍.

**Comment by Fizzadar** [comment]
This has now been implemented in https://github.com/Fizzadar/pyinfra/commit/895bd023faf661a167dff960f567b1e4b229060a and released in v1.3!
