### ISSUE TITLE
Support for su w/o sudo

### ISSUE THREAD

**Issue by reuleaux** [Fizzadar/pyinfra#48]
I have been running simple pyinfra deploy scripts like this one
for doing my daily apt-get update/upgrade combo:

apt.py

```python
from pyinfra.modules import apt
from pyinfra.modules import server

apt.update()
apt.upgrade()
server.shell(commands="apt-get -y autoremove")
```

initially I always ran it as the root user, like so

```bash
pyinfra -i somehost --user root -v apt.py
```

ie. using simply somehost's hostname, and taking advantage of the
fact, that I have an ssh-agent running, ie. I am not asked for a password or
key phrase (whether it's a good thing to allow ssh root access, is another question,
but it certainly makes my adminstrator's life easier).

Then I got bored of always having to type --user root, so instead I introduced
simple inventories (one for each host I use so far):

somehost.py

```python
HOSTS = [
    ('somehost', {'ssh_user': "root"})
]
```

that way I can just call:

```bash
pyinfra -i somehost.py apt.py -v
```

I guess it makes sense to have ssh_user set as "root", because *most* of
the operations I do on a host require root permissions.

However not always: a similar emacs/cask update I typically do as user rx
(rather then root):

```bash
cd ~/.emacs.d && EMACS="emacs" ~/cfg/e/cask/bin/cask outdated
```

Now what I would like is: just call

```bash
pyinfra -i somehost.py -v cask.py
```

given that I have prepared a similar cask deploy script:

cask.py

```python
from pyinfra.modules import server

server.shell(chdir="~/.emacs.d"
            , commands='EMACS="emacs" ~/cfg/e/cask/bin/cask update'
            , user="rx")
```

Ie. I want to just use the somehost.py inventory, and have my cask.py deploy script
figure out, that a certain task requires user "rx" only.
Note that this is my wishlist thinking: the server.shell command doesn't
currently have a user=... parameter

I do not want to have to think for every little task:

* oh, apt operations require root permissions, thus call them with an inventory
  that has 'ssh_user': "root"

* cask operations I do as user "rx", thus call them with another inventory
  that has 'ssh_user': "rx"

Rather I want the individual deploy scripts/operations therein be able
to take a user param.

currently what I am resorting to in the case of cask above:
```python
def caskUpdate():
    server.shell(commands='su - rx -c "cd ~/.emacs.d && EMACS=emacs ~/cfg/e/cask/bin/cask update"')

caskUpdate()
```

which is not really the style I want to write my operations.

Maybe this is possible with pyfinfra alreay, and I just haven't discovered it yet?

Also on my wishlist: maybe create a pyinfra mailing list, where I could ask these
kind of user questions ?

Not that in (haskell) propellor, which I am also using, this
is possible: the userScriptPropterty
there takes among other params a User param, cf eg.

http://hackage.haskell.org/package/propellor-3.0.5/docs/Propellor-Property-Cmd.html#v:userScriptProperty

ie. in propellor I just have

```haskell
caskUpdate :: Property UnixLike
caskUpdate = propertyList "cask update" $ props
             & userScriptProperty (User "rx")
             [
              "(cd ~/.emacs.d && EMACS=\"emacs\" ~/cfg/e/cask/bin/cask update)"
             ] `assume` MadeChange
```

Thanks for creating pyinfra in the first place, and keep up your good work.

**Comment by Fizzadar** [comment]
@reuleaux this _should_ already be supported by the `sudo_user` parameter. If the SSH user is root then simply adding that should work, eg:

```py
from pyinfra.modules import server

server.shell(
    chdir="~/.emacs.d" ,
    commands='EMACS="emacs" ~/cfg/e/cask/bin/cask update',
    sudo_user="rx"
)
```

Alternatively you can connect with a non-root user and use `sudo=True` on root-specific operations...

**Comment by reuleaux** [comment]
Hm, thanks for your your fast reply, but sorry: this doesn't work for me:


simplified cask.py deploy script shows where I am and who I am:

    def PwdWho():
        server.shell(chdir="~/.emacs.d"
                     , commands='echo $(pwd); echo $(whoami)'
                     , sudo_user="rx")


    PwdWho()

now calling that shows that root is used (given that I have
'ssh_user': "root" in my inventory for mirabelle as explained in detail before):

    $ infra.sh -i mirabelle.py cask.py -v
    cd /home/rx/cfg/infra...
    pyinfra -i mirabelle.py cask.py -v...

    ### Welcome to pyinfra

    --> Connecting to hosts...
        [mirabelle] Connected

    --> Building deploy scripts...
        [mirabelle] Ready

    --> Proposed changes:
        [mirabelle]	Operations: 1	    Commands: 1

    --> Beginning operation run...
    --> Starting operation: Server/Shell ('chdir=~/.emacs.d', 'commands=echo $(pwd); echo $(whoami)')
    [mirabelle] >>> sh -c 'cd ~/.emacs.d && (echo $(pwd); echo $(whoami))'
    [mirabelle] /root/.emacs.d
    [mirabelle] root
        [mirabelle] Success

    --> Results:
        [mirabelle]	Successful: 1	    Errors: 0	    Commands: 1/1

    <-- Thank you, goodbye



I should add that 

 * I am using pyinfra from debian testing

     rx@mirabelle ~ $ pyinfra --version
     pyinfra-0.1.dev26
     rx@mirabelle ~ $ 

 * and that I don't have sudo installed, and that I don't intend to:
   I have lived happily with just normal ssh access, if needed 
   I use: "ssh -l root ..."

**Comment by reuleaux** [comment]
My workaround with `su - rx...` seems to work somehow,
although I find it confusing that eg. `pwd` shows that I am in
~rx, whereas `echo $(pwd)` suggests that I am in `~root`,
and likewise for `whoami`:


file `cask.py`

```python
def pwdWho():
    server.shell(
        commands='su - rx -c "cd ~/.emacs.d && pwd; echo $(pwd); whoami; echo $(whoami)"'
    )

pwdWho()
```


```bash
$ pyinfra -i softland.py cask.py -v

### Welcome to pyinfra

--> Connecting to hosts...
    [softland] Connected

--> Building deploy scripts...
    [softland] Ready

--> Proposed changes:
    [softland]	Operations: 1	    Commands: 1

--> Beginning operation run...
--> Starting operation: Server/Shell ('commands=su - rx -c "cd ~/.emacs.d && pwd; echo $(pwd); whoami; echo $(whoami)"',)
[softland] >>> sh -c 'su - rx -c "cd ~/.emacs.d && pwd; echo $(pwd); whoami; echo $(whoami)"'
[softland] /home/rx/.emacs.d
[softland] /root
[softland] rx
[softland] root
    [softland] Success

--> Results:
    [softland]	Successful: 1	    Errors: 0	    Commands: 1/1

<-- Thank you, goodbye

```


Your suggested `sudo_user` solution does not work for me at all:
(haven't configured sudo on my system, and don't
intend to, as explained before), shows only `root` ie.:


```python

def pwdWho2():
    server.shell(
        chdir="~/.emacs.d"
        , commands='pwd; echo $(pwd); whoami; echo $(whoami)'
        , sudo_user="rx"
    )

pwdWho2()

```


```bash
~/cfg/infra $ pyinfra -i softland.py cask.py -v

### Welcome to pyinfra

--> Connecting to hosts...
    [softland] Connected

--> Building deploy scripts...
    [softland] Ready

--> Proposed changes:
    [softland]	Operations: 1	    Commands: 1

--> Beginning operation run...
--> Starting operation: Server/Shell ('commands=pwd; echo $(pwd); whoami; echo $(whoami)', 'chdir=~/.emacs.d')
[softland] >>> sh -c 'cd ~/.emacs.d && (pwd; echo $(pwd); whoami; echo $(whoami))'
[softland] /root/.emacs.d
[softland] /root/.emacs.d
[softland] root
[softland] root
    [softland] Success

--> Results:
    [softland]	Successful: 1	    Errors: 0	    Commands: 1/1

<-- Thank you, goodbye

~/cfg/infra $
```

**Comment by Fizzadar** [comment]
My apologies @reuleaux, I misunderstood. Supporting plain `su` is definitely a feature I'd like to implement, such that any command can be used with something like `su='myuser'`...

**Comment by Fizzadar** [comment]
Hi @reuleaux this should now be possible using the `su_user` kwarg or `--su-user` CLI arg (on any operation). For example:

```
pyinfra -i ubuntu14.pyinfra --run server.shell 'whoami' --su-user vagrant --user root -v
...
--> Starting operation: Server/Shell (u'whoami; echo $HOME',)
[ubuntu14.pyinfra] >>> su vagrant -c 'whoami; echo $HOME'
[ubuntu14.pyinfra] vagrant
[ubuntu14.pyinfra] /home/vagrant
...
```

Added in https://github.com/Fizzadar/pyinfra/commit/7b14d6c49c5197ad0c6894dd868bafc81719eb0f

**Comment by reuleaux** [comment]
Nick - OK thanks a lot, will get to try that out, sooner or later ie.:
* having installed pyinfra from debian testing currently I will get it eventually
  automatically
* if I can make some time, I will want to install pyinfra by hand,
  to get it sooner
