### ISSUE TITLE
Wrong documentation on pacman.packages operation

### ISSUE THREAD

**Issue by jprltsnz** [Fizzadar/pyinfra#484]
**Describe the bug**
Documentation of `v1.2.1` and current `HEAD` for pacman.packages state that:
```
upgrade: run pacman -Syu before installing packages
```
packages calls the upgrade operation which is: 
```
@operation
def upgrade(state=None, host=None):
    '''
    Upgrades all pacman packages.
    '''

    yield 'pacman --noconfirm -Su'
```
this runs `pacman -Su` and not `pacman -Syu` as stated on the docs

**Expected behavior**
This isn't much of a problem since `pacman.packages(packages, update=True, upgrade=True)`. is equivalent to running `pacman -Syu` before installing the packages, but the documentation should be changed to reflect this or make upgrade imply an update. (I 'm not sure which one you would rather, so I opened an issue instead of a PR.)

**Comment by Fizzadar** [comment]
Finally got around to this! Fixed by https://github.com/Fizzadar/pyinfra/commit/f90c8c38bee5ed2afa10ad053a2695c15d469edd (https://docs.pyinfra.com/en/latest/operations/pacman.html).
