### ISSUE TITLE
Documentation for git.bare_repo operation is missing

### ISSUE THREAD

**Issue by stchris** [Fizzadar/pyinfra#488]
**Describe the bug**
I provided a PR for creating bare git repos in #465, which was merged and I can see the code in master, but it's not in the release notes and the operation doesn't show up in the docs. I believe I missed to add a changelog entry as well as something to bring in the documentation.

**To Reproduce**

* go to https://docs.pyinfra.com/en/1.x/operations/git.html
* instructions for the operation `git.bare_repo` should be there, but aren't

**Expected behavior**
Documentation should be present.

**Meta**

**Comment by Fizzadar** [comment]
Hi @stchris! The major branch docs only update on actual release so it matches `pip install...`; the master docs are under latest and showing, ie: https://docs.pyinfra.com/en/latest/operations/git.html#git-bare-repo.

On my todo list is to (re)add a version switcher to make this more obvious.

**Comment by stchris** [comment]
Ah I see, cheers. I did seem to break the formatting there unfortunately. Maybe this bug should track that instead?

**Comment by Fizzadar** [comment]
This is now released in v1.3!
