### ISSUE TITLE
Help & Support Link is Broken

### ISSUE THREAD

**Issue by relaxdiego** [Fizzadar/pyinfra#495]
**Describe the bug**
https://docs.pyinfra.com/page/support.html is returning a 404

**To Reproduce**
Go to https://github.com/Fizzadar/pyinfra/issues/new/choose and choose "Help & Support"

**Expected behavior**
Something Help-y and Support-y would appear on my browser.

**Comment by Fizzadar** [comment]
@relaxdiego thank you for spotting this! I've now restored that page redirect so it's working as expected again :)
