### ISSUE TITLE
Provide a way to expose facts from external packages

### ISSUE THREAD

**Issue by sprat** [Fizzadar/pyinfra#498]
**Is your feature request related to a problem? Please describe.**
I've started implementing some custom operations and facts for my deployments. However I didn't found a way to expose my custom facts to pyinfra. I mean, the facts are available when they are imported in the deploy files, but they are not executed in `pyinfra inventory all-facts` for example.

**Describe the solution you'd like**
Use some python entrypoints maybe, so that libraries can declare there own facts classes?

**Comment by sprat** [comment]
Ok, I found a way by importing the facts in the `config.py` file. Maybe this could be documented?

**Comment by Fizzadar** [comment]
Yep I think adding a note about `config.py` working for this to the [writing facts page](https://docs.pyinfra.com/en/1.x/api/facts.html) is a good idea!

**Comment by sprat** [comment]
I guess the solution proposed in #491 would be a nice way to solve the problem, with an explicit import of the fact class somewhere in the operation or deploy.

**Comment by Fizzadar** [comment]
Explicit importing of facts has now been released in `v1.4`!
