### ISSUE TITLE
Facts don't take keyword arguments (wrapper() got an unexpected keyword argument 'name')

### ISSUE THREAD

**Issue by Raboldar** [Fizzadar/pyinfra#506]
**Describe the bug**
When trying to use the function : host.fact.find_in_file(name, pattern), I get the  wrapper() got an unexpected keyword argument 'name' error.

**To Reproduce**
Steps to reproduce the behavior (include code & usage example):
```
from pyinfra import host

join_command = host.fact.find_in_file(                                 
    name='~/generated/file',
    pattern='
      )  
```
**Expected behavior**
Accept the given arguments, open the mentioned file and then return the text that corresponds to the pattern.
**Meta**
+ Include output of `pyinfra --support` : 
```
--> Support information:
    System: Linux
      Platform: Linux-5.9.0-kali4-amd64-x86_64-with-glibc2.31
      Release: 5.9.0-kali4-amd64
      Machine: x86_64
    pyinfra: v1.3
    Executable: /home/ionut/psud-k8s-operator/venv/bin/pyinfra
    Python: 3.9.1rc1 (CPython, GCC 10.2.0)

```
+ How was pyinfra installed (source/pip)?: pip
+ Include pyinfra-debug.log (if one was created): None was created.
+ Consider including output with `-vv` and `--debug`. 
```
    exec(PYTHON_CODES[filename], data)
  File "pyinfraOPS/addMember.py", line 18, in <module>
    deploy_worker()
  File "pyinfraOPS/k8sAddNewMember/addWorkerNode.py", line 40, in deploy_worker
    join_command = get_join_as_worker()
  File "pyinfraOPS/k8sAddNewMember/addWorkerNode.py", line 66, in get_join_as_worker
    join_command = host.fact.find_in_file(
TypeError: wrapper() got an unexpected keyword argument 'name'

```

**Comment by Fizzadar** [comment]
Hi @Raboldar! This is happening because facts, unfortunatelty, don't accept keyword arguments - so if you switch to `host.fact.find_in_file('~/generated/file', 'pattern')` it'll work as expected. I would like to change/fix this as part of https://github.com/Fizzadar/pyinfra/issues/491!

**Comment by Raboldar** [comment]
I see, I will use it accordingly. It's a really nice tool, highly extensible and easy to use ! :)

**Comment by Fizzadar** [comment]
This is now supported in `v1.3.3`! (Implemented in https://github.com/Fizzadar/pyinfra/commit/3e83c96dcd0e7cc5762649cf1bd08b41da0a7cfd).
