### ISSUE TITLE
Add `path` fact (brew operations fail due to missing path on macOS by default)

### ISSUE THREAD

**Issue by taranlu-houzz** [Fizzadar/pyinfra#507]
**Describe the bug**
Currently, all `brew` operations (or at least, I would assume all) fail on macOS because the `PATH` does not contain `/usr/local/bin` by default ( I could have sworn this used to work in the past?). The default path that I get with `pyinfra <host> exec -- env` is `PATH=/usr/bin:/bin:/usr/sbin:/sbin`.

I don't think this is due to a change with my setup/environment.

**To Reproduce**
Steps to reproduce the behavior (include code & usage example):
Basic deploy that fails:
```
from pyinfra.operations import brew


brew.packages(
    name="Test install",
    packages=["tree"],
    latest=True,
    update=True,
)

```

Failed run:
```
❯ pyinfra inventories/----.py --limit ---- deploys/tasks/base/simple.py --debug
    [pyinfra_cli.main] Checking potential directory: deploys/tasks/base
    [pyinfra_cli.main] Setting directory to: deploys/tasks/base
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...
    [pyinfra_cli.inventory] Looking for group data in: deploys/tasks/base/group_data/all.py
    [pyinfra_cli.inventory] Looking for group data in: deploys/tasks/base/group_data/<inventory file>
--> Connecting to hosts...
    [pyinfra.api.connectors.ssh] Connecting to: ---- ({'allow_agent': True, 'look_for_keys': True, 'hostname': ----, 'timeout': 10})
    [----] Connected
    [pyinfra.api.state] Activating host: ----

--> Preparing operations...
    Loading: deploys/tasks/base/simple.py
    [pyinfra.api.operation] Adding operation, {'Test install'}, opOrder=(8,), opHash=bd05d67789318d253923550b574ee43b70bbb955
    [pyinfra.api.facts] Getting fact: brew_packages (ensure_hosts: (Host(----),))
    [pyinfra.api.connectors.ssh] Running command on ----: (pty=False) sh -c '! command -v brew > /dev/null || (brew list --versions)'
    [pyinfra.api.connectors.ssh] Waiting for exit status...
    [pyinfra.api.connectors.ssh] Command exit status: 0
    [pyinfra.api.facts] Loaded fact brew_packages
    [----] Ready: deploys/tasks/base/simple.py

--> Proposed changes:
    Groups: ----
    [----]   Operations: 1   Commands: 2

--> Beginning operation run...
--> Starting operation: Test install
    [pyinfra.api.operations] Starting operation Test install on ----
    [pyinfra.api.connectors.ssh] Running command on ----: (pty=None) sh -c 'brew update'
    [pyinfra.api.connectors.ssh] Waiting for exit status...
    [pyinfra.api.connectors.ssh] Command exit status: 127
    [----] sh: brew: command not found
    [----] Error
    [pyinfra.api.state] Failing hosts: ----
--> pyinfra error: No hosts remaining!
```

Adding `shell_executable="bash -l"` allows the deploy to work properly.

Also wondering: Is it possible to run the `brew` operations directly from the CLI in an adhoc manner? I tried `pyinfra <host> brew update` but that did not work.

**Expected behavior**
Not sure what the best way to deal with this would be, especially since macOS and Linux have slightly different configurations for `brew` by default. Maybe handle the expected case for each platform and then also add param to set the "brew install location" or something like that? Could also potentially get around this by modifying the environment. The `env` global params works for this, but is there a way to append to the `PATH` without fully overwriting the value?

**Meta**
+ Include output of `pyinfra --support`.
```
❯ pyinfra --support
--> Support information:
    System: Darwin
      Platform: Darwin-18.7.0-x86_64-i386-64bit
      Release: 18.7.0
      Machine: x86_64
    pyinfra: v1.3
    Executable: /Users/----/.local/bin/pyinfra
    Python: 3.7.8 (CPython, Clang 10.0.1 (clang-1001.0.46.4))
```
+ How was pyinfra installed (source/pip)?
Installed via `pipx`

**Comment by Fizzadar** [comment]
@taranlu-houzz are you connecting to the Mac instance via SSH? I've been testing brew locally (using `@local`) which does work but has the full path from my login shell.

I've encountered very similar issues with CentOS before which in some versions doesn't have `/usr/local/bin` or `/usr/local/sbin` in the default path - ultimately this isn't something `pyinfra` can fix itself. It should be possible to "fix" by overriding the `PATH` variable by setting `env={'path': '/usr/local/bin'}` or similar.

Running them via the CLI is possible: `pyinfra host brew.update`, for example (the [docs have some more in depth examples of this](https://docs.pyinfra.com/en/1.x/cli.html#executing-ad-hoc-operations) too).

**Comment by taranlu-houzz** [comment]
Hmm, I see. Yeah, I am connecting via ssh. Seems like it would be helpful to have a dedicated `path` fact, as well as the ability to append to ENV var, as opposed to completely overriding it.

For now, I think I will just add a custom fact to get the `PATH` and then use `env={"PATH": f"/usr/local/bin:{path_fact}"}` or something to that effect.

Thanks for the info on CLI use. I think I was getting confused with the way facts vs other operations are called (e.g. `pyinfra <host> fact <fact name>` vs `pyinfra <host> operation_cat.name`).

**Comment by Fizzadar** [comment]
`path` fact is an excellent idea to enable extending it 👍

**Comment by Fizzadar** [comment]
I've added the new `server.Path` fact in https://github.com/Fizzadar/pyinfra/commit/962fac8a63fe49972bcefa10b5645cb4722e51e4, pending `1.4` release shortly.

**Comment by Fizzadar** [comment]
This has now been released in `v1.4`!

**Comment by maxexcloo** [comment]
Sorry to bump this but I'm having this problem - would someone be able to give me a code example of how it should work?

Currently trying to run like this:

```
from pyinfra import host, local
from pyinfra.operations import apt, brew, server

if host.data.get("type") == ("debian" or "ubuntu"):
    apt.update(name="Update apt repositories", _sudo=True)

    apt.upgrade(
        name="Upgrade apt packages and remove unneeded dependencies",
        auto_remove=True,
        _sudo=True,
    )

    server.shell(
        name="Autoremove apt",
        commands=["apt autoremove"],
        _sudo=True,
    )

    server.shell(
        name="Clean apt",
        commands=["apt clean"],
        _sudo=True,
    )

if host.data.get("type") == "mac":
    brew.update()
```

**Comment by taranlu-houzz** [comment]
@maxexcloo This is a similar example of fact usage (I don't know if things have changed in newer versions of pyinfra, since I wrote this quite a while ago):
```python# ==Standard Library==
# ==Standard Library==
import pathlib

# ==Site-Packages==
from pyinfra import host
from pyinfra.facts import server
from pyinfra.operations import files


####################################################################################################
# Main
####################################################################################################


if host.get_fact(server.Kernel) in ("Darwin", "Linux"):
    p3d_path = pathlib.Path(host.data.hz_p3d_dir_path)

    # Root p3d dir
    files.directory(
        name=f"Ensure that: {p3d_path} exists.",
        path=p3d_path,
        user=host.get_fact(server.User),
        _sudo=True,
        _use_sudo_password=True,
    )
```

**Comment by geerlingguy** [comment]
Just wanted to drop another reference here, as I was working on adding the Homebrew path on my Mac as well. It's in the global system path, so I wasn't sure why it wasn't picked up over SSH via pyinfra.

```python
    server.shell(
        name="Build llama.cpp",
        commands=[
            "cd {}/llama.cpp && cmake -B build {}".format(working_dir, llama_cpp_build_opts),
            "cd {}/llama.cpp && cmake --build build --config Release -j {}".format(working_dir, num_cores)
        ],
        _env={"PATH": "/opt/homebrew/bin:$PATH"}
    )
```

Or, installing packages via Homebrew on a Mac:

```python
if host.get_fact(Os) == 'Darwin':
    brew.packages(
        name="Ensure prerequisites are installed (macOS).",
        packages=[
            "screenfetch",
            "stress-ng",
            "btop",
        ],
        _env={"PATH": "/opt/homebrew/bin:$PATH"}
    )
```

Alternatively, if you'd like to add homebrew's bin path to your SSH environment on a Mac running SSH...

```
# Inside /etc/ssh/sshd_config set:
PermitUserEnvironment PATH

# Restart SSH
sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

# Inside `~/.ssh/environment` add:
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin
```

This option could add security risk on a shared system, but should be fine in most cases. Certainly keeps my multi-platform pyinfra code cleaner.
