### ISSUE TITLE
Would be really helpful to have a backup option for several of the file.* operations

### ISSUE THREAD

**Issue by taranlu-houzz** [Fizzadar/pyinfra#510]
**Is your feature request related to a problem? Please describe.**
It would be very helpful if it was possible to "force through" some file operations that would normally fail by allowing them to backup the affected file/dir and then proceed. For example, when using `file.link` sometimes the `path` specified may already exist, but it may not be a link which causes the operation to fail. In such a scenario, it would be nice to have the option to move the blocking file/dir/link to a backup and then proceed with the link operation as intended.

I feel like this would streamline a lot of processes, and since it is an "opt-in" situation, it should not surprise the user.

**Describe the solution you'd like**
- Add a parameter `backup` that indicates that if the target path already exists, it should be moved to a backup location and the operation should proceed as though the path did not exist in the first place.
  - Would also be nice to have params that can be used to modify the way things are backed up:
    - `backup_postfix`: A postfix string to be appended to the backup path (e.g. ".bak").
    - `backup_dir`: A path to the directory where the backed up file/dir should be moved to help avoid cluttering the working directory if many files are backed up (e.g. by default use `./bak/`).
    -  `backup_timestamp`: Append a timestamp to the path (e.g. `2021-01-06_10:56:23`).

**Comment by Fizzadar** [comment]
👍 I'm a big fan of this idea @taranlu-houzz!

**Comment by Fizzadar** [comment]
Finally released this in v1.5!
