### ISSUE TITLE
git.config operation fails for empty global settings

### ISSUE THREAD

**Issue by aj-fuentes** [Fizzadar/pyinfra#511]
**Describe the bug**
When calling `git.config` operation to setup a *global* property AND no `.gitconfig` file exists, it fails with `"fatal: unable to read config file '/home/user/.gitconfig': No such file or directory"`.
This does not match git behaviour.

**To Reproduce**
`pyinfra host git.config "user.name" "bob"`

**Expected behavior**
If the global config file does not exists, it should create it and set the specified config, as `git config` would do.

**Meta**
+ Include output of `pyinfra --support`. 
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.4.0-59-generic-x86_64-with-glibc2.29
      Release: 5.4.0-59-generic
      Machine: x86_64
    pyinfra: v1.3
    Executable: /home/user/.local/bin/pyinfra
    Python: 3.8.5 (CPython, GCC 9.3.0)

+ How was pyinfra installed (source/pip)?
   pip
   
**Comments**
Issue comes from:
https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/operations/git.py#L44
https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/facts/git.py#L24
`git config --global -l` fails when no global config file is found, from here the fact/operation fails.

**Comment by Fizzadar** [comment]
Nice catch, @aj-fuentes - can fix this by first checking for the presense of the/a global config file.

**Comment by aj-fuentes** [comment]
@Fizzadar yes, I was thinking of something like that... but according to git [docs](https://git-scm.com/docs/git-config#Documentation/git-config.txt---global) there are two places for this global file. Maybe trying the command first and checking the return code would work. Git returns one file it expected, which we could `touch`, and continue like on current implementation.

**Comment by Fizzadar** [comment]
I believe the simplest fix for this is simply to ignore/tolerate the failure; checking for all the files will become unncessarily complex - I've pushed this in https://github.com/Fizzadar/pyinfra/commit/6013c813a8eeef63be8c610b76b5dac642b3a7dd which should fix the issue, pending release in `1.3.2` tomorrow!

**Comment by Fizzadar** [comment]
Now released in `v1.3.2`!
