### ISSUE TITLE
Group data should respect __all__

### ISSUE THREAD

**Issue by Tezar** [Fizzadar/pyinfra#521]
**Describe the bug**
When trying to import some modules in the "group_data/all.py", pyinfra will try to include them when building host data. Which in turn breaks `debug-inventory` as modules are not serializable into text. Adding ` __all__` doesn't work.

**To Reproduce**
Try to import module and then call `debug-inventory`

**Expected behavior**
Host data includes only exported variables and/or debug print handles non-json-friendly values gracefully.

**Comment by Fizzadar** [comment]
Thanks for spotting this @Tezar; I've fixed the two different issues here:

- Handle printing out module objects (for `debug-inventory`): https://github.com/Fizzadar/pyinfra/commit/520328c694c556a6f2caaf087b15b098ada39cd0
- respect any defined `__all__` in group data: https://github.com/Fizzadar/pyinfra/commit/8cb8f660412562de7cc88078ccc96fd5f15598f3

Aiming to release these in `v1.3.5` this weekend!

**Comment by Fizzadar** [comment]
Now released in `v1.3.5`!
