### ISSUE TITLE
server.crontab fails if there is no existing crontab

### ISSUE THREAD

**Issue by taranlu-houzz** [Fizzadar/pyinfra#523]
**Describe the bug**
If there is no existing crontab for the user on the host (e.g. someone ran `crontab -r`) then the `server.crontab` operation will fail.

**To Reproduce**
See above.

**Expected behavior**
I would expect a new crontab to be created with the specified job listing from the `server.crontab` operation.

**Meta**
+ Include output of `pyinfra --support`.
```
❯ pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Darwin
      Platform: macOS-10.14.6-x86_64-i386-64bit
      Release: 18.7.0
      Machine: x86_64
    pyinfra: v1.3.5
    Executable: /Users/----/.virtualenvs/05-hz-pyinfra-d0Faa_8y-py3.9/bin/pyinfra
    Python: 3.9.1 (CPython, Clang 10.0.1 (clang-1001.0.46.4))
```
+ How was pyinfra installed (source/pip)? Virtualenv via `poetry`

**Comment by Fizzadar** [comment]
Thanks for spotting this @taranlu-houzz; it's a bug in the `crontab` fact that incorrectly errors when there is no existing `crontab`; fixed in https://github.com/Fizzadar/pyinfra/commit/77232297fc3bbce9c90ede3599863b3283a8d848 and released just now in `v1.3.6` :)
