### ISSUE TITLE
macOS os_version fact reports the version of the Darwin kernel (instead of the macOS version)

### ISSUE THREAD

**Issue by taranlu-houzz** [Fizzadar/pyinfra#531]
**Describe the bug**
This technically isn't a bug, but basically, the `os_version` fact grabs the kernel version instead of the OS version, which is different on macOS. I think it is probably more likely that a user would want to get the macOS version, since that information might be used to construct a url for a file download, for example.

**To Reproduce**
`pyinfra <host> fact os_version`

**Expected behavior**
I think it would be more helpful to get the macOS version, maybe via `system_profiler SPSoftwareDataType | awk '/System Version/ {print $4}'` although not sure if using `awk` is the best option.

**Comment by taranlu-houzz** [comment]
Using `sw_vers` could also work.
```
❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G14033
```

**Comment by Fizzadar** [comment]
I think this is a bug - `os_version` should definitely return the MacOS, not Darwin kernel, version. I'm also going to add an explicit `kernel_version` fact which will return the Darwin version.

**Comment by Fizzadar** [comment]
Update - don't want to break anything here - better safe than sorry so I'm going to:

- deprecate `os` and `os_version` facts and rename to `kernel` / `kernel_version`
- add a new `macos_version` fact

**Comment by Fizzadar** [comment]
I have added the new fact in https://github.com/Fizzadar/pyinfra/commit/f15c30e89a066baf5f9755b62de66d891ea56cf8 & renamed/deprecated the others in https://github.com/Fizzadar/pyinfra/commit/57da13fcb986b245e6755e1ead7226b324c3d366, pending `1.3.7` release shortly!
