### ISSUE TITLE
Would be nice to be able to add empty spacing via server.crontab

### ISSUE THREAD

**Issue by taranlu-houzz** [Fizzadar/pyinfra#532]
**Is your feature request related to a problem? Please describe.**
A crontab is difficult to parse visually when it does not have any empty lines (especially when long commands cause wrapping to occur). Searching works well enough, but sometimes it is nice to be able to peruse the crontab via visually distinct chunks. 

**Describe the solution you'd like**
I think this would be possible, since it seems like the crontab operation is already tracking the comment as well as the job.
- Add a flag to the `server.crontab` operation that allows the user to specify whether there should be a blank line before, after, or both before and after the task (and comment).
- If a comment is present, put the blank line above the comment to keep it together with the job it goes with.

The goal would be to allow for this sort of formatting in the created crontab:
```cron

# pyinfra-name=Do job A
*/15 * * * * /usr/local/bin/A

# pyinfra-name=Do job B
*/30 * * * * /usr/local/bin/B

```

**Comment by Fizzadar** [comment]
This is much neater, added in https://github.com/Fizzadar/pyinfra/commit/6a535b4751be87795e653343a35f34c50c72476a!
