### ISSUE TITLE
Support OpenRC

### ISSUE THREAD

**Issue by Gaming4LifeDE** [Fizzadar/pyinfra#538]
**Is your feature request related to a problem? Please describe.**
Alpine packages are supported through apk, but you can't manage system services on Alpine Linux yet.

**Describe the solution you'd like**
Just an operation "openrc". I'd like to help but I have no idea how to write something like this...

**Comment by Fizzadar** [comment]
👍 totally agree this is much needed.

**Comment by Fizzadar** [comment]
Finally released this in v1.5!
