### ISSUE TITLE
Possible improvement for global "env" parameter

### ISSUE THREAD

**Issue by taranlu-houzz** [Fizzadar/pyinfra#541]
**Is your feature request related to a problem? Please describe.**
Currently, the `env` global param prepends the env dict keys to the front of the commands to be run. This can cause issues if the command happens to use a pipe, since the modified environment will only apply to the first command.

**Describe the solution you'd like**
- I think it would make sense to modify `env` to prepend `KEY1=VALUE1; KEY2=VALUE2; <etc>` instead, so that the environment would apply to the later commands as well.
- It might also make sense to add a new `env_export` param as well, that would use `export KEY1=VALUE1; <etc>`, so that if the command happens to spawn a subshell, the environment would also be passed on.

**Comment by Fizzadar** [comment]
I think `export` is a suitable change here - the `env` argument is expected to apply to everything within the given operation so I think this is a sensible change to make more-expected behaviour.

**Comment by Fizzadar** [comment]
I've made the switch to use `export` in https://github.com/Fizzadar/pyinfra/commit/d761cef197dc1c6d0fc9226b7c80520683bbecc7 and released this in `v1.3.8`!
