### ISSUE TITLE
brew packages fact ignores certain packages

### ISSUE THREAD

**Issue by morrison12** [Fizzadar/pyinfra#542]
**Describe the bug**
The brew packages fact omits certain installed packages, e.g. python.
This is due to them having "special" characters in their package name.
Other packages (e.g. openssl, gtk) are also affected

**To Reproduce**
`brew list --versions | grep python`
gives the following:
```
python@2 2.7.17_1
python@3.8 3.8.8_1
python@3.9 3.9.2_1
```
yet `pyinfra @local fact brew_packages 2>&1 | grep -A2 python ` gives no output

**Expected behavior**
python should show up in the fact output as follows (+/- specific version and what is installed):
```
        "python@2": [
            "2.7.17_1"
        ],
--
        "python@3.8": [
            "3.8.8_1"
        ],
--
        "python@3.9": [
            "3.9.2_1"
        ],
```

**Meta**
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Darwin
      Platform: macOS-10.14.6-x86_64-i386-64bit
      Release: 18.7.0
      Machine: x86_64
    pyinfra: v1.3.6
    Executable: /Users/james/.virtualenvs/macos-setup/bin/pyinfra
    Python: 3.9.2 (CPython, Clang 11.0.0 (clang-1100.0.33.17))

**Comment by Fizzadar** [comment]
Nice spot @morrison12; will get this corrected!

**Comment by Fizzadar** [comment]
This is now fixed in https://github.com/Fizzadar/pyinfra/commit/b2734797f9395056663176e8e14c2686db948bf6 and releasd in `v1.3.8`!
