### ISSUE TITLE
python.call and sudo=True not cooperating

### ISSUE THREAD

**Issue by romanchyla** [Fizzadar/pyinfra#544]
**Is your feature request related to a problem? Please describe.**
Run shell command on the host dynamically with sudo

**Describe the solution you'd like**

First of all, thank you for pyinfra! It makes devops so much fun and productive.

I am very new so likely not seeing the full picture, I'd like to add a GPG key like so

` curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
`

the problem is the `sudo` after the pipe (also, gpg becomes interactive when the file already exists -- so I must detect the state dynamically)

I tried the following:

```python
def add_key(state, host, username=None):
    import os
    if not os.path.exists('/usr/share/keyrings/docker-archive-keyring.gpg'):
        """  """
        status, stdout, stderr = host.run_shell_command(
            'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg',
            #sudo=True
        )
        print(''.join(stderr))
        assert status is True  # ensure the command executed OK

python.call(
    name='Add GPG key (if not exists)',
    function=add_key,
    sudo=True
)
```

results in:

```
gpg: can't create '/usr/share/keyrings/docker-archive-keyring.gpg': Permission deniedgpg: no valid OpenPGP data found.gpg: dearmoring failed: Permission denied(23) Failed writing body
```
with `sudo=True` in the `host.shell_command` it says `sudo: a password is required`

Yes I know not how to pass it in (`python.call` is ran with sudo after all)

I tried various variations, this one will work the first time:

```
server.shell(
            commands=['curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'],
            sudo=True)
```

But if the file already exists; it will result in error (as gpg starts talking):

if I do:

```python
def addk(state, host):
    server.shell(
        commands=['curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'],
        sudo=True)

python.call(
    name='Add GPG key (if not exists)',
    function=addk,
    sudo=True
)
```

then it fails:

```
    Traceback (most recent call last):
  File "/dvt/workspace/projects/it/python/lib/python3.6/site-packages/pyinfra/api/operations.py", line 120, in _run_server_op
    status = command.execute(state, host, executor_kwargs)
  File "/dvt/workspace/projects/it/python/lib/python3.6/site-packages/pyinfra/api/command.py", line 141, in execute
    return self.function(state, host, *self.args, **self.kwargs)
  File "dev_environment.py", line 65, in addk
    sudo=True)
  File "/dvt/workspace/projects/it/python/lib/python3.6/site-packages/pyinfra/api/operation.py", line 262, in decorated_func
    host_op_hashes = state.meta[host]['op_hashes']
KeyError: None
```
Not sure how to proceed; any help would be great

**Comment by Fizzadar** [comment]
Hi @romanchyla! I'm glad you're enjoying using `pyinfra` that's fantastic to hear :)

Operation functions don't work within Python callbacks, so in this case simply doing the following should work:


```py
server.shell(
    commands=['curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'],
    sudo=True,
)

```

To address the file already existing error, I'd recommend using the [`file` fact](https://docs.pyinfra.com/en/1.x/facts/files.html#file), so you could do:

```py
from pyinfra import host
from pyinfra.operations import server

if not host.fact.file('/usr/share/keyrings/docker-archive-keyring.gpg'):
    server.shell(
        commands=['curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'],
        sudo=True,
    )
```

This should get you up and running!

Regarding the final error - it's totally unhelpful and I'm going to handle this case and output something more useful!

**Comment by romanchyla** [comment]
awesome! thank you very much @Fizzadar

apropos the error messages - I really like that I can see the code and what is going on (stacktrace), and that we are talking Python, it is so much easier to make sense of what is happening (as opposed for - lets' say - Ansible hiding it behind the abstraction). I'm sure there is value in both, but just wanted to say that with pyinfra I can be productive immediately and it is so much more fun :)
