### ISSUE TITLE
OSError: No such private key file when using OPENSSH PRIVATE KEY

### ISSUE THREAD

**Issue by gnat** [Fizzadar/pyinfra#548]
So this took a few hours for me to figure out, and wanted to post the solution online.

Basically paramiko doesn't support openssh private key format before version 2.7.

Solution A: Ensure paramiko is at least version 2.7 
`pip3 install paramiko --upgrade`  

Solution B: Convert your private key to PEM format (usable by paramiko <=2.6)
`ssh-keygen -p -m PEM -f ./your_private_key`

You're welcome.

**Comment by gnat** [comment]
Would be very cool to simply bump the minimum version of paramiko to 2.7 in pyinfra but that's up to @Fizzadar

**Comment by Fizzadar** [comment]
I think bumping the required  version is the ideal solution - however it's technically a breaking change 😬! I'm going to leave this issue here while I figure out how to handle this, perhaps a warning until pyinfra 2.x is the best approach (ie warn if we fail to load a key explaining to upgrade paramiko).

**Comment by Fizzadar** [comment]
Implemented the warning in https://github.com/Fizzadar/pyinfra/commit/6347e352a3b6ed0dc038e50c9ded52af75ae8b40 (and fixed the general not found vs. invalid key error message), released in `1.3.9` just now!

**Comment by gnat** [comment]
Great. Thanks @Fizzadar

**Comment by Fizzadar** [comment]
It has occurred to me that bumping the minimum paramiko version from 2.2 to 2.7 isn't a breaking change, not sure what I was thinking originally; [this semver issue explains it well](https://github.com/semver/semver/issues/148), so will be bumping this in 1.4!

**Comment by gnat** [comment]
Nice one @Fizzadar !
