### ISSUE TITLE
Associated group_data will not load if inventory file has extra "." in it.

### ISSUE THREAD

**Issue by gnat** [Fizzadar/pyinfra#549]
**Describe the bug**
This works. Can refer to group_data variables inside jobs using `host.data.variable`.
`group_data/development.py`
`inventories/development.py`

This does not work. `host.data.variable` not found.
`group_data/git.site.com.py`
`inventories/git.site.com.py`

**Expected behavior**
Extra "." characters shouldn't break this functionality.

**Comment by Fizzadar** [comment]
Nice  spot @gnat! I've fixed this  in https://github.com/Fizzadar/pyinfra/commit/8060f1d1579e1a1f4b694af35eb464977092b336 which is now released in `v1.3.8` :)
