### ISSUE TITLE
MySQL user fact errors after initial creation

### ISSUE THREAD

**Issue by blarghmatey** [Fizzadar/pyinfra#552]
**Describe the bug**
When using the `mysql.user` operation it fails after the initial run due to a bug in the use of `MaskedString` for the password in the fact execution. Because the password is marked as a MaskedString [here](https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/facts/mysql.py#L30) that parameter gets rendered as `'***'`because of the `get_masked_string` function [here](https://github.com/blarghmatey/pyinfra/blob/master/pyinfra/api/command.py#L70). It seems like that is intended to only be called to print the value to the output, but it is also being used to construct the mysql command line, resulting in an output like:

```
[66.228.34.34] >>> sh -c '! command -v mysql > /dev/null || (mysql -u"root" *** -hlocalhost -P3306 -Be '"'"'SELECT * FROM mysql.user'"'"')'
[66.228.34.34] ERROR 1049 (42000): Unknown database '***'
```

**To Reproduce**
Steps to reproduce the behavior (include code & usage example):
To reproduce, use the `mysql.user` operation and pass the `mysql_password` parameter and then execute the deploy twice.

**Expected behavior**

The expectation is that the deploy can be executed an arbitrary number of times and the fact will perform the intended lookup to determine if the user already exists.

**Meta**
+ Include output of `pyinfra --support`.
```
--> Support information:
    System: Linux
      Platform: Linux-5.11.5-1-MANJARO-x86_64-with-glibc2.33
      Release: 5.11.5-1-MANJARO
      Machine: x86_64
    pyinfra: v1.3.7
    Executable: /home/tmacey/code/boundlessnotions/config-management/.venv/bin/pyinfra
    Python: 3.9.2 (CPython, GCC 10.2.0)
```
+ How was pyinfra installed (source/pip)? pip
+ Include pyinfra-debug.log (if one was created)
+ Consider including output with `-vv` and `--debug`.

**Comment by Fizzadar** [comment]
Have now released this fix in `1.3.9`!
