### ISSUE TITLE
winrm connector is broken

### ISSUE THREAD

**Issue by mfrg** [Fizzadar/pyinfra#553]
## Describe the bug
The winrm connector appears to be broken, I can not run any commands via the connector.  It appears make_windows_command() is getting unexpected arguments via **command_kwargs from run_shell_command() in the winrm connector.

## To Reproduce
Try to run any command via winrm and you will see:
`TypeError: make_win_command() got an unexpected keyword argument 'use_sudo_password'
2021-03-16T12:42:44Z <Greenlet at 0x7fb062873290: _run_server_op(<pyinfra.api.state.State object at 0x7fb0628423d0>, Host(@winrm/10.10.10.10), '784a97bf1955d5f7a2b9dd6c1e371e17b73c42bc')> failed with TypeError`

This is happening on the latest v1.3.8 release as well as the several prior releases.

## Expected behavior
The command completes successfully and returns valid output.  The fix may be as easy as enumerating the additional kwargs in run_shell_command and ignoring them.  

https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/api/connectors/winrm.py#L105

## Meta
+ Include output of `pyinfra --support`.
+ How was pyinfra installed (source/pip)?
+ Include pyinfra-debug.log (if one was created)
+ Consider including output with `-vv` and `--debug`.

**Comment by Gaming4LifeDE** [comment]
Are you using `use_sudo_password` anywhere? It's complaining that you gave it this parameter, which is does not understand.

**Comment by mfrg** [comment]
Nope, this is a fresh v1.3.8 install trying the examples @ https://docs.pyinfra.com/en/1.x/connectors.html#winrm with zero other configuration.

**Comment by Gaming4LifeDE** [comment]
Can you show me your inventory?

**Comment by mfrg** [comment]
There is no inventory, it's just specifying a host on the cmd line like in those examples.

**Comment by mfrg** [comment]
The issue could be that use_sudo_password is one of the stock auth kwargs (https://github.com/Fizzadar/pyinfra/blob/ba4990f142e8945e4c3a5f539bb63b2436e9bbb2/pyinfra/api/operation_kwargs.py#L4) so when the executor_kwargs for the op are created at https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/api/operations.py#L81 it gets included all the time and is then not enumerated and ignored in the winrm run_shell_command method like other kwargs.

**Comment by Fizzadar** [comment]
Thanks for spotting & investigating this @mfrg! I believe the fix will be to capture the argument @ https://github.com/Fizzadar/pyinfra/blob/master/pyinfra/api/connectors/winrm.py#L105.

I can get that sorted out over the next few days. Also want to look at properly testing the winrm connector to prevent issues like this going forward!

**Comment by mfrg** [comment]
Thanks @Fizzadar, when you dig in you will find that the combined output format for winrm is not correct either -- combined output is being returned as a list not a list of stdout/stderr tuples which is what is expected (which will break facts and probably other things I don't know about),  there is also a small issue with the string command formatting but these are all relatively minor to fix.

**Comment by Fizzadar** [comment]
I've fixed the kwarg issue in https://github.com/Fizzadar/pyinfra/commit/34de33653d827cc468c1d0d35aa06eb3f2164ac7 and also the combined output in https://github.com/Fizzadar/pyinfra/commit/52af5843695c97d5389db1a6a6056ddb137795ef (as well as some more cleanup commits). And have added https://github.com/Fizzadar/pyinfra/issues/556 to track adding proper tests for the connector!

**Comment by mfrg** [comment]
Awesome, I'll see if I can test it out shortly.  I'd also like add some [minor] additional protocol support in the connector, I can send you over a PR for that if you are up for it.

**Comment by Fizzadar** [comment]
@mfrg sounds good; PR's very welcome it'd be fantastic to expand the winrm functionality in pyinfra :)

**Comment by Fizzadar** [comment]
Have now released those fixes in `1.3.9`!
