### ISSUE TITLE
Add support for grant option and TLS settings in MySQL

### ISSUE THREAD

**Issue by blarghmatey** [Fizzadar/pyinfra#555]
## Is your feature request related to a problem? Please describe
There is currently no interface for setting the `WITH GRANT OPTION` suffix to permissions statements, though the `mysql_user_grants` fact does expose that information. There is also no option for appending any TLS suffix parameters to user creation (e.g. `REQUIRE SSL`). There is the escape hatch of executing arbitrary SQL but it doesn't benefit from the MySQL facts that the user and grants functions use.

## Describe the solution you'd like
It would be great to add grant option and tls_option parameters to the `mysql.privileges` and `mysql.user` operations.

**Comment by Fizzadar** [comment]
This will make a great addition to the mysql operation :+1:

**Comment by Fizzadar** [comment]
Now released (at last) in v1.5.
