### ISSUE TITLE
Stopping/starting postgresql service

### ISSUE THREAD

**Issue by giuppep** [Fizzadar/pyinfra#575]
## Is your feature request related to a problem? Please describe
The current implementation of `systemd.service` is unable to stop `postgresql` (at least in my case). The reason is that the `postgresql.service` service has status `active (exited)` and hence `pyinfra` thinks the service is stopped already.

## Describe the solution you'd like
Some possible solutions:
- have the possibility of "force" run a command, so that in this case it will stop the service regardless of the status.
- have ad-hoc operations in the `postgresql` operations to start/stop the service.

Happy to help if you think this may be useful.

**Comment by Fizzadar** [comment]
@giuppep this sounds like a bug in the `server.SystemdSstatus` fact, I think anything `active (exited)` should be considered running. Will take this opportunity to look at all the statues systemd might use as well.

**Comment by Fizzadar** [comment]
Fixed this in https://github.com/Fizzadar/pyinfra/commit/a54ac6f07849054ccf35700771d6e15186a80e33; now released in `v1.4.1`!

**Comment by giuppep** [comment]
Looks like it's working fine now. Thanks a lot for fixing 😃 

(By the way, great job on the library, I really like it! 😉 )
