### ISSUE TITLE
Command containing multiple quotes is not executed although the result is shown as successful

### ISSUE THREAD

**Issue by alexandrunastase** [Fizzadar/pyinfra#576]
## Describe the bug
Command is not executed when using server.shell operation. I also tried creating a new operation for this, but that didn't work either.

When running the command in the terminal it is applied as expected.

## To Reproduce
Created an example that reproduces the issue here:
https://github.com/alexandrunastase/pyinfra-dconf-issue-repro

## Expected behavior
dconf write command is executed

## Actual behavior
dconf write command is not executed

## Meta
+ Include output of `pyinfra --support`.
```
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.11.0-16-generic-x86_64-with-glibc2.33
      Release: 5.11.0-16-generic
      Machine: x86_64
    pyinfra: v1.3.10
    Executable: /home/alex/.local/bin/pyinfra
    Python: 3.9.4 (CPython, GCC 10.2.1 20210401)
```
+ How was pyinfra installed (source/pip)?
pip
+ Include pyinfra-debug.log (if one was created)
Does not exist
+ Consider including output with `-vv` and `--debug`.
```
sudo -l 
Matching Defaults entries for alex on zen:
    env_reset, mail_badpass, secure_path=/usr/local/sbin\:/usr/local/bin\:/usr/sbin\:/usr/bin\:/sbin\:/bin\:/snap/bin

User alex may run the following commands on zen:
    (ALL : ALL) ALL
pyinfra inventory.py up.py -vv --debug
    [pyinfra_cli.main] Checking potential directory: 
    [pyinfra_cli.main] Checking potential directory: 
    [pyinfra_cli.main] Checking potential directory: 
    [pyinfra_cli.main] Checking potential directory: 
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...

--> Connecting to hosts...
    [@local] Connected
    [pyinfra.api.state] Activating host: @local

--> Preparing operations...
    Loading: up.py
    [pyinfra.api.operation] Adding operation, {'dconf write test'}, opOrder=(4,), opHash=6a58b6c7e02f6d92150e84bffa4418d987f54dc9
    [@local] Ready: up.py

--> Proposed changes:
    Groups: inventory / @local / my_hosts
    [@local]   Operations: 1   Commands: 1   

--> Beginning operation run...
--> Starting operation: dconf write test 
    [pyinfra.api.operations] Starting operation dconf write test on @local
[pyinfra.api.connectors.local] --> Running command on localhost: sudo -H -n sh -c 'dconf write /org/gnome/desktop/wm/keybindings/close "['"'"'<Primary>q'"'"']"'
[@local] >>> sudo -H -n sh -c 'dconf write /org/gnome/desktop/wm/keybindings/close "['"'"'<Primary>q'"'"']"'
[pyinfra.api.connectors.util] --> Waiting for exit status...
[pyinfra.api.connectors.util] --> Command exit status: 0
    [@local] Success

--> Results:
    Groups: inventory / @local / my_hosts
    [@local]   Successful: 1   Errors: 0   Commands: 1/1  
```

**Comment by Fizzadar** [comment]
Interesting! I suspect this is a similar issue [to the quoting of`sed` commands](https://github.com/Fizzadar/pyinfra/commit/62cdd1e21783fff98389980dc584fed09af8945f), will start by looking there!

**Comment by Fizzadar** [comment]
I've been digging into this and am struggling to re-create the issue, I've setup an example to just echo out the quoted value as it makes it easier to debug:

```py
from pyinfra.operations import server

server.shell(
    commands='''echo "['<Primary>q']"''',
)
```

Output: 

```
$  pyinfra @local test_quotes.py  -vvv
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [@local] Connected

--> Preparing operations...
    Loading: test_quotes.py
    [@local] Ready: test_quotes.py

--> Proposed changes:
    Groups: @local
    [@local]   Operations: 1   Commands: 1

--> Beginning operation run...
--> Starting operation: Server/Shell (commands=echo "['<Primary>q']")
[@local] >>> sh -c 'echo "['"'"'<Primary>q'"'"']"'
[@local] ['<Primary>q']
    [@local] Success

--> Results:
    Groups: @local
    [@local]   Successful: 1   Errors: 0   Commands: 1/1
```

This does appear to be correctly quoting and printing `['<Primary>q']` as expected? @alexandrunastase would you mind testing with this example as well, there could be something else going on here.

**Comment by alexandrunastase** [comment]
Hey Nick. Thanks again for taking a look into this.

So I think I found an even better way of reproducing the issue.


```python
from pyinfra.operations import server

server.shell(
    commands='''echo "\"['<Primary>q']\"" | sudo tee keyboard.txt ''',
)
```
Output from pyinfra is a file containing `[<Primary>q]`. So no single quotes and no double quotes in this case

But when running the command directly in the terminal 

```bash
echo "\"['<Primary>q']\"" | sudo tee keyboard.txt
```
the output is quoted as expected: `"['<Primary>q']"`

**Comment by Fizzadar** [comment]
Thanks for the update - I believe this is actually due to Python escaping the `\"` even within the triple quotes; for example the following works as expected:

```py
from pyinfra.operations import server

server.shell(
    commands='''echo "\\\"['<Primary>q']\\\"" | tee keyboard.txt ''',
)
```

I think the triple backslashes are unavoidable in getting Python to correctly include the single one in the final command:

```
In [1]: print('''echo "\"['<Primary>q']\"" | sudo tee keyboard.txt ''')
echo ""['<Primary>q']"" | sudo tee keyboard.txt

In [2]: print('''echo "\\\"['<Primary>q']\\\"" | sudo tee keyboard.txt ''')
echo "\"['<Primary>q']\"" | sudo tee keyboard.txt
```

**Comment by alexandrunastase** [comment]
Thanks for the reply. I was not aware of this. I assumed this trippe single quotes allows any quotes inside. Your example works indeed for the writing correctly into the file, but I tried escpating the double quotes with the tripple backslashes for the dconf example at the beginning and that didn't work. Do you have any idea how that could be fixed?

**Comment by Fizzadar** [comment]
I believe the fix would be to wrap the string in double quotes, ie:

```''' dconf write /org/gnome/desktop/wm/keybindings/close "\\\"['<Primary>q']\\\"" '''```

I can test with `dconf` itself but this appears to correctly print out with both the double and single quotes included:

```py
from pyinfra.operations import server

server.shell(
    commands=''' echo "\\\"['<Primary>q']\\\"" ''',
)
```

**Comment by alexandrunastase** [comment]
So I tried this exact thing in this file : https://github.com/alexandrunastase/pyinfra-dconf-issue-repro/blob/main/up.py .

The escaping seems to be alright in the created file, but somehow the dconf command is still not executed properly, although the return code seems to be 0. Maybe there is something else that I am missing, apart from the quoting.
