### ISSUE TITLE
Ability to load other templates

### ISSUE THREAD

**Issue by wilypomegranate** [Fizzadar/pyinfra#586]
## Is your feature request related to a problem? Please describe
When using ```files.template``` it would be handy to be able to load relative templates to create complex jinja templates.

## Describe the solution you'd like
I think changing get_template to allow for using a FileSystemLoader referenced to the current working directory would work.

Something like

```python
Environment(loader=FileSystemLoader(os.getcwd())
```

**Comment by Fizzadar** [comment]
👍 big fan of this. I think it needs to use the "deploy directory" as the root point, which is either cwdir or the folder in which the (first) deploy file lives. There's some issues with the deploy dir thing but that needn't affect this!

**Comment by wilypomegranate** [comment]
Yeah that makes sense. I tried a quick test with the FileSystemLoader and it seems to work.

**Comment by themanifold** [comment]
Just so I'm understanding this correctly, is this going to fix the inability to use 

`{% include 'template/foo.j2 %}`

which currently gives me this error:

```
TypeError: no loader for this environment specified
```
