### ISSUE TITLE
Error: could not load fact: deb_packages

### ISSUE THREAD

**Issue by 4bo** [Fizzadar/pyinfra#587]
trying to run a simple command on a debian 10 target by pyinfra 1.4:
```
pyinfra myserver apt.packages iotop sudo=True
```
i get:
```
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [myserver] Connected

--> Preparing operation...
    [myserver] sudo: a password is required
    [myserver] Error: could not load fact: deb_packages 
--> pyinfra error: No hosts remaining!
```
the problem is with sudo part, non sudo commands is ok

**Comment by Fizzadar** [comment]
@4bo if you add `use_sudo_password=true` it should prompt for the password so this will work!

Currently there is no automatic detection of when a sudo password is required; there's [an issue tracking this here](https://github.com/Fizzadar/pyinfra/issues/318).
