### ISSUE TITLE
@local does not honor USE_SUDO_PASSWORD

### ISSUE THREAD

**Issue by gnat** [Fizzadar/pyinfra#591]
## Describe the bug
`USE_SUDO_PASSWORD` does not seem to work in the same way on `@local` as it does on `@ssh`

This bug is a bit insidious because if you run the same command multiple times in a row, it may work depending on your local machine.

## To Reproduce
Using `@local`

```python
from pyinfra import host
SUDO = True
USER = 'you'
USE_SUDO_PASSWORD = 'password'

# Fails with 
# [@local] sudo: 3 incorrect password attempts
# [@local] Error: could not load fact: command (command=whoami)
output = host.fact.command("whoami")

# Works
output = host.fact.command("whoami", use_sudo_password=USE_SUDO_PASSWORD)

# Fails with 
# [@local] sudo: 3 incorrect password attempts
# [@local] Error: could not load fact: command (command=echo 'hello')
output = host.fact.command("echo 'hello'")
```

## Expected behavior
Pretty sure this is just an oversight, config globals should ideally work in the same way as `@ssh`.

**Comment by Fizzadar** [comment]
Hmm - no matter what I do I cannot replicate this one! If you switch to doing `USE_SUDO_PASSWORD = True` does it prompt and work as expected?

The config variables are handled outside of the connector scope so should be applied identically for both `@ssh` & `@local`...

**Comment by Fizzadar** [comment]
Closing as cannot replicate - I also suspect v1.5 may solve this completely with proper automatic sudo prompting.

**Comment by gnat** [comment]
No worries! Hopefully this was my bad and this can be put to rest.

Will re-open with more detail if I can replicate in 1.5.
