### ISSUE TITLE
dnf.packages does notr accept mixed case package names

### ISSUE THREAD

**Issue by BandungBB** [Fizzadar/pyinfra#599]
## Describe the bug
I can not install a fedora package using dnf.package() because the package names are converted to all lowercase before pyinfra hands them off to it's internal dnf processing script.

## To Reproduce
dnf.packages(
        name = "install system tools",
        packages = [
            'NetworkManager',
            'unixODBC-gui-qt',
            'unixODBC',
            ],
        sudo = True,
 
 ## Expected behavior
There should be a way to freeze the package name so that the upper case letters remain in the package's name

## Meta
Here is what's recorded as the errors;
    [@local] No match for argument: networkmanager
    [@local]   * Maybe you meant: NetworkManager
    [@local] No match for argument: unixodbc-gui-qt
    [@local]   * Maybe you meant: unixODBC-gui-qt
    [@local] No match for argument: unixodbc
    [@local]   * Maybe you meant: unixODBC
    [@local] Error: Unable to find a match: networkmanager unixodbc-gui-qt unixodbc
    [@local] Error

+ How was pyinfra installed (source/pip)?
pyinfra was installed using dnf

**Comment by Fizzadar** [comment]
Thanks for reporting this, @BandungBB - looks like this was never updated when then `rpm.RpmPackages` fact was updated; I've now corrected this in https://github.com/Fizzadar/pyinfra/commit/e0fc224343648d6b8e60afc65e5a38a07e0c82b3, pending `v1.4.3` release (today most likely).

**Comment by Fizzadar** [comment]
Just (at last) released this in `v1.4.3`!

**Comment by BandungBB** [comment]
I appreciate you doing this do quickly. I wasn't expecting such a quick turn around. Thanks!
