### ISSUE TITLE
Update Jinja2 minimum version (jinja2 v3.x compatibility check)

### ISSUE THREAD

**Issue by Jobrowncsm** [Fizzadar/pyinfra#610]
## Is your feature request related to a problem?
Flask has increased minimum Jinja2 version to 3.x. To use Flask 2.x a separate deployment environment would be need to me maintained.

## Describe the solution you'd like
Update Jinja2 version.

**Comment by Fizzadar** [comment]
Hi @Jobrowncsm! I don't think bumping the minimum version is appropriate here, but expanding the maximum version to v4. I need to double check none of the 2->3 changes break the way `pyinfra` is using the library but I don't believe this is the case. I can then bump it up to allow v3.x as well as 2.x.

**Comment by Fizzadar** [comment]
I've just released the loosened requirement in v1.4.8.
