### ISSUE TITLE
bsdinit.service (FreeBSD) incorrect status command name

### ISSUE THREAD

**Issue by bikingcoder** [Fizzadar/pyinfra#617]
Out of the box there are a couple of issues with bsdinit.service on FreeBSD (using 12.2).

The [status_command](https://github.com/Fizzadar/pyinfra/blob/current/pyinfra/operations/bsdinit.py#L37) is set to 'check' but in actual fact it should be 'status'. (or somehow both are evaluated if necessary although I've no idea how that would fit in to the current design)

Secondly, the [path](https://github.com/Fizzadar/pyinfra/blob/current/pyinfra/operations/bsdinit.py#L35) is only valid for base FreeBSD packages ie it doesn't respect `/usr/local/etc/rc.d`. Can be worked around with a symlink but this seems a bit limited.

**Comment by bikingcoder** [comment]
Thanks for working on this! I'm keen to use pyinfra more, and see it as a possible Ansible alternative at day job.

**Comment by Fizzadar** [comment]
@mcgaw that's great; I'm keen to expand BSD support in pyinfra! I've just released `v1.4.10` which should fix both issues with `bsdinit.service` (https://github.com/Fizzadar/pyinfra/commit/925e967275d97170844379d2e06bc3ae3f057858) - let me know if that works, and also if there's other operations/similar that might be of use in the BSD world :)

**Comment by bikingcoder** [comment]
@Fizzadar apologies for not getting back to you sooner, just back in this space again. it seems to work now, thanks!
