### ISSUE TITLE
Support for 'yield' syntax in modules

### ISSUE THREAD

**Issue by hoh** [Fizzadar/pyinfra#62]
Many modules contain the following pattern:
```python
commands = []
if condition:
    commands.append('do stuff')
elif other_condition:
    commands.append('do more stuff')
commands.append('finally to this')
return commands
```

It would make modules easier to read if we could simply yield the commands as a generator, while keeping compatibility with the existing approach:
```python
if condition:
    yield 'do stuff'
if other_condition:
    yield 'do more stuff'
yield 'finally do this'
```

**Comment by Fizzadar** [comment]
@hoh I'm a _huge_ fan of this approach! This is far superior to the list method and I'm going to look to move everything over to this.

**Comment by hoh** [comment]
@Fizzadar thanks 👍
