### ISSUE TITLE
pkgin support

### ISSUE THREAD

**Issue by lun-4** [Fizzadar/pyinfra#632]
Using https://github.com/Fizzadar/pyinfra/issues/617#issuecomment-884766468 to submit an idea I had!

I have some NetBSD boxes here and there and would like to manage them with pyinfra, one step in that direction would be support for [pkgin](https://pkgin.net/), which is an user-friendly frontend to pkgsrc (which is already "provided" by the `pkg` module). 

A new `pkgin` module would be the idea, providing operations with the same semantics as the `apt` module with `packages()`, `update()`, and `upgrade()`:
 - `packages()` can be implemented because `pkgin list` shows all currently installed packages, so you can discard unecessary reinstallations
 - Maybe `autoremove()` could be done as well?

I can provide a NetBSD VM in my infrastructure for testing purposes, if you wish to!

**Comment by Fizzadar** [comment]
Definitely keen to add support for this!
