### ISSUE TITLE
Upgrade to distro 1.6

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#641]
Includes the `root_dir` argument so can remove the hack around it in https://github.com/Fizzadar/pyinfra/blob/current/pyinfra/facts/util/distro.py.

**Comment by link2xt** [comment]
Is this stale issue already done? `setup.py` requires distro 1.6:
https://github.com/Fizzadar/pyinfra/blob/6eca1a52d955a0497cd33c02cb9a94176f93583d/setup.py#L31

Not sure what `root_dir` is.
