### ISSUE TITLE
`file.put` fails if `dest` is a directory

### ISSUE THREAD

**Issue by oz123** [Fizzadar/pyinfra#663]
## Describe the bug
Using `files.put` as:

```
files.put(
   src="/home/oz123/some.deb"
   dest='/home/oz123/'
   )
```

Results in the following error:
```
   [hostxxx] Command socket/SSH error: OSError('Failure',)
```

Which is pretty cryptic...

## To Reproduce
Use as above.

## Expected behavior
One can use `files.put` as  with regular `sftp` or other unix commands `mv`, `cp`, which allow to ommit file name if the path is directory.

## Meta
+ Include output of `pyinfra --support`.
```
oz123@server:~/nesuss-agents$ ./venv/bin/pyinfra --support
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
      Release: 4.4.0-18362-Microsoft
      Machine: x86_64
    pyinfra: v1.4.14
    Executable: ./venv/bin/pyinfra
    Python: 3.8.10 (CPython, GCC 9.4.0)
oz123@server:~/nesuss-agents$

```
+ How was pyinfra installed (source/pip)?
```pip3 install pyinfra```

The issue is actually not with pyinfra, rather with paramiko (I have 2.7.2) see here https://github.com/paramiko/paramiko/issues/1000.

**Comment by Fizzadar** [comment]
Thank you for fixing this @oz123; this is now live in `v1.4.15`.
