### ISSUE TITLE
Mention debug-inventory in `--help` dialog

### ISSUE THREAD

**Issue by themanifold** [Fizzadar/pyinfra#673]
Mention the `debug-inventory` operation in the `--help` dialog, it only makes sense and it's referenced in the docs already: https://docs.pyinfra.com/en/1.x/deploys.html#data-hierarchy

**Comment by Fizzadar** [comment]
Just added this in https://github.com/Fizzadar/pyinfra/commit/7f455380e9046da5a81d19dfb070aee3e0712c33 and released in `v1.4.18`.
