### ISSUE TITLE
Move everything to yield

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#69]
Easier to reason about and avoids issues of early returns, move all modules to yield syntax and update operations docs to recommend that.

**Comment by Fizzadar** [comment]
Annoyingly - to support Python 2 any nested operation calls will need to use: https://stackoverflow.com/questions/17581332/converting-yield-from-statement-to-python-2-7-code as `yield from` is Py3 only.

**Comment by Fizzadar** [comment]
https://github.com/Fizzadar/pyinfra/commit/46909020c166cd94dae2176c63ea1621692df70d & https://github.com/Fizzadar/pyinfra/commit/d67a2a60cf97963a2a12787ce1f76d3311a80a58

**Comment by hoh** [comment]
Awesome 👍
