### ISSUE TITLE
Future planning: how to manage global arguments

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#695]
pyinfra has a [number of global `@operation`/`@deploy` arguments](https://docs.pyinfra.com/en/1.x/deploys.html#global-arguments), these are "magic" in that they are extracted before other arguments are passed into the operation/deploy function. This means that these functions cannot use arguments with the same name as global arguments.

While this works OK for builtin operations, where this issue can be managed, it's a disaster for 3rd party operations and deploys. It effectively bocks additional global arugments being added (such as `docker_user`, which would be very useful).

```py
# Currently:
files.file(
    name='Create a file as the pyinfra user using sudo',
    path='/home/pyinfra/sudo_testfile',
    sudo_user='pyinfra',
    env={'PATH': '/home/pyinfra/.local/bin'},
)

# Could become:
with operation_args(sudo_user='pyinfra', env={'PATH': '/home/pyinfra/.local/bin'}):
    files.file(
        name='Create a file as the pyinfra user using sudo',
        path='/home/pyinfra/sudo_testfile',
    )

# OR, make a simple rule that _ prefixed commands are reserved:
files.file(
    name='Create a file as the pyinfra user using sudo',
    path='/home/pyinfra/sudo_testfile',
    _sudo_user='pyinfra',
    _env={'PATH': '/home/pyinfra/.local/bin'},
)

# OR, a dictionary for all such commands
files.file(
    name='Create a file as the pyinfra user using sudo',
    path='/home/pyinfra/sudo_testfile',
    operation_args={
        'sudo_user': 'pyinfra',
        'env': {'PATH': '/home/pyinfra/.local/bin'},
    },
)

# OR, nicer(?) style
files.file(
    name='Create a file as the pyinfra user using sudo',
    path='/home/pyinfra/sudo_testfile',
    operation_args=dict(
        sudo_user='pyinfra',
        env={'PATH': '/home/pyinfra/.local/bin'},
    ),
)
```

Currently leaning towards the dict (option 3+4), with the final option style wise, only because it's easier to read (IMO, very subjective) and is the closest match to the current way.

**Comment by Fizzadar** [comment]
From: https://github.com/Fizzadar/pyinfra/issues/585#issuecomment-860271266

> This might be the right point to also start supporting Solaris'/Illumos' pfexec, and maybe unify the interface of using them? Instead of having various use_<UTIL>_login, use_<UTIL>_password, preserve_<UTIL>_env, remove the specific name, and provide a new parameter like e.g. priv_tool that can be set to one of the supported methods. Then I could write in my deploys files.file(..., priv_tool=doas, use_priv_login=True).
>
> This way, when I adapt the deploy to another OS, or simply when I have to switch to sudo because I started to need to use some of its features, I only have change it at one point. That point could even be somewhere central, instead of in every single operation.

**Comment by skutter-de** [comment]
I'd prefer option 3 I think just because option 4 is more verbose where it doesn't need to be. On the other hand, another solution could be just to prefix like Ansible does (e.g. pyinfra_sudo_user)

**Comment by Fizzadar** [comment]
`_` prefixed gloal arguments is now part of v2, with backwards compatibility until v3.

**Comment by Fizzadar** [comment]
Released in v2!
