### ISSUE TITLE
Remove global state/host arguments

### ISSUE THREAD

**Issue by Fizzadar** [Fizzadar/pyinfra#707]
These were added [a long time ago](https://github.com/Fizzadar/pyinfra/commit/bcb705a598ce6caee00e5ac4d416f94ab4935492#diff-a0bc476655b0a490b3fd21803c145ea405618bea9902c1a4d74a77380ceaa461), there’s effectively two ways to call any operation or deploy function. Should just always use the pseudo host object? This always represents the current state/host in CLI mode and could easily be applied to API mode working the same.

Ops/deploys can then just use these direct rather than having them passed into functions with `None` as the default.

**Comment by Fizzadar** [comment]
Also maybe time to rename pseudo to context or whatever, it’s effectively a set of classes that represent the current context at all times.

**Comment by gnat** [comment]
Removing the args seems like a fair simplification. :+1:  I do use the `host` pseudo-object quite extensively to retrieve group data and run `host.fact.command()` (to get raw output of a command)

**Comment by Fizzadar** [comment]
Released in v2 🎉
