### ISSUE TITLE
Fact: underlying StringCommand cannot ignore exit code != 0

### ISSUE THREAD

**Issue by yggdr** [Fizzadar/pyinfra#709]
While writing a new Fact I wanted it to execute a command that might return an error code, but still writes useful information to stdout. Pyinfra seems to interpret any exit code other than 0 as a failure to gather the fact, and StringCommand cannot be given the `ignore_error` kwarg, as that seems to be filtered out explicitly in the `PyinfraCommand`'s `__init__` via `get_executor_kwarg_keys`.

Looking at other Facts it seems you essentially have to add ` || true` at the end of the command you want run, so the exit status is always 0. This seems like a hack, `ignore_errors` should be allowed, so I can grab the text if I so choose.

**Comment by Fizzadar** [comment]
I think this is a great idea - there already exists a `success_exit_codes` global argument that could be used to achieve this just needs fact support example from operation:

https://github.com/Fizzadar/pyinfra/blob/7283f844ef991166dd0da9f5791b603e651e9691/pyinfra/operations/server.py#L80

**Comment by Fizzadar** [comment]
https://github.com/Fizzadar/pyinfra/pull/759 solves this in the upcoming v2 by enabling all of the execution arguments in fact calls.
