### ISSUE TITLE
Calling operation from dynamic execution leads to error

### ISSUE THREAD

**Issue by themanifold** [Fizzadar/pyinfra#710]
Are we meant to be able to invoke pyinfra operations from within a dynamic execution as defined here: https://docs.pyinfra.com/en/1.x/examples/dynamic_execution_deploy.html

```
from pyinfra.operations import files, python


def do_something(host, state):
    files.directory(name="something", path="/tmp/foo", present=False)


python.call(name="call do_something", function=do_something)
```

If we run this I get:

```
    Traceback (most recent call last):
  File "/some/dir/venv/lib/python3.9/site-packages/pyinfra/api/operations.py", line 120, in _run_server_op
    status = command.execute(state, host, executor_kwargs)
  File "/some/dir/venv/lib/python3.9/site-packages/pyinfra/api/command.py", line 184, in execute
    return self.function(state, host, *self.args, **self.kwargs)
  File "05_deploy_services.py", line 118, in tidy_old_dirs
    files.directory(
  File "/some/dir/venv/lib/python3.9/site-packages/pyinfra/api/operation.py", line 183, in decorated_func
    global_kwargs, global_kwarg_keys = pop_global_op_kwargs(state, host, kwargs)
  File "/some/dir/venv/lib/python3.9/site-packages/pyinfra/api/operation_kwargs.py", line 165, in pop_global_op_kwargs
    host_default = getattr(host.data, key, None)
AttributeError: 'NoneType' object has no attribute 'data'

    [some_server.com] Unexpected error in Python callback: AttributeError("'NoneType' object has no attribute 'data'",)
    [some_server.com] Error
--> pyinfra error: No hosts remaining!
```
If it helps, if I look at that point with a debugger, I see that `state` *is* defined and of course `host` is empty.

One thing I don't understand from the dynamic execution, from the docs. 
1. Where is `host` and `state` declared - it is referenced in the python function definition called `do_something(state, host)` in my code, but I don't see it defined anywhere? I assume it's some magic global that is injected by the pyinfra invocation of the deploy script, maybe?

If we're not meant to run pyinfra operations from within a dynamic execution, then we should probably document that and put some guard rails up in the code.

I'm using 
```
pyinfra --version
pyinfra: v1.5.0.dev0
```

**Comment by Fizzadar** [comment]
Hi @themanifold - the issue here is calling an operation during execution - ops can only (currently) be generated before any execution starts. So to dynamically run commands inside a callback function you need to use the lower level `host.run_shell_command`:

```py
def callback(state, host):
    status, stdout, stderr = host.run_shell_command('cat /var/lib/zerotier-one/identity.public')
    ...
```

This error is confusing and useless and I'd like to update it to reference the actual issue here and point to the above.

**Comment by themanifold** [comment]
Thanks for that. I think the docs hint at it, but they never say it is the only way, so thanks for clarifying. How do I invoke the `host.run_shell_command` with sudo etc? Or do I need to do all that instrumentation myself?

**Comment by Fizzadar** [comment]
All the arguments like `sudo*`, `su*`, etc can be passed to `run_shell_command` so no need to manually build that. Keeping this issue to make this clearer in the documentation and expand the example.

**Comment by Fizzadar** [comment]
Calling operations inside callbacks is now supported in `v2.1` 🎉!
