### ISSUE TITLE
Config option to suppress warning: "Invalid auth argument: cannot use use_sudo_password without sudo."

### ISSUE THREAD

**Issue by gnat** [Fizzadar/pyinfra#711]
## Issue / Use Case
I frequently switch sudo on/off for my task scripts. This currently works flawlessly using `config.SUDO = True` and `config.SUDO = False` I pre-fill `config.USE_SUDO_PASSWORD`.

Great for situations like:
1. `config.SUDO = True`
2. Adjust firewall (root user).
2. `config.SUDO = False`
2. Run Rootless Docker (normal user).

The issue is when I `config.SUDO = False` pyinfra will print out:
```
Invalid auth argument: cannot use `use_sudo_password` without `sudo`.
```
Of course I can suppress this by continually setting/unsetting `config.USE_SUDO_PASSWORD` but this is super inconvenient.

## Describe the solution you'd like
* `config.py` option to suppress this warning.

Thanks!

**Comment by Fizzadar** [comment]
Hi @gnat - 100% agree with this the warning isn't showing in the expected scenarios. I'm not sure it's possible to reliably show these warnings at all as there's many different combinations of config/global args/etc. Will have a think about how best to handle this but maybe removing the warnings alltogether would be an improvement.

**Comment by Fizzadar** [comment]
These were removed entirely a while back, the logic around when these are/aren't valid is too confusing.
