### ISSUE TITLE
Link to GitHub Examples broken

### ISSUE THREAD

**Issue by FullByte** [Fizzadar/pyinfra#712]
## Describe the bug
On https://pyinfra.com in the footer "pyinfra on GitHub" the links for "Examples" is broken
Is:  https://github.com/Fizzadar/pyinfra/tree/current/example
Should be https://github.com/Fizzadar/pyinfra/tree/current/example**s**

## To Reproduce
Go to https://github.com/Fizzadar/pyinfra/tree/current/example

## Expected behavior
Should be https://github.com/Fizzadar/pyinfra/tree/current/examples

**Comment by Fizzadar** [comment]
Thank you for spotting this @FullByte! Now updated :)

**Comment by drennalls** [comment]
@Fizzadar The link seems to be broken again.

**Comment by FullByte** [comment]
Seems like this is the case because branches where introduced (e.g. 2.x). 

FYI: Correct link is now https://github.com/Fizzadar/pyinfra/tree/2.x/examples

Possibly more links referring to this repository are broken due to this?

**Comment by Fizzadar** [comment]
OK this is fixed again, all the website links go to documentation now which is stable and branch independant. I did a quick sweep of the docs too and they should all be OK!
