### ISSUE TITLE
Docker operations?

### ISSUE THREAD

**Issue by mjmare** [Fizzadar/pyinfra#716]
It may be that I don't understand the purpose of the docker and dockerssh connectors, but it seems to me that a set of Docker operations appears to be a glaring omission given Docker's ubiquity. 
For example building/managing images, starting/stopping containers, managing docker compose stacks etc. Say, something similar to (part of) https://docs.ansible.com/ansible/latest/collections/index_module.html#community-docker

If similar functionality is already present in PyInfra please clarify.

TIA!

**Comment by shohamd4** [comment]
Hi, these kinds of docker operations are highly valuable.
Would you have any thoughts on implementing it?
Thanks

**Comment by ebreton** [comment]
+1 for `docker-compose` (and docker in general) 🙏

**Comment by Fizzadar** [comment]
These were added in v3!
