### ISSUE TITLE
Support for not installing recommended packages in apt.packages

### ISSUE THREAD

**Issue by hoh** [Fizzadar/pyinfra#72]
By default, Ubuntu installs recommended but not suggested packages. With `--no-install-recommends`, only the main dependencies (packages in the Depends field) are installed.

It would be useful to provide an option to [`apt.packages` ](https://github.com/Fizzadar/pyinfra/blob/develop/pyinfra/modules/apt.py#L212)to support this argument.

**Comment by Fizzadar** [comment]
Closed @ https://github.com/Fizzadar/pyinfra/commit/6fbfe898fdf29884cc88c0814b18146ccfb3ec5c

**Comment by hoh** [comment]
Thanks 👍
