### ISSUE TITLE
ssh connector does not handle proxyjump correctly

### ISSUE THREAD

**Issue by bauen1** [Fizzadar/pyinfra#728]
With an ssh configuration like
```
Host de-fra0.lab.bauen1.xyz
    ProxyJump none
Host *
    ProxyJump sysadmin@de-fra0.lab.bauen1.xyz:80
```

OpenSSH will proxy every ssh connection through `sysadmin@de-fra0.lab.bauen1.xyz:80` except connections to `de-fra0.lab.bauen1.xyz`

pyinfra breaks with this config and will enter an recursive loop, relevant code:
https://github.com/Fizzadar/pyinfra/blob/df120c702399d58bf3370b0cdd9fbe71b489e4e6/pyinfra/api/connectors/sshuserclient/client.py#L81-L96

**Comment by Fizzadar** [comment]
This should now be fixed as of `v1.6` which I just pushed out (fixed by https://github.com/Fizzadar/pyinfra/commit/5c14d4391bafb17daba4d3eb6e4e0bd24c7741bf).
