### ISSUE TITLE
apk not being found with alpine using dropbear sshd.

### ISSUE THREAD

**Issue by bogen85** [Fizzadar/pyinfra#729]
## Describe the bug
I'm using infra on alpine with dropbear sshd and apk is not being found.
I did try openssh sshd and it works, but for some of my setups I'd prefer to use dropbear.

## To Reproduce
```sh
# this is on a temporary scratch install of alpine
pyinfra --user root 192.168.122.227 apk.packages rsync
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [192.168.122.227] Connected

--> Preparing operation...
    [192.168.122.227] Ready: apk.packages

--> Proposed changes:
    Ungrouped:
    [192.168.122.227]   Operations: 1   Commands: 1   

--> Beginning operation run...
--> Starting operation: Apk/Packages (rsync)
    [192.168.122.227] sh: apk: not found
    [192.168.122.227] Error
--> pyinfra error: No hosts remaining!
Wed 29Dec21 02:40:15 ~
```
## Expected behavior
I expected a way to specify the path to apk.
I did a sed replace of apk with /sbin/apk and it works.
```sh
sed "s,'apk,'/sbin/apk," .local/lib/python3.10/site-packages/pyinfra/facts/apk.py -i
sed "s,'apk,'/sbin/apk," .local/lib/python3.10/site-packages/pyinfra/operations/apk.py -i
sed "s,'apk,'/sbin/apk," .local/lib/python3.10/site-packages/pyinfra/operations/server.py -i
```

Should there be a way to configure an absolute path for remote package management commands?
I could make a PR if we can agree on how this could be made configurable.

## Meta
+ Include output of `pyinfra --support`.
```
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.15.11-arch2-1-x86_64-with-glibc2.33
      Release: 5.15.11-arch2-1
      Machine: x86_64
    pyinfra: v1.5
    Executable: /home/dwight/.local/bin/pyinfra
    Python: 3.10.1 (CPython, GCC 11.1.0)
```
+ How was pyinfra installed (source/pip)?
```sh
pip install --user pyinfra
```

**Comment by bogen85** [comment]
I tried the ```@chroot``` connector and had the same issue and had to patch pyinfra the same way to make it work ```( apk to /sbin/apk )```.

By the way... ansible is not working for me with alpine chroots, due to the way it treats symlinks in the chroot (as alpine is busybox based).

So, despite having to patch it, pyinfra is showing more promise for me than ansible...

**Comment by bogen85** [comment]
In general things would be more flexible and allow more variations to work if things like the sh, apk, and chroot commands were configurable. For example, I prefer to use [systemd-nspawn](https://wiki.archlinux.org/title/Systemd-nspawn) instead of chroot as it offers full container isolation, and generally works as a drop in replacement for chroot. If the chroot connector's chroot_command were configurable, systemd-nspawn could be used instead, without having to write a new connector.

systemd-nspawn is available on every systemd based linux distro and is more robust than chroot. (if something one run in a chroot leaks processes they are not automatically reaped when the chroot command ends, unlike when the command is run in a container like systemd-nspawn.

**Comment by bogen85** [comment]
These ( #724 and #692 ) may be related.

**Comment by bogen85** [comment]
Well, I wrote a wrapper script for chroot to use systemd-nspawn, that works fine.
I can set the PATH variable in the script, so no need to patch pyinfra's apk text for systemd-nspawn.
I might write a proper systemd-nspawn connector and make a PR for it.

As far as ssh goes, I can symlink /bin/apk to /sbin/apk and that allows pyinfra to connect via ssh.
So, for now this is not a showstopper for me, and I'm no longer having to patch pyintra to make it work.

**Comment by Fizzadar** [comment]
@bogen85 is there a reason `/sbin` isn't in the `PATH` by default for the user in question? The PATH issue isn't really something pyinfra itself can deal with directly - you could set `config.ENV` to apply path everywhere which should fix the issue. 

Thinking about general configurability - I think pyinfra's approach of running commands without an absolute path is correct and the `PATH` variable should be appropriately setup. The best I can think of would be some kind of aliasing system so you could say "for `apk` use `/sbin/apk`, etc.

Re: `systemd-nspawn` - are you using the `@chroot` connector at the moment? There's two approaches here:

- A new connector specific for `systemd-nspawn`
- Add a configuration field `host.data.X` to change the behaviour of the `@chroot` connector (this is probably nicer?)

**Comment by bogen85** [comment]
@Fizzadar I think on the PATH issue, [dropbear](https://matt.ucc.asn.au/dropbear/dropbear.html) appears to be the culprit as it is not setting the path and is not honoring the ssh config for environment variables. The [documentation](https://linux.die.net/man/8/dropbear) for dropbear claims it sets them, and I'll have to dig deeper into that.

Regarding systemd-nspawn, yes, I'm using the ```@chroot``` connector along with a chroot wrapper script in my path. See #731 for more details. I'm open to either (new connector or new configuration field) as long as I have the some functionality I'm getting from the wrapper (systemd-nspawn run with sudo, not all of pyinfra) (with ansible and chroot, all of ansible has to be run as root).

**Comment by bogen85** [comment]
It is working now on a fresh setup (no ~/.ssh/config specifics needed). Have not determined what was causing it to not work earlier.

Continuing discussion on #731for chroot.
