### ISSUE TITLE
host.fact.linux_distribution in deploy returns FakeData

### ISSUE THREAD

**Issue by hoh** [Fizzadar/pyinfra#74]
When typing `print('DISTRO', host.fact.linux_distribution)` in a `deploy.py` / role, I get `FakeData` instead of the expected result. Running `pyinfra (...) --fact linux_distribution` prints the expected dictionary.

This is probably a regression as I did not have this issue in the past. `pyinfra==0.1.5` from Pypi.

**Comment by Fizzadar** [comment]
@hoh this is expected - the first print will be executed when the CLI loads up the deploy file to check for any hooks and/or config variables - at that point the deploy isn't actually running (it happens before we even connect) - for example:

```
$  pyinfra -i ubuntu14.pyinfra test.py --user vagrant --key src/example/files/insecure_private_key

### Welcome to pyinfra

DISTRO FakeData
--> Connecting to hosts...
    [ubuntu14.pyinfra] Connected

--> Building deploy scripts...
DISTRO {'name': 'Ubuntu', 'major': '14', 'minor': '04'}
    [ubuntu14.pyinfra] Ready
```

Where `test.py` looks like:

```py
from pyinfra import host

print('DISTRO', host.fact.linux_distribution)
```
