### ISSUE TITLE
Possible future breakage: files.replace and Python 3.10

### ISSUE THREAD

**Issue by lun-4** [Fizzadar/pyinfra#776]
[PEP 622](https://peps.python.org/pep-0622/#backwards-compatibility), which introduced `match` and `case`, says:
> This PEP is fully backwards compatible: the match and case keywords are proposed to be (and stay!) soft keywords, so their use as variable, function, class, module or attribute names is not impeded at all.

So as of Python 3.10, nothing breaks. I think we should consider future-proofing `files.template`'s `match` parameter as it's possible they become proper keywords in the future, same as how `async` and `await` were introduced in Python 3.5 and 3.6, but had their syntax restricted in Python 3.7.

**Comment by Fizzadar** [comment]
Agree 100%, v2 is a good chance to rename this and can setup a warning/conversion in v1.8.

**Comment by Fizzadar** [comment]
Rolled this out in v2, renamed to `text` and shows a warning for the old `match` argument.
