### ISSUE TITLE
files.makedirs has no apparent effect

### ISSUE THREAD

**Issue by drewp** [Fizzadar/pyinfra#777]
bad:
```
    files.download(src=...     dest=dl)
    files.makedirs(local, exist_ok=True)  # this has no effect
    server.shell([
        f"aunpack --extract-to={local} {dl}",
    ])

--> Starting operation: Files/Download (src=https://github.com/kovidgoyal/kitty/releases/download/v0.24.4/kitty-0.24.4-x86_64.txz, dest=/tmp/kitty-0.24.4-x86_64.txz)
    [slash] No changes

--> Starting operation: Server/Shell (['aunpack --extract-to=/home/drewp/.local/kitty /tmp/kitty-0.24.4-x86_64.txz'])
    [slash] tar: /home/drewp/.local/kitty: Cannot open: No such file or directory
    [slash] tar: Error is not recoverable: exiting now
    [slash] aunpack: xz ... | tar ...: non-zero return-code
    [slash] Error
```

good:
```
    files.download(src=...     dest=dl)
    files.makedirs(local, exist_ok=True)
    server.shell([
        f"mkdir -p {local}",  # this workaround fixed it
        f"aunpack --extract-to={local} {dl}",
    ])

--> Starting operation: Files/Download (src=https://github.com/kovidgoyal/kitty/releases/download/v0.24.4/kitty-0.24.4-x86_64.txz, dest=/tmp/kitty-0.24.4-x86_64.txz)
    [slash] No changes

--> Starting operation: Server/Shell (['mkdir -p /home/drewp/.local/kitty', 'aunpack --extract-to=/home/drewp/.local/kitty /tmp/kitty-0.24.4-x86_64.txz'])
    [slash] Success
```

--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.34
      Release: 5.13.0-30-generic
      Machine: x86_64
    pyinfra: v1.7
    Executable: env/bin/pyinfra
    Python: 3.9.9 (CPython, GCC 10.3.0)

**Comment by Fizzadar** [comment]
Hi @drewp - was a bit confused by this, `files.makedirs` isn't an operation at all! It's actually just importing `os.makdirs` which is [imported/used in the `files.py` module](https://github.com/Fizzadar/pyinfra/blob/current/pyinfra/operations/files.py#L13). Using the [`files.directory`](https://docs.pyinfra.com/en/1.x/operations/files.html#files-directory) operation should enable you to achieve the desired result.

I suppose this is a weird gotcha with having everything be Python code. It would definitely be nice to avoid/prevent/warn about this somehow, but I'm not quite sure how (aside from prefixing them all or similar, which is not ideal!).

**Comment by drewp** [comment]
Ha, I see. I probably got it from autocomplete and assumed it must be an operation.
Possible fixes:
* put `del makedirs' (etc) at the bottom of files.py
* (probably better) put an `__all__` global in files.py listing the things you do want to export
* `import os` instead of `from os import makedirs` would have been enough here, since I'm not going to accidentally write `files.os.makedirs` in my config
* `makedirs = directory` at the bottom (kidding- don't do this)

**Comment by Fizzadar** [comment]
> makedirs = directory at the bottom (kidding- don't do this)

🤣 

Unfortunately `__all__` doesn't prevent such imports, I'll change things to just `import os` and use `os.makedirs` etc!

**Comment by drewp** [comment]
Whoa, I never knew `__all__` was only to control `import *`! 

Your fix sgtm.

**Comment by Fizzadar** [comment]
> Whoa, I never knew `__all__` was only to control `import *`!

Me either, only discovered it looking into this!

v2 + 1.7.1 include the fix as above.
