### ISSUE TITLE
systemctl unrecognized option --legend=false

### ISSUE THREAD

**Issue by nepeat** [Fizzadar/pyinfra#783]
## Describe the bug
systemctl error with unrecognized option when attempting to alter service state with pyinfra

```
[@local] >>> sh -c '! command -v systemctl >/dev/null || systemctl -al --plain --legend=false list-units'
    [@local] systemctl: unrecognized option '--legend=false'
    [@local] Error: could not load fact: systemd_status machine=None, user_mode=False, user_name=None
    Loaded fact systemd_status (machine=None, user_mode=False, user_name=None)
```

## To Reproduce
Ubuntu 20.04 LTS machine on Oracle Cloud

```
systemd.service(
    name="Restart and enable the Vault agent",
    service='vault-agent.service',
    running=True,
    restarted=True,
    enabled=True,
)
```

## Expected behavior
Service is enabled and restarted via systemd.

## Meta
Possible issue introduced via https://github.com/Fizzadar/pyinfra/commit/4d42f7a9aed3096808887d2064e76a2ea76516e4

**Comment by Fizzadar** [comment]
Thanks for reporting this @nepeat - looks like the flag is only available in the latest versions of systemd; I've reverted the change and released a fixed `v1.7.2`.
