### ISSUE TITLE
v2.0rc1 update notes

### ISSUE THREAD

**Issue by drewp** [Fizzadar/pyinfra#788]
I tried 2.0rc1 on my setup:

- "The `match` argument has been replaced by `text` in the `files.replace` operation" has no line number, but other warnings do. Odd.

- Running just my first two config scripts (~40 steps on ~4 hosts), the timing is:
```
v1.7.2:
   6.25s user 0.53s system 14% cpu 47.057 total
v2.0rc1:
   3.09s user 0.48s system 8% cpu 39.781 total
```

When I run all my configs in 11 pyinfra invocations:
```
v1.7.2:
    32.54s user 3.90s system 11% cpu 5:09.49 total
v2.0rc1:
    19.94s user 2.66s system 12% cpu 3:01.23 total
```

Nice!

**Comment by Fizzadar** [comment]
> I tried 2.0rc1 on my setup:
> 
>     * "The `match` argument has been replaced by `text` in the `files.replace` operation" has no line number, but other warnings do. Odd.

Will fix that, nice spot!

>     * Running just my first two config scripts (~40 steps on ~4 hosts), the timing is:
> ```
> v1.7.2:
>    6.25s user 0.53s system 14% cpu 47.057 total
> v2.0rc1:
>    3.09s user 0.48s system 8% cpu 39.781 total
> ```
> 
> When I run all my configs in 11 pyinfra invocations:
> 
> ```
> v1.7.2:
>     32.54s user 3.90s system 11% cpu 5:09.49 total
> v2.0rc1:
>     19.94s user 2.66s system 12% cpu 3:01.23 total
> ```
> 
> Nice!

This is excellent, and somewhat surprising too :)! Out of interest are the operations varied between hosts in this example? The new op gen stage should be much improved in such scenarios.

**Comment by Fizzadar** [comment]
Added the call location to the warning in https://github.com/Fizzadar/pyinfra/commit/5dcc99db73af610337179f9bf273bc6780f320ea!
