### ISSUE TITLE
apt --force-yes is deprecated

### ISSUE THREAD

**Issue by hoh** [Fizzadar/pyinfra#79]
At every use of the `apt` module, we get the following warning:
`W: --force-yes is deprecated, use one of the options starting with --allow instead`

In the man page, we find the following information:

> --force-yes
>       Force yes; this is a dangerous option that will cause apt to continue without prompting if it is doing something potentially harmful. It should not be used except in very special situations. Using force-yes can potentially destroy your system! Configuration Item: APT::Get::force-yes. This is deprecated and replaced by --allow-downgrades, --allow-remove-essential, --allow-change-held-packages in 1.1.

We are probably looking for `--assume-yes` as a safer and non-deprecated option:

> -y, --yes, --assume-yes
> Automatic yes to prompts; assume "yes" as answer to all prompts and run non-interactively. If an undesirable situation, such as changing a held package, trying to install a unauthenticated package or removing an essential package occurs then apt-get will abort. Configuration Item: APT::Get::Assume-Yes.

**Comment by Fizzadar** [comment]
`--assume-yes` is already passed as `-y` - I've now changed so `--force-yes` is only passed when explicitly requested, by use of an extra `force` kwarg @ https://github.com/Fizzadar/pyinfra/commit/6df273e38e6c3e4f6c3a35eb069101dab8e68982
