### ISSUE TITLE
Authentication error with Paramiko 2.9.0+ on older systems

### ISSUE THREAD

**Issue by julienlavergne** [Fizzadar/pyinfra#797]
## Describe the bug
As mentioned in this paramiko issue https://github.com/paramiko/paramiko/issues/1984, some additional parameters must be passed to `connect` in some cases.
Without those parameters, we hit an Authentication Error.

## To Reproduce
Simply connect to an old enough host, I can reproduce the issue on RedHat 6.10

## Expected behavior
Paramiko can be configured to work on older systems, I suppose we could have a way to provide os version in inventory in order to pass those parameters to paramiko.

**Comment by Fizzadar** [comment]
Whoops I missed this one; should now be possible to handle this by setting [`host.data.ssh_paramiko_connect_kwargs`](http://docs.pyinfra.com/en/2.x/connectors/ssh.html#available-data) which can set arbitrary Paramiko `SSHClient.connect` kwargs as needed here.
