### ISSUE TITLE
File that matches regex of `--limit` CLI flag halts run

### ISSUE THREAD

**Issue by themanifold** [Fizzadar/pyinfra#800]
## Describe the bug
A file in the root of a pyinfra project that matches regex of `--limit` CLI flag halts run. The file that matches seems to be treated like a target host in the inventory.

## To Reproduce
Steps to reproduce the behavior (include code & usage example):

1. Directory structure and code:

`inventory.py`, contents:
```
servers = ["example.com"]
```
`example-file`, empty
`test.py`, contents:
```
from pyinfra.operations import files

server.shell(
    commands=["ls"]
)
```
2. Command line:
```
$ pyinfra -vv --debug --limit example* inventory.py test.py 
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...
    [pyinfra_cli.inventory] Checking possible group_data directory: /home/user/workspace/foo
    No host matches found for --limit pattern: example-file

--> Connecting to hosts...

--> Preparing operations...
    Loading: test.py

--> Proposed changes:

--> Beginning operation run...
--> Results:
```

## Expected behavior
In this instance, l would expect `ls` to be executed in the home directory of the user that is executing this pyinfra script. I would not expect the `example-file` file to have any effect on `--limit example*` CLI flag, it should not be treated like a pyinfra target host.

## Meta
+ Include output of `pyinfra --support`.
```
pyinfra --support
--> 
    System: Linux
      Platform: Linux-5.10.105-1-MANJARO-x86_64-with-glibc2.35
      Release: 5.10.105-1-MANJARO
      Machine: x86_64
    pyinfra: v2.0.2
    Executable: /home/user/workspace/foo/venv/bin/pyinfra
    Python: 3.10.2 (CPython, GCC 11.1.0)
```
+ How was pyinfra installed (source/pip)? 
  + pip
+ Include pyinfra-debug.log (if one was created): 
  + none created
+ Consider including output with `-vv` and `--debug`.
  + done

**Comment by Fizzadar** [comment]
Hi @themanifold - this is actually a shell problem/gotcha! You need to quote any glob-like patterns (`--limit 'example*'`) otherwise the shell will automatically expand the filenames before being passed into pyinfra. Ref: https://www.gnu.org/software/bash/manual/bash.html#Filename-Expansion

**Comment by themanifold** [comment]
> Hi @themanifold - this is actually a shell problem/gotcha! You need to quote any glob-like patterns (`--limit 'example*'`) otherwise the shell will automatically expand the filenames before being passed into pyinfra. Ref: https://www.gnu.org/software/bash/manual/bash.html#Filename-Expansion

Gah, can't believe I fell for this. Every time. Thanks for looking at it though.
