### ISSUE TITLE
Wrong link_target in Link Fact on RHEL 6

### ISSUE THREAD

**Issue by julienlavergne** [Fizzadar/pyinfra#801]
## Describe the bug
Running `stat` on a link on a RHEL 6 os returns the following file line:
`` File: `xxx' -> `yyy' ``

The link_target returned by the fact is set to `` `yyy `` in that case, instead of the expected `yyy`.

Note that on top of trimming `'`, we also need to trim `` ` ``

**Comment by Fizzadar** [comment]
This was [actually fixed a while back in May](https://github.com/Fizzadar/pyinfra/commit/fbdf13b12c7b4698d5a67033b1d6e5049f58b985) but I clearly missed updating here! Just [added a quick test](https://github.com/Fizzadar/pyinfra/commit/b0a0252edf40a0d7c7b3c8d83dfff4b87a068eec) to ensure this going forward too.
