### ISSUE TITLE
New argument to complement _ignore_errors to continue op commands on error

### ISSUE THREAD

**Issue by julienlavergne** [Fizzadar/pyinfra#812]
## Describe the bug
When using `server.user` operation, with `_ignore_errors=True`, the operation stops at first error.

Especially, when trying to change user home directory and change ssh keys in authorized keys, ssh keys won't be changed if the user home directory fails to be modified.

In my case, changing user home directory fails with error `usermod: user XXX is currently used by process 14997`. Which I want to bypass with `_ignore_errors=True`. But the operation seems to exists immediately and ssh keys provided in `public_keys` parameter are not updated.

## To Reproduce
Modify a user while it is being used

```python
import posixpath

from pyinfra.operations import server

server.user(
    name=f"Create user account",
    user="XXX",
    home="/home/YYY",
    public_keys=["A", "B", "C"],
    delete_keys=True,
    ensure_home=False,
    _sudo=True,
    _ignore_errors=True,
)
```

## Expected behavior

When `_ignore_errors=True`, I am expecting `server.user` to do its best to apply the changes I want. If the user already exists and changes can only be applied partially, I expect them to be applies partially.

Note that current behavior give unpredictable results because which changes will be applied depends of the order in which operations are performed in `server.user`

## Meta
v2.1

**Comment by Fizzadar** [comment]
I'm not sure this is the right approach for `_ignore_errors` which specifically ignores operation errors, rather than individual commands. Changing this behaviour to continue executing commands after a failure could have unintended consequences.

As an alternative I propose a new argument, `_continue_on_error` (or similar), which explicitly enables this behaviour.

**Comment by julienlavergne** [comment]
I might prefer to have some more fine grained function to handle users. The current one is doing too much, but creating a user and managing authorized_keys are independent actions to me.

**Comment by Fizzadar** [comment]
> I might prefer to have some more fine grained function to handle users. The current one is doing too much, but creating a user and managing authorized_keys are independent actions to me.

That's a great point. I think separating out a `user_authorized_keys` operation would be a good addition.

**Comment by Fizzadar** [comment]
Have implemented the user keys operation here: https://github.com/Fizzadar/pyinfra/commit/1e3e5b4b8ec33d20dca14eb0deb0cf0f71e87cd7, and also added continue on error support in https://github.com/Fizzadar/pyinfra/commit/911594ba77ca34de38971f699eecd4b091cf1430.
