### ISSUE TITLE
server.user ensure_home fails on symbolic link

### ISSUE THREAD

**Issue by julienlavergne** [Fizzadar/pyinfra#813]
## Describe the bug

If user home directory exists and is a symbolic link, using `server.user` operation with `ensure_home=True` will fails saying home directory is not a folder.

## To Reproduce
On a user whose home directory is a symbolic link

```python
server.user(
    name=f"Create user account",
    user="XXXX",
    home="/home/XXXX",
    ensure_home=True,
    _sudo=True,
)
```

## Expected behavior
`ensure_home` should create the directory if needed. But if there is already a symbolic link pointing on a directory, then there is no need to do anything or to fail.

## Meta
v2.1

**Comment by Fizzadar** [comment]
This should now be fixed in https://github.com/Fizzadar/pyinfra/commit/5707fc04d181919da5ecae65dd44f869b5ce5961, released just now in v2.3. Just pushed an additional test in https://github.com/Fizzadar/pyinfra/commit/3397c5b90743e7560fc76c5c36d18a16fc2b88c4 as well.
