### ISSUE TITLE
mysql.database - command() got an unexpected keyword argument 'user_hostname'

### ISSUE THREAD

**Issue by joserdot** [Fizzadar/pyinfra#820]
## Describe the bug

Error when creating the database, does not know the default argument

## To Reproduce

```
mysql.user(
    name='Create the zabbix@localhost MySQL user',
    user='zabbix',
    password='zabbix',
    _sudo=True
)

mysql.database(
    name='Create the zabbix MySQL database',
    database='zabbix',
    user='zabbix',
    charset='utf8mb4',
    collate="utf8mb4_bin",
    _sudo=True
)
```

## Expected behavior
Successful database creation

## Meta
+ Include output of `pyinfra --support`.
```
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-5.17.7-300.fc36.x86_64-x86_64-with-glibc2.35
      Release: 5.17.7-300.fc36.x86_64
      Machine: x86_64
    pyinfra: v2.1
    Executable: /home/jose/.local/bin/pyinfra
    Python: 3.10.4 (CPython, GCC 12.0.1 20220308 (Red Hat 12.0.1-0))
 
```
+ How was pyinfra installed (source/pip)?  pip

+ Consider including output with `-vv` and `--debug` 

[debug001.log](https://github.com/Fizzadar/pyinfra/files/8767758/debug001.log)
[debug002.log](https://github.com/Fizzadar/pyinfra/files/8767759/debug002.log)

**Comment by Fizzadar** [comment]
Thanks for reporting this @joserafaelterra - should now be fixed in `v2.2` by https://github.com/Fizzadar/pyinfra/commit/e0f6fb56de092195a3f26871724f906a75ffd560. I've also added a test to prevent this kind of thing slipping through in the future (https://github.com/Fizzadar/pyinfra/commit/d47056c826db667c9dc963a510c195426af6a7b5).
