### ISSUE TITLE
Add support for useradd -m, —create-home

### ISSUE THREAD

**Issue by yun** [Fizzadar/pyinfra#826]
## Is your feature request related to a problem? Please describe
Currently when creating an user using pyinfra the `-m` or `—create-home` flag is not passed to the `useradd` command.
This flag ensures that the home directory is created but also initialized with files from the `/etc/skel` skeleton directory such as `.bashrc`, `.bash_aliases`, `.profile`, etc.

As a current workaround I currently spawn shell scripts with the `install` command manually to some skeleton files after the user is created.

## Describe the solution you'd like
it would be nice if `server.user` operation supports the following new keywords:

 - `create_home=False` (for the -m flag, if True)
 - `skeleton=None` (for the -k flag, if specified)

eg:

```python
server.user(“user”, create_home=True, skeleton=“/etc/skel2”)
```

I already added this locally as a test and it works, but I have not tested this with other *NIX distributions so i’m hesitant to make a PR. Also, I’m not sure if this overlaps the current `ensure_home` flag, so ideas and discussion is welcome.

**Comment by Fizzadar** [comment]
Support added for this just now in v2.3 (https://github.com/Fizzadar/pyinfra/commit/9f0df3a4e68ff4c746061a42ff080ad5244d003d)!

**Comment by yunzheng** [comment]
Nice!
