### ISSUE TITLE
how can i reuse ssh connection like ssh argument ControlMaster in pyinfra

### ISSUE THREAD

**Issue by samegek** [Fizzadar/pyinfra#827]
pyinfra host10.py exec -- whoami
this will connect ssh remote machine
then 
pyinfra host10.py exec -- hostname
this will connect ssh remote machine
but i will reuse above ssh connection, dont reconnect remote

**Comment by samegek** [comment]
it can do this thing. im wrong

**Comment by Fizzadar** [comment]
@samegek did you manage to do this? I was about to reply saying I didn't think this was possible!

**Comment by samegek** [comment]
> @samegek did you manage to do this? I was about to reply saying I didn't think this was possible!

uncomment the following line in ssh config
![image](https://user-images.githubusercontent.com/14978256/181446776-a530bbfd-1733-49a1-a693-7534b1e48f2c.png)
