### ISSUE TITLE
"Using the API" page not easily found in 2.x docs

### ISSUE THREAD

**Issue by rsyring** [Fizzadar/pyinfra#837]
## Describe the bug

I was looking for the "Using the API" page in the 2.x docs.  It's easily found in the 1.x docs navigation under "How pyinfra Works" but I had to do a Google site search to find it in the 2.x docs.

It would seem it's still [present and rendered](https://docs.pyinfra.com/en/2.x/api/index.html) in 2.x docs but nothing links to it.

## Expected behavior

I would expect the page to be in the navigation like it was in the 1.x docs.

**Comment by Fizzadar** [comment]
I have been toying with the idea of removing the api documentation entirely as is unstable but there’s clearly interest in it, so will fix this!
