### ISSUE TITLE
files.put operation does not work with IO-like objects

### ISSUE THREAD

**Issue by ghost** [Fizzadar/pyinfra#841]
## Description of the bug
The `files.put` operation says it can "Upload a local file, or file-like object, to the remote system.", argument `src` can be "filename or IO-like object to upload". I can't get it to work though. In [the operation](https://github.com/Fizzadar/pyinfra/blob/2.x/pyinfra/operations/files.py#L873), it does:

```python
 if assume_exists and not os.path.isfile(local_file):
    local_sum = None
else:
    local_sum = get_file_sha1(src)
```

`src` and `local_file` are always the same once you get here. Either `os.path.isfile` is called, which gives
```
TypeError: stat: path should be string, bytes, os.PathLike or integer, not _io.StringIO
```
or we try to `get_file_sha1` which expects a path not an IO-like object, so it eventually fails with 

```
  File "/..../.venv/lib/python3.8/site-packages/pyinfra/facts/files.py", line 223, in process
    regex = regex % re.escape(self.path)
  File "/usr/lib/python3.8/re.py", line 277, in escape
    pattern = str(pattern, 'latin1')

TypeError: decoding to str: need a bytes-like object, PosixPath found
```

## To Reproduce
Try to `files.put` anything that is not a file on your local system.

## Expected behavior
This should work with IO-like objects, or the documentation should state it is only intended to work with on-disk files and `src` should be a path.

## Meta
+ Include output of `pyinfra --support`.
```
System: Linux
      Platform: Linux-5.13.0-44-generic-x86_64-with-glibc2.29
      Release: 5.13.0-44-generic
      Machine: x86_64
    pyinfra: v2.2
    Executable: ~/code/project/.venv/bin/pyinfra
    Python: 3.8.10 (CPython, GCC 9.4.0)
```
+ How was pyinfra installed (source/pip)?
pip

**Comment by Fizzadar** [comment]
Thanks for reporting this @bouke-sf, looks like an issue specific to combining `assume_exists` and a IO-like object; I've pushed out a quick fix in https://github.com/Fizzadar/pyinfra/commit/689316761d888721f9d07e28eaa6759dc7926e4b just in time for v2.3 release :)
