### ISSUE TITLE
CONTRIBUTING not consistent with code (setup.cfg and pyproject.toml)

### ISSUE THREAD

**Issue by morrison12** [Fizzadar/pyinfra#870]
## Describe the bug
The third bullet under [Contributing/Code Style](https://docs.pyinfra.com/en/latest/contributing.html#code-style) says _single quotes everywhere possible_ but 
1. in ``setup.cfg`` line 13 is ``inline-quotes = double`` 
and  
2. in ``pyproject.toml``  ``skip-string-normalization = true`` is not present in the ``[tool.black]`` section which ensures ``black`` will normalize quotes to double quotes 

I'm happy to provide a PR but wanted to check whether the style has changed first

## To Reproduce
n/a

## Expected behavior
If  [Contributing/Code Style](https://docs.pyinfra.com/en/latest/contributing.html#code-style) is still correct,  the settings for ``flake8`` and ``black`` should match it.

## Meta
current HEAD on 2022-08-10

**Comment by Fizzadar** [comment]
Thanks for spotting this @morrison12! Updated to black/isort in https://github.com/Fizzadar/pyinfra/commit/94efd2b3d46df5dd9664dadc147d0730e601a1b9.
