### ISSUE TITLE
Incorrect documentation and docstring for python.call

### ISSUE THREAD

**Issue by swsnr** [Fizzadar/pyinfra#886]
## Describe the bug
The [docstring of python.call](https://github.com/Fizzadar/pyinfra/blob/958b5ef8f076fdb644970efd7213b6f23c017879/pyinfra/operations/python.py#L12) shows a function which takes a `state` and a `host` argument.

The implementation however removes these arguments and emits a warning.

**Comment by Fizzadar** [comment]
Thank you for pointing this out, now fixed!
