### ISSUE TITLE
SSH authentication error

### ISSUE THREAD

**Issue by pikeas** [Fizzadar/pyinfra#890]
## Describe the bug
Pyinfra is unable to connect to a server over ssh.

## To Reproduce
```
$ pyinfra --debug server.example.com exec -- ls
--> Loading config...
--> Loading inventory...
    [pyinfra_cli.inventory] Creating fake inventory...
--> Connecting to hosts...
    [pyinfra.connectors.ssh] Connecting to: server.example.com ({'allow_agent': True, 'look_for_keys': True, 'hostname': 'server.example.com', '_pyinfra_ssh_forward_agent': None, '_pyinfra_ssh_config_file': None, '_pyinfra_ssh_known_hosts_file': None, '_pyinfra_ssh_strict_host_key_checking': None, '_pyinfra_ssh_paramiko_connect_kwargs': None, 'timeout': 10})
    [pyinfra.connectors.sshuserclient.client] Loading SSH config: None
    [server.example.com] Authentication error () (Authentication failed.)
    [pyinfra.api.state] Failing hosts: server.example.com
--> pyinfra error: No hosts remaining!
```

```
# ~/.ssh/config
Host *.example.com
    User [...]
    IdentityFile [...]
```

## Expected behavior
Pyinfra should display additional error information when unable to connect.

## Meta

```
    System: Darwin
      Platform: macOS-12.3.1-arm64-arm-64bit
      Release: 21.4.0
      Machine: arm64
    pyinfra: v2.4
    Executable: /Users/pikeas/repo/code/py/.venv/bin/pyinfra
    Python: 3.10.7 (CPython, Clang 14.0.0 (clang-1400.0.29.102))
```

**Comment by Fizzadar** [comment]
>     [pyinfra.connectors.sshuserclient.client] Loading SSH config: None

This line looks very suspicious to me! Could you try again but explicitly set the config file:

```
pyinfra --debug server.example.com --data ssh_config_file=/Users/pikeas/.ssh/config exec -- ls
```

I'm not sure why it doesn't automatically pick it up, if we confirm the above works then at least we know where the problem is!

**Comment by pikeas** [comment]
The cause of my issue was that my SSH agent hadn't loaded keys into memory. I've just removed the keys from memory to share a repro and...of course there's a proper error now:

```
$ ssh-add -D
$ pyinfra server.example.com exec -- ls
--> Loading config...
--> Loading inventory...

--> Connecting to hosts...
    [server.example.com] Authentication error () (Private key file is encrypted)
--> pyinfra error: No hosts remaining!
```

I haven't made any changes to my client (MacOS laptop) since opening the issue, especially not removing my SSH config file. The only thing I can think of is that MacOS has different handling on "first" (post-reboot) use of the agent, which may bubble up differently.

I'll close this issue for now - if pyinfra didn't see a config file, everything else worked as expected. I'll reopen if I can repro the issue with the config.
