### ISSUE TITLE
Running pyinfra locally

### ISSUE THREAD

**Issue by hoh** [Fizzadar/pyinfra#90]
I am looking to run pyinfra locally instead of over SSH (on a desktop compute for example). 

Is there a way to execute the commands locally (like [`subprocess.run`](https://docs.python.org/3/library/subprocess.html) ) ?

At the moment, I use a very horrible hack:
```bash
#!/bin/bash

sudo bash -c 'cat /home/hoh/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys'

./venv/bin/pyinfra -i inventory/desktops.py deploy.py

sudo bash -c 'echo "" > /root/.ssh/authorized_keys'
```

**Comment by Fizzadar** [comment]
I like this idea - I think the best approach would be multiple "connection adapters", each of which would only need implement the function set from the [ssh](https://github.com/Fizzadar/pyinfra/blob/develop/pyinfra/api/ssh.py) API, eg `pyinfra/api/connectors/local.py`.

**Comment by Fizzadar** [comment]
This is now (finally!) possible as of https://github.com/Fizzadar/pyinfra/commit/8800ece45e9d4f884b6af6d3b328c7a4e6e85d0a. Pending the upcoming `v0.4` release.

Syntax is as follows (using the new CLI format):

```sh
pyinfra @local deploy.py
```

**Comment by hoh** [comment]
Awesome !
