### ISSUE TITLE
Use _precondition without erroring

### ISSUE THREAD

**Issue by sebastianelsner** [Fizzadar/pyinfra#909]
I want an operation to run only if _precondition is "true". If it is not true, I don't want the operation to run and not produce errors. Currently,  after the error the deploy stops.

The use case behind this request is to make third party software "installers" kind of "idempotent". It would be nice to separate the "precondition" from the execution of an installer.

This is the way I would do it right now:

```bash
    server.shell(
        name="Install Houdini",
        commands=[
            "if [! -d ./hfs19.5.403 ]; then "
            "./houdini_installer install "
            "--product Houdini "
            "--version 19.5.403 "
            "; fi"
        ],
    )
```

vs. this is a "nicer" way

```bash
    server.shell(
        name="Install Houdini",
         _precondition="! test -d ./hfs19.5.403",
        commands=[
            "./houdini_installer install "
            "--product Houdini "
            "--version 19.5.403 "
        ],
    )
```

This way an operation would also not show up as "Changed" in the summary.

Does this request make sense?

I have been using similar functionality in Puppet with the "onlyif => ..." module directive.

**Comment by Fizzadar** [comment]
Hi @sebastianelsner! Does the `./hfs19.5.403` file get created earlier on or as part of the install command? If install you could do the following:

```py
from pyinfra.facts.files import Directory
from pyinfra.operations import server

if not host.get_fact(Directory, path="./hfs19.5.403"):
    server.shell(name="Install Houdini", ...)
```

This best fits the two phase diff-then-apply way pyinfra works.

**Comment by sebastianelsner** [comment]
Ah, I see! This solves my case. Thank you!
