### ISSUE TITLE
example code for `ssh.command` is invalid python

### ISSUE THREAD

**Issue by minusf** [Fizzadar/pyinfra#933]
## Describe the bug
example code for `ssh.command` is invalid python

```python
ssh.command(
    name="Create file by running echo from host one to host two",
    hostname="two.example.com",
    command="echo "one was here" > /tmp/one.txt",
    user="vagrant",
)
```

## To Reproduce
read https://docs.pyinfra.com/en/2.x/operations/ssh.html#ssh-command

## Meta
```
    System: Darwin
      Platform: macOS-13.1-arm64-arm-64bit
      Release: 22.2.0
      Machine: arm64
    pyinfra: v2.5.3
    Executable: ./venv/bin/pyinfra
    Python: 3.10.8 (CPython, Clang 14.0.0 (clang-1400.0.29.102))
```

**Comment by Fizzadar** [comment]
Thanks for catching this, fixed via https://github.com/Fizzadar/pyinfra/commit/664d3ba847ba5cfc1166f01c056b79ce17e2073a.

**Comment by minusf** [comment]
thanks for looking into this.  do the commits publish automatically? 😅
