### ISSUE TITLE
Update ls to use iso dates (test_facts running into a problem in 2017)

### ISSUE THREAD

**Issue by danstender** [Fizzadar/pyinfra#94]
Hi,
this is running into a problem:
```
$ faketime 'next year' python3 -m nose
...............................F..F....F...................................................................................................................................
======================================================================
FAIL: test_valid (tests.test_facts.TestTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jsontest.py", line 13, in test
    self.jsontest_function(test_name, test_data)
  File "/tmp/sandbox/pyinfra-0.2/tests/test_facts.py", line 43, in jsontest_function
    raise e
  File "/tmp/sandbox/pyinfra-0.2/tests/test_facts.py", line 36, in jsontest_function
    self.assertEqual(data, test_data['fact'])
AssertionError: {'size': '8', 'mtime': '2017-02-13T12:56:00', 'mode': 77[36 chars]fra'} != {'size': '8', 'user': 'pyinfra', 'mtime': '2016-02-13T12[36 chars]fra'}
  {'group': 'pyinfra',
   'mode': 777,
-  'mtime': '2017-02-13T12:56:00',
?               ^

+  'mtime': '2016-02-13T12:56:00',
?               ^

   'size': '8',
   'user': 'pyinfra'}
-------------------- >> begin captured stdout << ---------------------
```
Best,
DS

**Comment by Fizzadar** [comment]
@danstender this happens because by default `ls` only gives the day/month when a file is created in the current year - so pyinfra _assumes_ the current year, causing the test to fail when this is changed.

I'm going to change the `ls` command to output ISO dates (unfortunately it'll have to become `ls -ld --time-style=full-iso || ls -ldT` to support both Linux/BSD). Which should mean all `ls` based facts have the full date & time.

**Comment by danstender** [comment]
Great! Tests are temporarily failsafed in the Debian package (for reproducible builds - one test environment builds a year in front), that fix would be welcome. Thx in advance.

**Comment by Fizzadar** [comment]
@danstender this is now fixed @ https://github.com/Fizzadar/pyinfra/commit/266c0cfc4274d542f3f7472ff09b30508ed54930 and will be in the v0.2.3 cut in the coming weeks :)

**Comment by danstender** [comment]
Great! Thx.
