### ISSUE TITLE
Looks like «_has_package» from «pyinfra/operations/util/packaging.py» works wrong

### ISSUE THREAD

**Issue by belonesox** [Fizzadar/pyinfra#949]
## Describe the bug

I catched situation with missing DNF package after pyinfra 2.6 operation.

```python
dnf.packages(
    name="Test packages RPMs",
    packages=["caddy"],
    _sudo=True,  
)
```

I am not sure, that I can easily provide convinient reproducable environment (publicly available virtual machine in some cloud? OVA/qcow fromm virtualbox/qemu/docker…).

But I did some debugging, and I see strange behaviour, probable suspect. 

```python
def _has_package(package, packages, expand_package_fact=None, match_any=False):
```
 definitely should return ``True`` only if package is installed (it exists exists in ``packages``). 
But last lines of this function return ``True`` even if no such package exists, because ``all([])==True``.

```python
…
    if match_any:
        return any(checks), package_name_to_versions
    return all(checks), package_name_to_versions
```

Illustrative scheme from my debugging 

![image](https://user-images.githubusercontent.com/1609739/215815484-4d3ad810-115c-434c-849d-d9be9cd9db27.png)

I hope, this scheme can describe the issue…  
If not, I will try to make reproduceable environment, but not sure, how much time it takes if  I can succeed even.

## Meta
+ Include output of `pyinfra --support`.
```
--> Support information:

    If you are having issues with pyinfra or wish to make feature requests, please
    check out the GitHub issues at https://github.com/Fizzadar/pyinfra/issues .
    When adding an issue, be sure to include the following:

    System: Linux
      Platform: Linux-6.0.15-200.fc36.x86_64-x86_64-with-glibc2.35
      Release: 6.0.15-200.fc36.x86_64
      Machine: x86_64
    pyinfra: v2.6
    Executable: /usr/local/bin/pyinfra
    Python: 3.10.9 (CPython, GCC 12.2.1 20221121 (Red Hat 12.2.1-4))
```
+ How was pyinfra installed (source/pip)?
pip

**Comment by Fizzadar** [comment]
Hi @belonesox, thank you for reporting this! I am unable to replicate it currently, a reproducible environment would be extremely helpful (docker if possible).

Following the code it seems if `package_name_to_versions` is non-empty the checks should always contain values. Might be worth converting checks to a list rather than a generator for testing here too.

**Comment by Fizzadar** [comment]
No repro, please re-open if you have/get one.
