### ISSUE TITLE
Missing operation to reload Systemd

### ISSUE THREAD

**Issue by hoh** [Fizzadar/pyinfra#97]
After adding or changing a systemd service file (`/etc/systemd/system/*.service`), it is necessary to run `systemctl daemon-reload` in order to make systemd aware of the changes. There is no operation to do this at the moment.

One solution would be to add this as an option to the `init.systemd` operation such as
```python
init.systemd(name, running=True, restarted=False, reloaded=False, command=None, 
enabled=None, daemon_reload=False)
```

**Comment by Fizzadar** [comment]
Closed @ https://github.com/Fizzadar/pyinfra/commit/3ad16d530d494dab4c70be2847900459509f1d48
