### ISSUE TITLE
Persist SSH connection across operations

### ISSUE THREAD

**Issue by link2xt** [Fizzadar/pyinfra#988]
pyinfra uses [Paramiko](https://github.com/paramiko/paramiko/) which currently does not support SSH multiplexing with persistent connection as configured by the `ControlPersist` option of the SSH config: https://github.com/paramiko/paramiko/issues/852

Opening a new connection for each operation slows down pyinfra and may trigger IDS if it is installed on the server.

A solution could be to persist the connection within pyinfra itself instead of opening a new SSH connection each time.

**Comment by Fizzadar** [comment]
This is incorrect - pyinfra only connects to each host once and maintains the same paramiko connection throughout. The control persist mechanism is specifically to reuse connections between different processes.

Each command requires a new ssh channel which is lightweight to setup. It’s possible to bypass this by combining commands together but you loose the ability to grab exit codes so is a non starter..
