### ISSUE TITLE
Adding a public key does not work

### ISSUE THREAD

**Issue by sebastianelsner** [Fizzadar/pyinfra#999]
## Describe the bug
Adding a public key to a user does not work when there are already existing keys.

## To Reproduce
I have this deploy:

```python
@deploy("ssh key")
def ssh_keys():
    with open("a.pub") as f:
        k1 = f.read()
    with open("b.pub") as f:
        k2 = f.read()
    server.user("user", public_keys=[k1, k2])
```

I add another key:

```python
@deploy("ssh key")
def ssh_keys():
    with open("a.pub") as f:
        k1 = f.read()
    with open("b.pub") as f:
        k2 = f.read()
    with open("c.pub") as f:
        k3 = f.read()
    server.user("user", public_keys=[k1, k2, k3])
```

## Expected behavior
I expect k3 to be added.

## Meta
+ Include output of `pyinfra --support`.

```
    System: Linux
      Platform: Linux-6.4.7-100.fc37.x86_64-x86_64-with-glibc2.36
      Release: 6.4.7-100.fc37.x86_64
      Machine: x86_64
    pyinfra: v2.7
    Executable: /home/sebels/venv/bin/pyinfra
    Python: 3.11.4 (CPython, GCC 12.3.1 20230508 (Red Hat 12.3.1-1))
```
+ How was pyinfra installed (source/pip)?

pip

## My Debug

I was able to trace the issue down to :
https://github.com/Fizzadar/pyinfra/blob/44ce3fa8ed689ffca6cc79aadfa61f4b72754bac/pyinfra/operations/files.py#L473

As commented in the code this is the situation we have: Line(s) exists and we want to ensure they're correct. But we never enter the "if" in the line below:
https://github.com/Fizzadar/pyinfra/blob/44ce3fa8ed689ffca6cc79aadfa61f4b72754bac/pyinfra/operations/files.py#L476
This is because "replace" is an empty string "".
Could it be the if should be "replace is None" instead of "replace is ''"?

**Comment by sysadmin75** [comment]
The issue turns out to be a problem when reading in a public key on the host. The string has a newline (if the key has one).  This caused the `process` command in FindInFile to return any existing lines, which threw off the logic in the rest of the `files.line` operation.
